### ISSUE TITLE
[NPC] Ahn'Kahet's Spellweavers

### ISSUE THREAD

**Issue by Ashamedlol** [wow-mania/Redemption#1]
So in this dungeon, you encounter variated types of nerubian mobs from poison spider to webweaver to the normal one and there's the spellweaver. However, the spellweaver does not work properly because he channel a certain spell called Shadow Sickle which does nothing (supposed to do something) then stands at his place without attacking, then suddenly casts Shadow Blast (his only working mechanic).

**Comment by wow-mania** [comment]
Need correct NPC name or entry id.
