### ISSUE TITLE
[Quest] Troll Patrol: What ya Want a Medal

### ISSUE THREAD

**Issue by wow-mania** [wow-mania/Redemption#1]
ID#12519 

Title "Troll Patrol: What ya Want a Medal" You are supposed to collect the medals from the corpses outside the arena. Unfortunately there are no corpses there to collect them from. 

http://www.wowhead.com/quest=12519/troll-patrol-whatdya-want-a-medal
http://www.wowhead.com/npc=28162/drakkari-corpse

**Comment by fvicaria** [comment]
Fixed for Release 9.
