### ISSUE TITLE
[NPC] Enemies sinking into the ground

### ISSUE THREAD

**Issue by saucemin** [wow-mania/Redemption#10]
I have had this strange problem for a while. 
(Keep in mind that just when this issue occurs is completely random.) 
Say I see an enemy on a hill, and I go to attack it. When I go into combat, the enemy sinks into the ground and is sometimes unreachable. This can be slightly solved by leading the enemy out of the hill, but the bottom of it is still phasing through the ground.  Sometimes everything will be fine but then when the enemy dies, it sinks and I am unable to loot it. This doesn't happen with any specific NPC or in any specific area. It's not gamebreaking, but it can be kind of annoying at times!

**Comment by wow-mania** [comment]
Please give names and location.

**Comment by saucemin** [comment]
This issue can happen anywhere. There is no specifics.
