### ISSUE TITLE
[Quest] The Great Fras Siabi

### ISSUE THREAD

**Issue by Nogrial** [wow-mania/Redemption#100]
Windows 7 / Using Client

After picking up The Great Fras Siabi from Smokey LaRue, in Eastern Plaguelands Lights Hope Chapel, I went into Stratholme w/friend and got to the tabacco shop described in quest. There is clearly a box in front of the shop, but it isn't clickable or hoverable, my friend also had the quest and was unable to get the item needed. 

Could be related to #101

**Comment by GMLucetta** [comment]
Confirmed. tested today and http://www.wowhead.com/quest=5214/the-great-fras-siabi cannot be completed.
