### ISSUE TITLE
[Stratholme] Supply Boxes unclickable/lootable but can hover over them. 

### ISSUE THREAD

**Issue by Nogrial** [wow-mania/Redemption#101]
Windows 7/ Using Client

I went through and tried to collect every Supply Crate in Stratholme. At first I thought the supply crates to the left of the road, as you travel through the map, weren't lootable. After much investigation, I would estimate about 30% Supply Crates were lootable, while the rest were NOT. Could be related to #100 However, I don't know.

**Comment by Calebrimbor** [comment]
Fix is confirmed. Status on BugTracker set as 'Fixed'.
