### ISSUE TITLE
Dying after fighting/fleeing and holding W,A,S,D causes my character to be freeze

### ISSUE THREAD

**Issue by Nogrial** [wow-mania/Redemption#102]
Windows 7 / Using Client

I am unable to recreate consistently, this could be a non issue also, because of a conflict with an addon.

 While running to a mob or away from a mob while fighting, then dying causes my dead spirit to be unable to move using W,A,S,D

- I can type and mouse click, just cannot move

- Could be because I am a goblin and some times use goblin jump during a fight to try to evade mobs. 

Steps to fix known issue:

- Reload UI from addon tab.

**Comment by genasi** [comment]
Its happened to me on mage and warrior, neither are goblin nor have engineering. I did however die while trying to get out of an aoe with both toons.
It can be solved as OP suggest or with a /reload

**Comment by Kalasbyxan** [comment]
Can't confirm, does not happen on different characters and classes. Must be a more singled out issue than a general. Since a /reload works, I suggest we stick to that.
