### ISSUE TITLE
[Quest] The Heart of the Mountain

### ISSUE THREAD

**Issue by Nogrial** [wow-mania/Redemption#103]
Windows 7 / Using Client

Maxwort Uberglint in Burning Steppes gives this quest.
- Quest suggests that after opening all of the relic coffer vaults, a boss appears. I think he only spawns once we've looted all of the chests. 
- We are capable of opening all of the Relic coffer Vault doors, but not the chests. They aren't even hoverable
- every time I've tried this event, I haven't had the Dark Keepers Key  either
- possible it is the same bug or same issue noted in #100 and #101 ?

**Comment by Calebrimbor** [comment]
Confirmed!
http://www.wow-mania.com/armory/?item=11309

The Dark Keeper's Key(http://www.wow-mania.com/armory/?item=11197) should drop from Dark Keeper mobs, these mobs are not there. Therefore you can't open the vault where this Heart of the Mountain(http://www.wow-mania.com/armory/?item=11309) should be in. Opening this vault with adding the key to my inventory will show you a unclickable chest. All the other vaults you could open with the Relic Coffer Key(http://www.wow-mania.com/armory/?item=11078) contain a chest which is not clickable. This quest is not doable.

![wowscrnshot_091316_124235](https://cloud.githubusercontent.com/assets/20358867/18471064/42ee2592-79b0-11e6-936a-ee06d3f9c4a6.jpg)
