### ISSUE TITLE
[CORE] Dungeon - Blackfathom deeps

### ISSUE THREAD

**Issue by Manapaws** [wow-mania/Redemption#104]
While in Blackfathom Deeps, only the tank and healer would stay in combat after a fight, no mobs were left that we could see. They found if they teleported out of dungeon, they would no longer be combat.

It wouldn't stay that way. After another fight, the tank and healer would again be in combat without anything actually being there..visibly of course.

Just thought I'd let you know about the issue

**Comment by mariogotze** [comment]
Can you describe the spot, where you got into battle?

**Comment by fvicaria** [comment]
The .clearcombat command should sort this out for now.
