### ISSUE TITLE
[Dungeon] Utgarde Keep - Ingvar bugged

### ISSUE THREAD

**Issue by genasi** [wow-mania/Redemption#104]
The last boss in Utgarde Keep, Ingvar, is bugged. He goes to phase 2 just fine, there is some issue with the Val'kyr that arrives to do the resurrect, but he gets back up and the fight continues. When Ingvar is killed 2nd time, his corpse reverts to the phase 1 corpse, he is not lootable and when you leave the dungeon you get the Deserter debuff even though the dungeon is finished and RDF rewards are awarded.

**Comment by wow-mania** [comment]
Should be fixed this Wednesday after update.
Please re-open if it's not OK.
