### ISSUE TITLE
It's All Fun and Games quest is bugged

### ISSUE THREAD

**Issue by Grantagh** [wow-mania/Redemption#105]
In the quest "It's al Fun and Games" I'm supposed to shoot down the big eye above Shadow Vault, but I cant hurt it at all, its health refills immediately, unless I fly really close to it, but in that case it kills me because its ability hits too hard. Its a really big issue, that this quest isn't working as it opens up a ton of  quests in that area.

**Comment by Oriden** [comment]
Fixed, move close to the creature (tbh u should just enter the blue shell)
