### ISSUE TITLE
[QUEST] Last Rites - Borean Tundra Quest

### ISSUE THREAD

**Issue by BrookiCookie** [wow-mania/Redemption#105]
The quest, Last Rites, is obtained from Thassarian while he's on the ground in a small building standing around with Laird, a human necromancer, and the lich he's trying to kill. Upon taking the quest you're instructed to go into the city of En'kilah and teleport up to where Thassarian is, ontop of the scourge base floating overhead. When you teleport Leryssa is standing there, as is a human elite who's name I can't remember. Copies of those two also walk up to where they are standing and hunch over stunned, like they should. The Image of the Lich Ling spawns, and a councilor walks up and is transformed into Prince Valanar, you can kill the prince and the non-stunned Leryssa ends up helping you, but dies so they both vanish anyways. Thassarian stands off to the side staring into space, entirely away from everyone while all of this happens and after Leryssa dies, Prince Valanar stands around while you kill him. After that, nothing changes. The stunned Leryssa is still stunned, the stunned guy and the normal standing guy are both there next to her, and Thassarian is staring off into space. The ones who died dissapear and you're infinitely stuck. I just did this quest from Northrend/Borean Tundra and it didn't end up being fixable directly.

**Comment by MrNorrell** [comment]
Seen this appearing to affect another player.
