### ISSUE TITLE
[Raid] Ulduar's XT-002 Deconstructor

### ISSUE THREAD

**Issue by Ashamedlol** [wow-mania/Redemption#106]
Most of this boss's mechanics work fine, however, the heart mechanic is bugged because there's no timer when the heart will pack up (supposed to be cast by the heart itself as a channel) and when you dps the heart you'll end up dpsing XT-002 for some reason. And if you keep dpsing the heart to dps XT, he will give no loot and no credit (if you were to have weekly quest for example), all of this also leads to an impossible "Heartbreaker" achievement (hardened mode XT-002).

**Comment by Calebrimbor** [comment]
Closing the issue, this quest will be added to [Project](https://github.com/wow-mania/Redemption/projects/3).
