### ISSUE TITLE
[NPC] Herald Volazj in Ahn'Kahet: The Old Kingdom

### ISSUE THREAD

**Issue by BrookiCookie** [wow-mania/Redemption#107]
The boss encounter Herald Volazj is severly bugged, upon casting "Insanity", he normally creates one copy of everyone in combat with him for the certain group, but he created 5 copies or so of every member of the group(25+ with high hit points, depending on your gear). This makes it along the lines of impossible to do.

**Comment by fvicaria** [comment]
That is the correct behaviour. If you party member kills his image first he can come to your help.
