### ISSUE TITLE
[Raid] Ulduar's Iron Council.

### ISSUE THREAD

**Issue by Ashamedlol** [wow-mania/Redemption#107]
This fight also has most of the mechanics working properly, however, Stormcaller Brundir is really bugged because in the real fight he's not supposed to move alot, just stand -> hit tank and cast (with random spell aggro), so what happens is he moves alot on this server so he can end up walking into the wall and getting stuck, and how he moves while casting is also unintended and annoying.

**Comment by Calebrimbor** [comment]
Closing the issue, this quest will be added to [Project](https://github.com/wow-mania/Redemption/projects/3).
