### ISSUE TITLE
[Dungeon] Forge of Souls's Bosses

### ISSUE THREAD

**Issue by Ashamedlol** [wow-mania/Redemption#108]
Bronjahm's Corrupted Soul, if it was death gripped by a deathknight it will remain in place and not move at all which is bugged.

Devourer of Soul is supposed to cast and attack while Mirror Soul is on, Wailing Soul is supposed to be casted towards a party member and then Devourer of Souls starts to spin the beam around the room starting from the original position of the party member that was targeted.

**Comment by Ashamedlol** [comment]
Another thing to add is the Ghosts of Unleashed Souls for some reason are attackable on 5man heroic, meanwhile they're untargetable/undamageable on 5man normal so it's supposed to be undamageable/untargetable on 5man heroic too.

**Comment by Oriden** [comment]
Fixed targettable ghosts & death grip

**Comment by genasi** [comment]
I can add that you shouldnt be able to interrupt Bronjahm's soulstorm spell http://www.wowhead.com/spell=68872

**Comment by Ashamedlol** [comment]
Also, new bug appeared that Devourer of Souls no longer spawns ghosts during Unleashed Souls.

**Comment by Ashamedlol** [comment]
Devourer of Souls SHOULD NOT be autoattacking the tank while using Wailing Soul, I was stepping near the boss and he was autoattacking me plus doing his beam thingy but when I take distance he doesn't attack.

**Comment by Kalasbyxan** [comment]
Can't find either issues in current FoS. Will make new topic if issue arises again.
