### ISSUE TITLE
[Dungeon] Hall of Reflection's LK Encounter

### ISSUE THREAD

**Issue by Ashamedlol** [wow-mania/Redemption#109]
If Arthas/Lich King is further than 30 yards of Sylvanas or Jaina's range, they will not break the Ice Wall and the encounter bugs out (wipe).

**Comment by wow-mania** [comment]
Duplicate #24

**Comment by Ashamedlol** [comment]
Different type of bug, unlootable chest isn't same as wall not opening :p.
