### ISSUE TITLE
[Quest] Corrosive Prevention

### ISSUE THREAD

**Issue by mariogotze** [wow-mania/Redemption#109]
ID#27347
The quest Corrosive Prevention is bugged in a subtle manner, and they only manifest when you have the quest.  The Power Core Fragment near the crash site does't always work.  And, other currently operating Power Core Fragments deactivate when approached, giving only a fraction of a second to pop an Ooze.  The oozes then attack you, so you have to kill them, and when it reactivates, there are no slimes to pop.

**Comment by fvicaria** [comment]
Should be fixed now.
