### ISSUE TITLE
[Quest] Sacrifices must be made

### ISSUE THREAD

**Issue by Kalasbyxan** [wow-mania/Redemption#11]
The quest (http://wow-mania.com/armory/?quest=12007) can not be completed as the NPC does not appear when using the item (35797) at the brazier. Tried to find a trigger point around and on it with no success. The NPC shows in GM mode but not in player mode.

**Comment by wow-mania** [comment]
You need Zimbo's Mojo to summon it also.
http://www.wowhead.com/item=35836/zimbos-mojo#reagent-for

Worked fine for me.
