### ISSUE TITLE
[NPC] Azure Dragon

### ISSUE THREAD

**Issue by mariogotze** [wow-mania/Redemption#11]
In Wyrmrest Temple sometimes when im flying to upper level using Tariolstrasz im attacked and instant killed by Azure drake.

**Comment by mariogotze** [comment]
Confirmed

**Comment by wow-mania** [comment]
Can you get the id of the NPC and the GUID please. Thanks!

**Comment by fvicaria** [comment]
Just move around and avoid the drake.
