### ISSUE TITLE
[Raid] Ruby Sanctum's Halion

### ISSUE THREAD

**Issue by Ashamedlol** [wow-mania/Redemption#112]
At phase transitioning to Shadow Realm, if you don't enter fast enough Halion will consider himself out of combat and immediately reset his health to 100%, making shadow realm a 100% to 50% fight which isn't good due to the beserker timer existing on the boss.

And if you release during the fight encounter, the whole raid will bug into a "Encounter in Progress".

**Comment by wow-mania** [comment]
#260
