### ISSUE TITLE
[Dungeon] Utgarde Pinnacle's Skadi the Ruthless

### ISSUE THREAD

**Issue by Ashamedlol** [wow-mania/Redemption#113]
Harpoons scale with spellpower, so if you make a caster pick up a harpoon and shoot skadi, you will kill Skadi immediately and not recieve loot, however, if you let a Rogue or Warrior do so, you'll need 3-shots to take Skadi down to the main place and fight him to be able to loot him. (but Grafi becomes untargetable and unkillable which leads into a bugged achievement for those who seek it.)

**Comment by Ashamedlol** [comment]
A part of this bug report has been partly fixed, I've seen someone get the Skadi Grafi achievement today.

**Comment by Ashamedlol** [comment]
However, I just tested it again and it seems that the original fight tends to work but the issue now is if you don't aggro the mobs within 2-3 seconds of aggroing Skadi, him and the mobs will disappear and you will be locked out of the fight, so you need one to aggro and one to tank I suppose (you're able to refresh the fight by walking into gate then back to Skadi).

**Comment by Calebrimbor** [comment]
Fixed
