### ISSUE TITLE
[Raid] Eye of Eternity, Malygos's Sparks.

### ISSUE THREAD

**Issue by Ashamedlol** [wow-mania/Redemption#114]
Only a few missing mechanics on Malygos, such as Power Sparks not existing: it's a mechanic where you kill the spark flying to Malygos and it'll spawn a ground that increases your DPS by a certain percentage, it's stackable and if it's poorly handled and reaches to Malygos he gets empowered.

**Comment by Ashamedlol** [comment]
New bugs recently: the Nexus Lords move faster than usual, and are suddenly unattackable at certain random circumstances.
If the disc flight dpsers die or drop the disc, the disc will not work anymore.

**Comment by Kalasbyxan** [comment]
**Power Sparks** (http://www.wow-mania.com/armory/?npc=30084) gets emoted "_A Power Spark forms  from a nearby rift!_" but never spawn. It should be a spark travelling towards Malygos and when killed, leaves a field on the floor granting the buff **Power Spark** (http://www.wow-mania.com/armory/?spell=56152) which is stackable if several sparks gets killed at the same location.

**Scion of Eternity** (http://www.wow-mania.com/armory/?npc=30249) flying on a Hover Disc (http://www.wow-mania.com/armory/?npc=30248) does not drop disc to floor for player use when killed. The disc stays unusable in the air where the Scion died.

Nexus Lord (http://www.wow-mania.com/armory/?npc=30245) disc does work as intended. Did not experience issues with Nexus Lords. Might be random.
