### ISSUE TITLE
[Dungeon] Ahn'kahet: The Old Kingdom's Trashmobs.

### ISSUE THREAD

**Issue by Ashamedlol** [wow-mania/Redemption#115]
Ahn'kahar Spell Flinger has a bugged spell called Shadow Sickle, it's supposed to be a channeled spell that deals a moderate amount of shadow damage at random targets, their Shadow Blast is also bugged because it's supposed to deal 65% of your maximum health on 5 normal, 80% of your maximum health on 5 heroic but it deals nothing here.
Plague Walkers also have a bugged spell which is called Aura of Lost Hope, it's supposed to be cast ONLY when they're in combat with you, but it's cast all around the instance which leaves you on a 7k maximum HP if you don't clear the whole Plague Walkers.

As for bosses, it's only Herald Volaszj being bugged where he shouldn't be interuptable but at the same time his clones shouldn't be meele hitting you for massive amounts of damage (supposed to be casters of certain spells).

**Comment by genasi** [comment]
link to dungeon: http://www.wowhead.com/zone=4494/ahnkahet-the-old-kingdom
link to boss: http://www.wowhead.com/npc=29311/herald-volazj
According to this guide: http://www.wowhead.com/guides/dungeons/timewalking/ahnkahet-the-old-kingdom-strategy-guide the clones shouldnt be casters, there should be 4 of them and they should have the same abilities as the players.
Quote from guide:
When Volazj reaches 66% health, and again at 33% health, he casts  Insanity, spawning hallucinatory copies of players' allies.
Each player is in his or her own copy of reality, and faces hostile clones of the other members of the party
These clones have the same model and will use the same abilities that the players in your party use, including CC effects
Players must defeat all four of the hostile clones in their version of reality to escape
Upon defeating all four of their own hostile clones, they will be transported at random to another player's copy of reality and can assist that player in defeating the clones
Once every player's hostile clones have been defeated,  Insanity ends and players can engage Volazj again.
