### ISSUE TITLE
Quest You Can't Miss Him

### ISSUE THREAD

**Issue by bmxguy777** [wow-mania/Redemption#116]
Quest in Storm Peaks called you Can't Miss Him, in this quest you are told to go to Fjorn's Anvil and talk to an npc named Njormeld. When you find him he is targetable to attack but not to turn in the quest. Even when GM Paulikus came to check it out he was able to attack him.

**Comment by Rockshark** [comment]
So how do you get passed the "The Drakkensryd"?

**Comment by fvicaria** [comment]
#416 Keeping the new report.
