### ISSUE TITLE
[Quest] Fire at Will!

### ISSUE THREAD

**Issue by Naigio** [wow-mania/Redemption#116]
In Blade's Edge Mountain you recieve this quest to destroy the warp-gates with the fel cannons close by.
What happened when I took control of one was not quite what I was expecting, the Fel Cannon started to follow me around, like a pet would and none of the abilites did as they were intended, so the gauntlet (the  mobs spawning to attack me) never happens, and you're left unable to complete the quest.

**Comment by ThaydeGM** [comment]
Quest http://www.wow-mania.com/armory/?quest=10911requires the player to use http://www.wow-mania.com/armory/?item=31807 on a Fel Cannon to destroy http://www.wow-mania.com/armory/?npc=22504 and http://www.wow-mania.com/armory/?npc=22503. On using the Naturalized Ammunition the gauntlet that is supposed to attack the player doesn't happen, nor does the fel cannon destroy the warp-gates making the player unable to finish the quest.
