### ISSUE TITLE
[Dungeon] Oculus's Mage-Lord Urom

### ISSUE THREAD

**Issue by Ashamedlol** [wow-mania/Redemption#119]
His health keeps refreshing each time he teleports [BUG], and once he's in the middle he teleports to the empty air and falls causing him to refresh completely with whole damage evaded [BUG], he also teleports to targets instead of the middle sometimes [BUG], casts Empowered Arcane Explosion near players instead of air [BUG].

How it's supposed to be is that his health doesn't refresh on the teleports, and once he's in the middle he should be using the teleport ONLY when he's casting the Empowered Arcane Explosion at the air (he's flying midair and casting it) and returning to players.

**Comment by Ashamedlol** [comment]
To add on all this, he should NOT be interuptable.

**Comment by Kalasbyxan** [comment]
**Mage-Lord Urom** (http://www.wow-mania.com/armory/?npc=27655) uses **Teleport** (http://www.wow-mania.com/armory/?spell=51112) and stands in the middle of the Oculus while casting **Empowered Arcane Explosion** (http://www.wow-mania.com/armory/?spell=51110). When testing, he uses Teleport but instantly moves back to the aggro holder and uses Arcane Explosion there. Three times out of perhaps 10 times, Mage-Lord Uron stays in the middle and starts to cast Arcane Explosion but ends after a second and resets.

I did not experience an HP reset when teleporting (that I noticed).
