### ISSUE TITLE
[Quest] Weaken The Ramparts

### ISSUE THREAD

**Issue by wow-mania** [wow-mania/Redemption#12]
Bring Andre's Head to Security Chief Bilgewhizzle in Steamwheedle Port. You can go to where he is supposed to be and you see him right away, that is the beginning of the problem, he is not where he should be right from the start. There are 3 adds that are sitting by some logs a little further into the port area and he is supposed to be in the center of them. The other thing that is wrong is that you cannot harm him in anyway what so ever lol. Then again he doesn't harm you either.

**Comment by mariogotze** [comment]
Wrong description, anyways Weaken The Ramparts works fine.

**Comment by ChemicalSerenity** [comment]
Confirmed, ramparts works fine, completed Horde side ramparts quest twice yesterday.
