### ISSUE TITLE
[Dungeon] Pit of Saron's Cave Encounter (the Gauntlet)

### ISSUE THREAD

**Issue by Ashamedlol** [wow-mania/Redemption#120]
[What's supposed to happen] So once you're in the cave and you start fighting the two skeletons, the cave encounter or known as Gauntlet will start and Scourgelord Tyrannus will try to collapse the cave on you, there will be ice runes on the floor that indicate where a snowpack will be falling, if you get hit by this snowpack you will recieve damage and get knocked back. The black medaliation is immune to this snowpack falling. Currently there's no such thing as cave encounter inside this PoS.

As for Scourgelord Tyrannus, Rimefang should be showing a rune on the ground where he would be shooting an ice blast (before the impact by a slight time) and he should not be canceling the freeze-blast on a target although it's an animation cancel bug within the server's casting order. Scourgelord Tyrannus himself should be slowed when dragged into those ice blast grounds.

**Comment by Calebrimbor** [comment]
All is working fine now, thanks for the report!
