### ISSUE TITLE
[Quest] Territorial Trespass

### ISSUE THREAD

**Issue by Kalasbyxan** [wow-mania/Redemption#121]
The quest (http://www.wow-mania.com/armory/?quest=13051) require the player to place an item (http://www.wow-mania.com/armory/?item=42797) on a nest which will start an event where the dragon Veranus (http://www.wow-mania.com/armory/?npc=30461) appear.

The event seemed to not start, then it look 12 minutes for the dragon to spawn. The last two lines of Veranus speech played out and then the quest completed itself. When doing it myself I did not await the 12 minutes (reported by player Sheephappens) but monitored how no event took place.

**Comment by genasi** [comment]
I can confirm that it takes quite a while for the dragon to appear, not sure if its 12min but I did it saturday and waited around from I placed to egg about 5-10 mins, then I thought I would try and abandon and retake the quest so I flew up and saw the dragon coming in very slowly, like walking pace, from the area south of the nest and then Thorim jumped on the back and quest completed.

**Comment by GMLucetta** [comment]
This is still not working as intended. It takes between 5-12 minutes for the dragon to arrive.

**Comment by GMLucetta** [comment]
See also issue 247 

https://github.com/wow-mania/Redemption/issues/247

**Comment by GMLucetta** [comment]
https://github.com/wow-mania/Redemption/issues/247 is already dealing with this.
