### ISSUE TITLE
[QUEST] The swarm grows (part 3 of 3)

### ISSUE THREAD

**Issue by Burpone** [wow-mania/Redemption#121]
Kill 5 Silithid Searchers, 5 Silithid Hive Drones, and 5 Silithid Invaders and return to Moktar Krin in Thousand Needles.

NPC #4130 slain (5)
NPC #4133 slain (5)
NPC #4131 slain (5)

The bug is:   NPC #4131 (Silithid invaders) is JUST 1 !!! so you have to wait more than 1 hour for kill 5 of them.

**Comment by fvicaria** [comment]
Easy fix. I will do that for next release.
