### ISSUE TITLE
[item] X-53 Touring Rocket

### ISSUE THREAD

**Issue by Kalasbyxan** [wow-mania/Redemption#122]
The mount (http://www.wow-mania.com/armory/?item=54860) and spell (http://www.wow-mania.com/armory/?spell=75973) does not work in Azeroth for a player (Shamel) after have been working. Kalasbyxan and Kaukas attempted unlearning, re-adding and unlearnning, relearning.

**Comment by Ashamedlol** [comment]
It's back to working, thanks nonetheless :).
