### ISSUE TITLE
[MINOR][CLASS/paladin] Duplicate starting spell

### ISSUE THREAD

**Issue by oleberdal** [wow-mania/Redemption#122]
No impact on game play other than the feeling of playing a bug free game.

[Seal of Righteousness] is duplicated. They still do they same and seem to have the same stats. Slightly different description on one of them. Should be easy to remove (find the spell ids and remove the incorrect one from existing paladins, and change script(?) to not give the incorrect spell on newly created paladins).

**Comment by fvicaria** [comment]
Fixed
