### ISSUE TITLE
[World] Game mechanic: loot bugged

### ISSUE THREAD

**Issue by Orcozzio** [wow-mania/Redemption#123]
It may happen that you get no loot from a kill, but if it is skinnable you should still be able to skin it... The bugged loot (started maybe when the Summer event started) prevent you from looting your kills pretty often... You get experience, reputation, killing counts (if a quest needs a tot of mob killed), but no loot... Sadly this bugged mechanic affect also the locked boxes you open with keys (if blacksmith)... you can find nothing inside an opened box... and even the boxes that comes from pick-pocket...

I cannot explain how much is annoying this bug...

**Comment by uga** [comment]
The bug happens all over the place.
It seems NOT to happen when the mob is supposed to drop a quest item.
But all mobs that are not supposed to drop a quest item, very often (like 30-50% of the times) they die without alloing for looting AND (if skinnable) for skinning. 
The impossibility to skin is 100% revealing the bug's existance: rather then missing loot I would call it mis-assigned loot. The dead mob behaves as if it was tagged+killed by someone else (while I was the playing alone, of course).

This bug's impact on regular game playability is dramatic. Please assign high priority to its correction.

**Comment by TheSale** [comment]
+1 here
same stuff happening to me, just I would like to add:
-Looting quest objects (looting herbs, boxes, materials, or anything you have to gather from)  it cast your opening or gathering, but you receive nothing, and it still stays there like gatherable or collectable but if you click to collect again it do not cast and it says its unable to collect

-Gathering herbs and mines, same thing as with quest objects, just it happen to ore disapear after its empty, or its there still but give nothing and you cant mine it again, same for herbs

- PROSPECTING I think this is most important, yesterday it occur to me 2 times during prospecting  2 stacks of fell iron ores you click to prospect 5 ores and it open empty looting box and consume 5 ores

- loot from dungeons, you win need or greed, but you dont receive item, stay in body and after rolling is over and it says who is winner, item can be picked up by anyone

- looting corpses as they said, most of the time it occur that its not lootable, and sometimes it is lootable but it is empty
this is most annoying in dungeon it happen to me that I dont get any lootable corpses after we kill like 50 mobs, people looting frostwave cloth, thrash armors and weapons and gold, but I dont loot anything, and when I get to loot most often it occur its empty loot.

this is annoying and lead to bad experience of the game, when you dont receive loot when you supposed to, although I believe there is much more urgent matter that mater on holding people on server like dungeon bugs, raid bugs, server crushes, disconnects, maniac points bug

**Comment by genasi** [comment]
I havent seen the bug in the valley near Dun Niffelem, I have been skinning jormungar and mammoths there for the last 3 days with no issue.
I have seen the bug happen in a Ahn'ket the last kingdom run yesterday, we finished it with the only loot coming from the bosses.
I also did azjol-nerub, where practically all the mobs can be skinned, but it wasnt possible in this run.
Both runs were using RDF.
I logged a different toon to get emblems on that and got azjol-nerub again, and this time the mobs could be looted and skinned.

**Comment by Kalasbyxan** [comment]
Confirmed:
- Gathering bjects disappear after cast bar finishes without loot
- Mobs that should be skinnable sometimes aren't skinnable
- Empty loot tables on corpses

**Comment by huqboss** [comment]
Very common with herbs and mining deposites - after gathering/mining there is no loot window and when you try to do it again there is a communicate: "This object was already looted"

**Comment by Emcitementz** [comment]
I'll look into that.

**Comment by iggapres** [comment]
I don't know if it's the same bug, but this reminds me this problem:
When you're at the limit of loot distance of the thing you have to loot, the game lets you loot (progress bar, animation of your char), but nothing is looted and the object looted is "locked" for a few time.

 On chests, for example, you have to wait a few seconds/minutes for a reset, then coming closer to it makes the loot work again.

Also happens in fishing when the bobble is thrown too far away.

**Comment by wow-mania** [comment]
Need a reproducible case with steps. Until then not much we can do.
