### ISSUE TITLE
[MINOR][GAME] Resolution, mouse pointer

### ISSUE THREAD

**Issue by oleberdal** [wow-mania/Redemption#123]
Mouse pointer icon doesn't move from the login screen and throughout the game. I can figure out where the mouse pointer is by noticing when other icons are being hovered (by the seemingly invisible mouse pointer).

Downloaded game using torrent. Works for my younger brother (different computer, same wow-folder and files).

Tried:
- deleting cache
- unchecked "Read Only" for all files, folders and sub-folders
- plug in a mouse
- run as administrator
- using younger brothers files and folders (copy from his computer)
- restarting computer

Bypass:
- I found out that the problem isn't present when using windowed mode. Making me think that it's a problem related to the resolution and system compatibility. (works with windowed, but not full screen)

EDIT: It also works in full screen mode if you disable "Hardware Cursor", but that makes a small lag/delay when moving the mouse pointer.

PS: I don't know if this is easy to fix or hard to fix, but I guess it's low priority as it has an easy workaround, and probably only affects a very few amount of people. But I will assist to fix this bug if there is anything I can do, for instance inform about my system properties!

**Comment by Upperfoot** [comment]
I don't believe this is as such an issue with WoW-Mania, but more of an issue of WoW itself, Hardware Cursor was put in game to fix your issue as a workaround (it's not perfect). But I would suggest updating your Graphics Drivers from the below links, choosing one depending on your computers graphics device.

ATI: http://support.amd.com/en-us/download
Nvidia: http://www.nvidia.co.uk/Download/index.aspx?lang=en-uk
Intel: https://downloadcenter.intel.com/

Hopefully that will resolve your problem.

Thanks!

**Comment by fvicaria** [comment]
Yep this is a client side issue.
