### ISSUE TITLE
[Event] Midsummer's Darnassus and Ironforge Bonfire for Horde

### ISSUE THREAD

**Issue by Ashamedlol** [wow-mania/Redemption#125]
The bonfire of Darnassus is clickable but it does not give the flame darnassus quest, player Rosevyn is struggling with this and I can confirm that I just tried it on a horde toon and it didn't work.

Went to test Ironforge as well, it did not work too.

**Comment by Kalasbyxan** [comment]
Will renew troubleshooting once Midsummer event is active.
