### ISSUE TITLE
[Quest] [The Flesh Giant Champion](Part 3 of 3)

### ISSUE THREAD

**Issue by agolgeli** [wow-mania/Redemption#126]
It seems bugged, you kill the mob, but objective does not get completed.

**Comment by Rockshark** [comment]
This was reported a few days ago. Me too cant completed the quest. It seem that the 4 or 5 NPC are doing more damage than you so you cant get the credit for the kill. It the same type of bug with The Air Stands Still.

**Comment by fvicaria** [comment]
This is a general issue. Similar to "Air Stands Still" if you don't do 51% of the damage you do not get credit.
Get someone to do the quest with you.
