### ISSUE TITLE
[Raid] Naxxramas's Post-Quarter Teleporters

### ISSUE THREAD

**Issue by Ashamedlol** [wow-mania/Redemption#127]
The teleporters at end of each quarter only work for one person, they should be for the whole group.

**Comment by wow-mania** [comment]
Should be fixed. Please retest.

**Comment by Ashamedlol** [comment]
Re-tested, does still not work.

**Comment by Kalasbyxan** [comment]
Plague Portal works for everyone using it.
Military Portal, Construct Portal and Arachnid Portal does not work apart from for first player.
