### ISSUE TITLE
[Dungeon] Utgarde Keep - Ingvar bugged

### ISSUE THREAD

**Issue by genasi** [wow-mania/Redemption#128]
The last boss in Utgarde Keep, Ingvar, is bugged. He goes to phase 2 just fine, he gets back up and the fight continues. When Ingvar is killed 2nd time, he respawns alive, he is thus not lootable even though the dungeon is finished, achievement (if 1st time) and RDF rewards are awarded.

**Comment by wow-mania** [comment]
Fixed for Wednesday.
