### ISSUE TITLE
[Quest] Hah... You're Not So Big Now!

### ISSUE THREAD

**Issue by Naigio** [wow-mania/Redemption#129]
The quest given to you by Crafty Wobblesprocket in Boraen Tundra is a bit indecisive about giving you the results.
I apply the Quest Item to the required mob several times, and I even see the debuff on the marked target, yet it won't yield me a point towards completing the quest.

**Comment by Orcozzio** [comment]
I managed to finish that quest, but it was long and tricky... It was easier for me playing on hunter... while my pet got aggro on the mobs I applied the debuff several time to find "the right one"... I mean... the quest should count the times the mob get the debuff, but actually it counts most of the times you turn the mob into a gnome...
So... the quest is bugged, yes... but if you have lot of time to waste you can complete it (I will skip that quest on my alts)

**Comment by Calebrimbor** [comment]
Issue added to the BugTracker for testing. Thank you for your report. 
@ Testers: Please add all details such as links etc.

**Comment by Calebrimbor** [comment]
Quest is working fine. Removed the issue from the BugTracker.
