### ISSUE TITLE
[Quest] On Ruby Wings

### ISSUE THREAD

**Issue by mariogotze** [wow-mania/Redemption#13]
ID#12498

In quest On ruby wings, Tiassi the Lighting Bringer should ride Grand Necrolord Antiok who wears quest item Scythe of Antiok but hes not here

**Comment by Valtheria** [comment]
He spawns after you kill Tiassi. However, you have to dismount from the provided drake to kill him, which kills you even if you land first. At least, it kills me every time I dismount.
