### ISSUE TITLE
[Raid] Trial of the Crusade's Anub'arak

### ISSUE THREAD

**Issue by Ashamedlol** [wow-mania/Redemption#132]
Spike mechanic is bugged, if you're a paladin and you divine shield it, the spike will get stuck in place.
Also happens when a player dies by spike, the spikes get stuck at their place.

It should be following a target and knocking everyone that's in path of the spikes while damaging with some damage that ignores armor totally (as well as the main person himself if it hits him), and focus should switch if target is dead or left aggro (divine shielded if paladin, hand of protection on raid member if paladin in RG).

**Comment by Calebrimbor** [comment]
Works now.
