### ISSUE TITLE
[Dungeon] Gal'darah (Heroic)

### ISSUE THREAD

**Issue by Ashamedlol** [wow-mania/Redemption#134]
He sits there channeling his purple beam at the statue and does nothing, he's supposed to fight you and summon a rhino that deals good damage randomly to a random group member and transform into that rhino thingy.

**Comment by Calebrimbor** [comment]
Confirmed!

http://www.wow-mania.com/armory/?npc=29306

Should do abilities displayed on this url: http://www.wowhead.com/npc=29306/galdarah#abilities:mode=heroic

He does nothing, just sitting there. This is only on Heroic mode, normal seems fine.

**Comment by wow-mania** [comment]
Fixed for next Wednesday. Please confirm.
