### ISSUE TITLE
[Spell] Hammer of Justice does not interrupt spellcast when mob is immune to stuns

### ISSUE THREAD

**Issue by mourasman** [wow-mania/Redemption#135]
Currently, if you use Hammer of Justice on a mob that's immune to stuns (boss, for example) and he's casting an interruptable spell, HoJ doesn't interrupt it.

This was supposed to happen, although it's only slightly implied in the spell's tooltip.

This can be very disruptive on certain fights/achievements.

**Comment by fvicaria** [comment]
Should be fixed for next release.
