### ISSUE TITLE
[Quest] A suitable disguise

### ISSUE THREAD

**Issue by Taladric** [wow-mania/Redemption#136]
Goblin doesn't show up to talk to, therefore I cannot begin quest.
![wowscrnshot_070516_221314](https://cloud.githubusercontent.com/assets/18010035/16608154/f0066210-42fd-11e6-8bda-6d2474bdb22b.jpg)

**Comment by Dierdrah** [comment]
There's still an issue with this quest: while the little gnome does appear, you get stuck into endlessly throwing clothes at the elemental, without having the quest actually progress. I spent about 5 minutes throwing laundry at it, but then I got tired and realized that it was a bug.

**Comment by Kalasbyxan** [comment]
http://www.wow-mania.com/armory/?quest=24556

Like mentioned above, washing event is neverending, never completing offering the reward needed for the quest.
