### ISSUE TITLE
[Zone] Wintergarde Mausoleum

### ISSUE THREAD

**Issue by Naigio** [wow-mania/Redemption#137]
There is just way too many mobs down in the Mausoleum, several mobs spawning on top of each other, breeding like rabbits.
With the increased spawnrate it makes it even worse, please fix.

**Comment by Calebrimbor** [comment]
Confirmed!

These NPC's are quite overcrowded, although it's still doable:
http://www.wow-mania.com/armory/?npc=27797
http://www.wow-mania.com/armory/?npc=27800
http://www.wow-mania.com/armory/?npc=27824
http://www.wow-mania.com/armory/?npc=27823
