### ISSUE TITLE
[QUEST] Divination: Gorefiend's Truncheon

### ISSUE THREAD

**Issue by Kalasbyxan** [wow-mania/Redemption#137]
Doesn't give out the required spectacles and it doesn't tell you if that you can get a pair from:
http://www.wowhead.com/npc=21774 (Alliance)
 http://www.wowhead.com/npc=21772 (Horde)

Maybe they just don't spawn?

Don't know if its a bug or not but i didn't get any spectacles when i took the quest and that left me confused of what to do.

Can't seem to be able to buy anything from those but ill just leave this here if its buggy

**Comment by fvicaria** [comment]
I got the spectacles with both alliance and horde
