### ISSUE TITLE
Multiple issues.

### ISSUE THREAD

**Issue by lordslag** [wow-mania/Redemption#138]
The Orbs of Translocation on the Isle of Quel"Danas to not function.

The drop rate on Boiling Blood in Hellfire is ABSURDLY low.  It is impossible to understate just how unreasonably low it truly is.

The Terrorfiends in the quest In Need of Felblood have a Felblood drop rate of at least 1/27.  No one is THAT unlucky, not even me. 

PVP flag does not toggle off when 5 minute timer expires. Must relog.

The quest Magic of the Arrakoa has a drop rate of less than 0/14, and that's not counting all the ones I destroyed before I started counting.

In the quest Natural Remedies, the Seed of Revitalization doesn't cause Fallen Sky Ridge to 
be revitalized, so the quest can't be completed.  It also does not play the story animation,
but it DOES summon the special monster you must kill afterwards.

Parts for the Job quest has a Shoveltusk ligament drop rate of less than 0/20...and that's not counting all the ones I killed before I started counting.

Pursuit of Justice does not grant mounted movement bonus.  Tested with other player.

**Comment by fvicaria** [comment]
Isues will be dealt individually. In future log them one by one so I do have to break them up myself.
