### ISSUE TITLE
Hunter's pet talent: Wild Hunt

### ISSUE THREAD

**Issue by Orcozzio** [wow-mania/Redemption#139]
Literally the talent does nothing... it doesn't scale pet stamina or attack power... no matter the rank.

**Comment by wow-mania** [comment]
Please be more specific. When did it start?

**Comment by Orcozzio** [comment]
Don't know when... I didn't tested it when I was levelling even if I saw nothing was changing assigning talents points to any pet... In the beginning I tought it was just a visual bug... something needing a UIrelod or relogging... Almost at level 80 I noticed that my pets was loosing aggro too often and Recount (an addon) showed me their pretty low dps... So when I read on forum that another hunter found that ability broken I respecced to test it on the target dummy... Checking the pet stats as they show in pet details and letting pet attack the dummy... Spending talent points into Wild Hunt doesn't change pet stats as showed in pet details and doesn't change pet dps as showed by Recount... so it is not just a visual bug... pets doesn't receive any benefit from Wild Hunt.

**Comment by Orcozzio** [comment]
...there are other hunter talents in the BM tree that looks like not working, but I'm waiting tests from other hunters before opening a new issue here

**Comment by wow-mania** [comment]
This should be fixed today. Update coming.
