### ISSUE TITLE
[QUEST] Escape From Silverbrook

### ISSUE THREAD

**Issue by Mayhem178** [wow-mania/Redemption#140]
This Grizzly Hills quest doesn't appear to be able to be completed.  When you free the prisoner from his cage and get on the horse with him, he rides around randomly, occasionally falling through the terrain.  He never makes it to Silverbrook to complete the quest.

Also, if you dismount the horse, he begins attacking you, even though he's still marked as a friendly unit.

**Comment by fvicaria** [comment]
I improved the script a bit. Please reopen if still not working for you.

**Comment by Malthu** [comment]
I've just experienced what the OP described ingame.
