### ISSUE TITLE
Random Dungeon Finder: endless solo in qeue

### ISSUE THREAD

**Issue by TheSale** [wow-mania/Redemption#140]
I noticed 2 bugs
first I was on questing and qeued in meanwhile after aprox 1 and a half hour I checked and saw that timer show that I am in queue under a minute  and that I am only one in queue 

and second I join the queue but even I select my rolle it dos not assign me any roll of members and it stay empty like that and timer is also under a minute

I think this is red flag and have to look over ASAP 

only solution to enter in rdf to make your own 5 man group and go like that, since I am new on server and dont know people to play with, and people in world chat just dont care, its bad experience for me

update:
now timer in queue is ticking but still after 15 min as tank/dps I am still only one in queue

**Comment by Bravopatriot** [comment]
wow-mania client and launcher
windows 10

I would also like to report i deleted old patches from data and gbdata. same thing happened. waited for over an hour till i gave up. tried on multi toons with different roles and same result. have attached screen shots. whatever got fixed for arena has disabled the RDF tool.

![wowscrnshot_070616_095405](https://cloud.githubusercontent.com/assets/19984295/16629024/d1c2a17a-4379-11e6-9639-507ead6d3833.jpg)
![wowscrnshot_070616_100203](https://cloud.githubusercontent.com/assets/19984295/16629022/d1c012ac-4379-11e6-87df-3b14d7bc99ca.jpg)
![wowscrnshot_070616_100820](https://cloud.githubusercontent.com/assets/19984295/16629023/d1c02d96-4379-11e6-82af-bd4d73c8ad0a.jpg)

**Comment by wow-mania** [comment]
Cannot reproduce people are queuing fine.

**Comment by Bravopatriot** [comment]
still not que solo, if im in a 5 man group its fine. alot of people online now are having the same issue sir.
