### ISSUE TITLE
(Quest) Tempering the Blade

### ISSUE THREAD

**Issue by Taladric** [wow-mania/Redemption#141]
So I did forge of souls and threw the sword in... nothing happened.  Didn't get credit and I lost the Item.
![wowscrnshot_070616_175753](https://cloud.githubusercontent.com/assets/18010035/16639437/8a00c83c-43a4-11e6-846d-337214f7e1da.jpg)
![wowscrnshot_070616_175758](https://cloud.githubusercontent.com/assets/18010035/16639438/8a0421c6-43a4-11e6-9121-f148ec59b551.jpg)
![wowscrnshot_070616_180228](https://cloud.githubusercontent.com/assets/18010035/16639439/8a044b9c-43a4-11e6-9de5-d27cfc123093.jpg)

**Comment by Calebrimbor** [comment]
Stand under the bucket of Molten Iron and the use the Quest Item
