### ISSUE TITLE
[QUEST] Mystery of the Infinite

### ISSUE THREAD

**Issue by Mayhem178** [wow-mania/Redemption#142]
When you place the hourglass in the Bronze Dragonshrine, Future You appears and the event occurs as expected.  However, once the event is complete, credit for completing the quest is not given.

"Mystery of the Infinite, Redux" (the follow-up quest for this) is also confirmed non-functional (https://github.com/wow-mania/Redemption/issues/19).

**Comment by fvicaria** [comment]
Can someone confirm this one. The first quest was working fine. The second part not scripted.

**Comment by fvicaria** [comment]
Duplicate #19 
The first part is OK the sequel is not scripted yet.
