### ISSUE TITLE
[NPC] Neltharaku

### ISSUE THREAD

**Issue by DasGroove** [wow-mania/Redemption#142]
http://www.wow-mania.com/armory/?npc=21657

I've sat and flown through his flight path for over an hour and had him randomly appear behind my character once. I would like to work towards a netherwing drake but if I can't consistently come in contact with Neltharaku, I don't believe I'll be able to. 
Windows 10
Wow-mania client/launcher
http://www.wowhead.com/npc=21657/neltharaku

**Comment by Calebrimbor** [comment]
Confirmed. I've managed to reproduce. Issue is labeled as 'Confirmed' on the BugTracker.

**Comment by wow-mania** [comment]
NPC is there and can be stopped and dialog is fine.
![image](https://cloud.githubusercontent.com/assets/12248683/19758984/b8b3200e-9c22-11e6-96fe-407e176daaee.png)
