### ISSUE TITLE
[Quest] Fate, Up Against Your Will

### ISSUE THREAD

**Issue by Naigio** [wow-mania/Redemption#143]
So one of the best quest chains in Northrend is not working as intended.
After picking up Fordragon's shield and running off to Stormwind, I recieve this quest to go to Org, but I can't because Jaina ins't next to Varian in SW, to teleport me there.
Nor will she aid me from Theramore. Please fix this.

Also I want to point out that when delivering the "Return to Angrathar" the cinematic didn't start and I had to actually run down there to continue the quest, instead of being teleported down there like you normally would after the cinematic.

**Comment by Calebrimbor** [comment]
Issue added to the BugTracker for testing. Thank you for your report. 
@ Testers: Please add all details such as links etc.

**Comment by Calebrimbor** [comment]
Labeled with 'Priority' since this quest is frequently reported.

**Comment by Calebrimbor** [comment]
http://www.wow-mania.com/armory/?quest=13369

Confirmed, Jaina Proudmoore (No known ID) should be standing next to King Varian's throne, you should be able to select the option to start the teleport.
