### ISSUE TITLE
[Quest] The Shining Light

### ISSUE THREAD

**Issue by temjiu** [wow-mania/Redemption#144]
Issues are actually in 2 separate things:

1) The zombies that are only supposed to be on the bottom floor are actually roaming both floors, making doing any of the quests in the Utgarde Catacombs very difficult. I ended up bypassing this by grabbing this quest, then using the shield to run around to get the articles to complete the other quest.

2) Issue with the light shield: it has a timer set, and it should last the entire timer. However, once you grab the sacred artifact, the shield disappears! Leaving you to have to run through the hordes of undead. Glad my character was a tank...I'd hate to see how a mage survives that amount of mobs!

I tried logging, dropping and reacquiring quest, nothing changed.

**Comment by GMSunShield** [comment]
http://www.wow-mania.com/armory/?quest=11288

Players talk to Ares the Oathbound ( http://www.wow-mania.com/armory/?npc=24189 ) to start this quest.
NPC should put Shining Light Aura on player ( http://www.wow-mania.com/armory/?spell=43202 )
    ^Issue^ Players do not get this aura.

Players then have to pick up item Sacred Artifact ( http://www.wow-mania.com/armory/?item=33485 )
to bring back to Ares the Oathbound. The aura Shining Light Should stay on  the player till the quest is handed in.

Note1: >Quest item: Sacred Artifact ( http://www.wow-mania.com/armory/?item=33485 ) Can be picked up<
Note2: Undead do spawn up top  close to NPC: Ares the Oathbound
    ^Issue^ Undead should only spawn down by Sacred Artifact
