### ISSUE TITLE
[Quest] Into the World of Spirits

### ISSUE THREAD

**Issue by temjiu** [wow-mania/Redemption#145]
picked up at Valgarde. Quest item cannot be found (Reagent Pouch). it's not in the normal place it is on retail, and is nowhere in the area. 

relogged, abandoned quest and picked it up again. Spent a good 10m swimming through the area using a /target macro to make sure it wasn't just hiding in some larger object. Nada.

**Comment by genasi** [comment]
I have needed to find this pouch twice on redemption and both times they were on the wreckage in the shallow part to the north in the bay. It is slightly bugged however since the pouch is supposed to have several spawn locations.

**Comment by temjiu** [comment]
yeah, I noticed the different spawn locations on various videos I watched. Unfortunately, both had no target-able items. Even using a macro, swimming around the whole area (including both ships..but I scanned the shores and walls to just to be sure) i found nothing.

**Comment by Calebrimbor** [comment]
Confirmed as bugged, it's on the to fix list.
