### ISSUE TITLE
Day #3 of RDF being unusable solo

### ISSUE THREAD

**Issue by Bravopatriot** [wow-mania/Redemption#146]
Wow-mania client and launcher
Windows 10

Description of problem:
When the server came back up from maintenance the rdf feature was bugged if qued solo or in a group less that 5. the time clock would not spawn nor would it show you what roll you are assigned. have tested this every day since Wednesday and still broken. being part of a small guild or leveling this makes things not impossible, as you can still que as a group of 5, but a hassle. I really enjoy playing on this server because this is where my friends are. Ive always had good responses with the GM and staff but being unable to que while i farm/quest is getting to be more than annoying. 

I have tested to see if queing for specific heroics would help, but it didnt. tried random dungeon and no que. the entire thing is bugged unless you are in a full group. i did notice that on one other thread someone started that you could not find any problems with rdf. however everyone in world chat says differently. GMs may be able to verify claims since i didnt think to take screen shots at that time. 

I have deleted all patches and reinstalled, with this not fixing the problem. Before maintenance happened i had no problem queing. now with arena coming back with restart unable to que for PVE events on a PVE server.

Thank you for your time. have attached screen shots that have timestamps on them to show the timer and que bug.

![wowscrnshot_070616_095405](https://cloud.githubusercontent.com/assets/19984295/16690465/bbe100b6-44ed-11e6-8845-79efb0adc0ba.jpg)
![wowscrnshot_070616_100203](https://cloud.githubusercontent.com/assets/19984295/16690466/bbe299c6-44ed-11e6-87c2-fe34f4d7cb5e.jpg)
![wowscrnshot_070616_100820](https://cloud.githubusercontent.com/assets/19984295/16690464/bbe02cd6-44ed-11e6-8a4c-b23fcef38d34.jpg)
![wowscrnshot_070616_192919](https://cloud.githubusercontent.com/assets/19984295/16690482/ce6b15d2-44ed-11e6-99eb-45369fc1b2fd.jpg)
![wowscrnshot_070716_093947](https://cloud.githubusercontent.com/assets/19984295/16690483/ce6bce8c-44ed-11e6-9e06-2a6272fb4d0e.jpg)

**Comment by silverbane27** [comment]
Yup everyone is complaining in global chat about not being able to use the dungeon finder

**Comment by Calebrimbor** [comment]
Fixed a while ago
