### ISSUE TITLE
[NPC] Matis the Cruel

### ISSUE THREAD

**Issue by RefractionIX** [wow-mania/Redemption#15]
http://www.wowhead.com/npc=17664/matis-the-cruel

I encountered him walking on his set path and challenged him. Shortly after I found myself being hit by a large amount of magic numbers and died in five seconds. I rezzed, went after him again, and attacked him again and was able to follow him, taking no damage, and beat him in melee. Note, before I closed completely, I took a small chunk of magic damage before it stopped when I got into melee. 

Steps to reproduce, I think would just be to attack him at range outside of melee range to see the magic damage numbers. If that doesn't occur for anyone else but me, I'm not entirely sure what to think.

Account name: Refraction IX
Character Name: Melifiss, lvl 24 Draenei Protection Paladin.

I am using WowMania client on latest patch, on Windows 7 Ultimate. 

Note: this is the first issue that I've logged, please be kind to me if I don't have it perfect.

**Comment by wow-mania** [comment]
Works fine in Redemption. Nothing to do here.

**Comment by Calebrimbor** [comment]
It wasn't on the BugTracker, so no update needed
