### ISSUE TITLE
[Quest] Escape Through Force

### ISSUE THREAD

**Issue by mariogotze** [wow-mania/Redemption#15]
ID#994

The quest "Escape Through Force" which is a choise of two quests, the other one is called "Escape Through Stealth".
You get to choose between those two after "The Lost Master" quest, i chose the Force one and I had to follow Volcor until we reached the road, once we hit the road he sat down and disappeared while saying "Speak with Terenthis in Auberdine for your side of the story etc. etc.".
Once i got to Auberdine i couldnt speak with Terenthis nor did i find Volcor anywhere near.

**Comment by wow-mania** [comment]
Fixed.
