### ISSUE TITLE
[Class] Death Knight - Dancing Rune Weapon

### ISSUE THREAD

**Issue by ChemicalSerenity** [wow-mania/Redemption#150]
(per Deathmort) Doesn't seem to work properly. When I summon the sword, it appears, but does absolutely nothing. Tested it 10 times, never attacks or moves.

**Comment by fvicaria** [comment]
This is a problem in TC also. I can come up with hacks but a proper fix will need more data which is not available at the moment.

**Comment by fvicaria** [comment]
fixed on next release.
