### ISSUE TITLE
[Quest] The Art of Being a Water Terror

### ISSUE THREAD

**Issue by Calebrimbor** [wow-mania/Redemption#151]
http://www.wow-mania.com/armory/?quest=13091

For this quest you need to kill 10 Jotunheim Vrykul, while possessing a Water Terror(http://www.wow-mania.com/armory/?npc=30642). These Water Terrors are held up in a cage by the water. You can unlock them by pressing on the gate. Once unlocked, the Water Terror will accompany you.

No Water Terror accompanies you when opening the gate.

**Comment by Calebrimbor** [comment]
Labeled with 'Priority' since this quest is frequently reported.

**Comment by Emcitementz** [comment]
This is working properly on dev.
