### ISSUE TITLE
[Quest] The Iron Colossus

### ISSUE THREAD

**Issue by Calebrimbor** [wow-mania/Redemption#152]
http://www.wow-mania.com/armory/?quest=13007

For this quest you'll need to kill Iron Colossus(http://www.wow-mania.com/armory/?npc=30300) making use of a Tamed Jormungar. You can find him north of the Iron Colossus. To time this Jormungar you'll need to click on the orb next to it.

The orb to control a Jormungar does not work. A error appears: Need to be closer to interact, while standing next to it.

**Comment by wow-mania** [comment]
Should be fixed on next update or crash. :)
