### ISSUE TITLE
[Quest] Rise, Obsidion!

### ISSUE THREAD

**Issue by Calebrimbor** [wow-mania/Redemption#154]
http://www.wow-mania.com/armory/?quest=3566

For this quest you'll have to go to The Slag Pit. In the room where Obsidion(http://www.wow-mania.com/armory/?npc=8400). In the same room you'll find a altar. Click on that and Lathoric the Black(http://www.wow-mania.com/armory/?npc=8391) will spawn and start a speech. Then both Obsidion and Lathoric become hostile. Kill them and loot the 2 quest items Head of Lathoric the Black and Heart of Obsidion.

Lathoric the Black despawns after the speech. Obsidion can be killed.

**Comment by Kalasbyxan** [comment]
Priority tag from being broken still and old report.
