### ISSUE TITLE
[Raid] Karazhan - Opera Event

### ISSUE THREAD

**Issue by Naigio** [wow-mania/Redemption#155]
The boss encounter doesn't work as intended, never starts after the announcer is done.

**Comment by Readerlady** [comment]
To piggyback on this issue. Romeo and Juliette encounter starts but does not complete. First attempt a few weeks ago was also the Red Riding Hood event. Grandmother would not start the event. You could talk to her but she had no option to begin the fight. She did not become attackable.

**Comment by Kalasbyxan** [comment]
Attempt 1: Rumelo & Julianne. Julianne spawns, does not attack when attacked and regenerate health. Despawns after a while. 

Attempt 2: Oz. Dorothee, Strawman, Roar and Tinhead spawns and the curtain falls, rendering them to be unattackable. 

Attempt 3: Grandmother spawns but when talking to her, all she has to say is "Greetings, Kalasbyxan."
