### ISSUE TITLE
More Multiple Issues

### ISSUE THREAD

**Issue by lordslag** [wow-mania/Redemption#156]
[If He Cannot Be Turned] is bugged.  When you kill General Lightsbane you do not get credit
for the kill.  This quest is vital to the activation of the Shadow Vault area and dailies.

[The Last Line of Defense] is bugged in such a manner that the cannons cannot fire outide of a
very small invisible shell.  No attackers or dragons can be killed.

[The Grand Melee] does not grant XP, or Reputation when completed, even though it displays
that it does.

[A Blade Fit for a Champion] does not grant XP, or Reputation when completed, even though it displays
that it does.

[A Valiant's Field Training] does not grant XP, or Reputation when completed, even though it displays
that it does.

[At the Enemy's Gates] does not grant XP, or Reputation when completed, even though it displays
that it does.

[The Valiant's Challenge] does not allow you to attack or damage the challenger in any way.

[Among the Champions] Does not grant Marks of the Champion when defeating Champions in the
Ring of Champions.

**Comment by fvicaria** [comment]
https://github.com/wow-mania/Redemption/wiki/How-to-Log-a-Bug

Most of them have been reported.
