### ISSUE TITLE
[Quest] Zero Tolerance

### ISSUE THREAD

**Issue by Nogrial** [wow-mania/Redemption#157]
Drakuru gives you Scepter or Empowerment which make an undead troll stronger and now your minion. The minion starts off in passive mode. He also doesn't attack anything. he only follows you. Which results in not being able to solo kill Darmuk. 

Since this quest can't be completed, you can't move any further on [Quest] Hazardous Materials

**Comment by Nogrial** [comment]
Temporary solution, is just grouping with people and killing Darmuk.

**Comment by Calebrimbor** [comment]
Issue added on the BugTracker for testing. Thank you for your report. 
@ Testers: Please add all details such as links etc.

**Comment by Calebrimbor** [comment]
http://www.wow-mania.com/armory/?quest=12686

It's confirmed. The Hand of Drakuru(http://www.wow-mania.com/armory/?npc=28805) can't attack Darmuk(http://www.wow-mania.com/armory/?npc=28793) since it's a 'Invalid Target'.
