### ISSUE TITLE
Quest: "Prove Your Hatred" Level 50 Paladin Quest (Horde)

### ISSUE THREAD

**Issue by Arthao** [wow-mania/Redemption#159]
The quest "Prove Your Hatred" has you collecting "Minion Scourge Stones" from lesser undeads in the Western Plaguelands. However they do not seem to drop.

**Comment by fvicaria** [comment]
There are a whole list of creatures that drop this item. Most set to 50%, that is to say you get 1 every two kills on average.

http://www.wowhead.com/item=12840/minions-scourgestone
