### ISSUE TITLE
[Skill] Sacrifice on Voidwalker

### ISSUE THREAD

**Issue by mariogotze** [wow-mania/Redemption#16]
Bug - "Sacrifice" skill on Voidwalker pets creates protective bubble but does not actually sacrifice the voidwalker.

**Comment by wow-mania** [comment]
Seems to work fine. If problem re-appears please call me in-game and show me.

**Comment by ChemicalSerenity** [comment]
Confirmed. Not proud of it, but I've used this bug to save my bacon on a couple of occasions. It's been a week or so since I last played my loc so if you've fiddled with things in the last week or so this may no longer be valid, otherwise I can confirm this behaviour.
