### ISSUE TITLE
The Light Of Dawn (Death Knight starter quest line)

### ISSUE THREAD

**Issue by RaptorSB** [wow-mania/Redemption#16]
Seems the battle is bugged out. No NPCs to interact with and no way to gain completion of the quest and continue on with a Death Knight.

**Comment by Oriden** [comment]
Speak to Mograine, it should work

**Comment by Calebrimbor** [comment]
Although it's set as confirmed a full report is missing

**Comment by wow-mania** [comment]
Please test it as I have not seen it happen in a long time.

**Comment by Calebrimbor** [comment]
Tested and it's working fine. I think players did the quest when a battle already has begun, or didn't had the patience to watch the whole lore, which takes a long time. Removed the issue from the BugTracker since it wasn't bugged.
