### ISSUE TITLE
[Tailoring] Deathchill Cloak, Wispcloak

### ISSUE THREAD

**Issue by Calebrimbor** [wow-mania/Redemption#160]
NPC Charles Worth(http://www.wow-mania.com/armory/?npc=28699) teaches you the patterns Deathchill Cloak(http://www.wow-mania.com/armory/?item=42190) once earned the achievement: Loremaster of Northrend(http://www.wow-mania.com/armory/?achievement=41), and Wispcloak(http://www.wow-mania.com/armory/?item=42189) once earned the achievement: Northrend Dungeonmaster(http://www.wow-mania.com/armory/?achievement=1288)

The requirements for both patterns are mixed up, so for Deathchill Cloak you'll need the achievement: Northrend Dungeonmaster, and for Wispcloak you'll need the achievement: Loremaster of Northrend.

**Comment by Emcitementz** [comment]
Seems like retail comments don't agree with what you're saying. It is not mixed up.
