### ISSUE TITLE
Blackrock Depths Issues: The Grim Guzzler

### ISSUE THREAD

**Issue by Daethalion** [wow-mania/Redemption#160]
There is a bug in the Blackrock Depths instance that causes anyone entering the Grim Guzzler to immediately come under attack from an unknown source. The attacks put a stacking debuff on players and will generally kill them within 2-3 shots, and cannot be avoided, however it appears that this attack will not reoccur after the player has been killed and returned.

Another issue is the fact that Ribbly Screwspigot does not spawn and cannot be fought for completion of his quest.

**Comment by fvicaria** [comment]
Fixed both issues.
