### ISSUE TITLE
Faction change

### ISSUE THREAD

**Issue by antonius123** [wow-mania/Redemption#161]
Hi, I've done a faction change and all the mounts and reputation got mixed up. I am now a night elf and I kept a great gray kodo. First time I did it, my night elf turning into a tauren, my night elf mounts transformed into skeletal horses and I had reputation with Undercity instead of Thunder Bluff. The faction/race change thing seems to be a bit hazardous.

Thanks.

**Comment by fvicaria** [comment]
Call me in game please so we can try so sort out.
