### ISSUE TITLE
[Quest] It Goes to 11...

### ISSUE THREAD

**Issue by temjiu** [wow-mania/Redemption#162]
6th quest in a series that starts with "The Path to Payback". no matter what I do, I cannot get the Harpoon to work. standing on it, near it, or different locations around it when I use the Control mechanism does nothing. trying to use the level nearby it keeps telling me that It "Requires Icehammer's Harpoon Controller" and I can do nothing. 

the controller I actually got was labeled "Harpoon Control mechanism". Not sure if the difference in names is causing an issue? either way, using the mechanism does nothing other then put it on a 30 sec CD, and the Large Harpoon lever doesn't do anything either.

**Comment by Vircotto** [comment]
The harpoon guns are bugged. Activating the mechanism does nothing.


The lever the original poster commented on is for a different quest that has nothing to do with this one.

**Comment by Calebrimbor** [comment]
Issue added to the BugTracker for testing. Thank you for your report. 
@ Testers: Please add all details such as links etc.

**Comment by Calebrimbor** [comment]
Status BugTracker set as 'Pending'.

**Comment by Calebrimbor** [comment]
Tested the fix, still not able to go in any harpoon.

**Comment by Calebrimbor** [comment]
Fix is confirmed. Status on BugTracker set as 'Fixed'.
