### ISSUE TITLE
Being Kicked From Group After Disconnecting in Dungeon

### ISSUE THREAD

**Issue by acs9307** [wow-mania/Redemption#164]
I've tried running several dungeons, but I haven't been able to complete a single one as I always DC in the middle.  When I DC, even though I log back in right away, I am no longer in the group and am placed in the same location I disconnected at (the middle of the dungeon).  I am pretty sure the group isn't kicking me since it has happened over 5 times (every time I run a dungeon) and I log back in right away.  I've also noticed I seem to get more lag while in a dungeon than when I am normally questing.

I am playing from China and usually have lag around 300-500 ms, though it can sometimes spike pretty high.

**Comment by fvicaria** [comment]
While I appreciate you logging the issue this is not a game issue. Mention it at the forum support topic.
We are moving to a Tier 1 server tomorrow so my guess is that you lag will drop considerably.
Whisper me in-game and we can try run some tests.
