### ISSUE TITLE
[Instance] Ragnaros (11502) despawns if you don't kill him

### ISSUE THREAD

**Issue by mourasman** [wow-mania/Redemption#165]
Currently, when you ask Majordomo Executus to summon Ragnaros, he does and all goes well. The problem is that if you wipe and want to do the fight again, when you get back in the instance, Ragnaros won't be there.

To top it all off, only Janitor can spawn NPCs... :'(

**Comment by fvicaria** [comment]
Spawning a new NPC is not an answer and it will make things worse for the next time.
I will reduce a bit it's power.
Just don't wipe!

**Comment by mourasman** [comment]
"Spawning a new NPC is not an answer"

Of course not, that's why he shouldn't despawn when you wipe in the first place. That's the real issue here.

**Comment by fvicaria** [comment]
It's an event. So the event has some specific frequency limitation. I can look into that also but it won't be for now. 
The quicker solution in the time being is to reduce it's damage slightly.
