### ISSUE TITLE
[Quest] The Fallen Sisters

### ISSUE THREAD

**Issue by Calebrimbor** [wow-mania/Redemption#166]
http://www.wow-mania.com/armory/?quest=11314

For this quest you'll need to free 7 Chill Nymphs(http://www.wow-mania.com/armory/?npc=23678) by using Lurielle's Pendant(http://www.wow-mania.com/armory/?item=33606) on the Chill Nymph.

The pendant is not working, nothing happens.

**Comment by genasi** [comment]
The pendant is working, but the Chill Nymphs are supposed to be hostile. When you get them below a certain amount of HP, you use the pendant and the Chill Nymph is turned friendly and should run of, despawn and "make room for" a new hostile nymph to spawn.
This doesnt happen, so the nymphs are all friendly and you cant complete the quest.

**Comment by Calebrimbor** [comment]
Labeled with 'Priority' since this quest is frequently reported.

**Comment by Emcitementz** [comment]
This is working properly.

**Comment by Marvin023** [comment]
This quest is still not working. All the nymphs are still invalid targets. They are not resetting.

**Comment by ghostlynx-helios** [comment]
Found one nymph that was hostile and used pendant successfully, all the rest of the nymphs are pretty chill already... and non-hostile.
