### ISSUE TITLE
[Quest] Rallying the Troops

### ISSUE THREAD

**Issue by Calebrimbor** [wow-mania/Redemption#168]
http://www.wow-mania.com/armory/?quest=12070

For this quest you'll need to use Shard of the Earth(http://www.wow-mania.com/armory/?item=36764) on Grizzly Hills Giant(http://www.wow-mania.com/armory/?npc=26261) fighting in Boulder Hills. When doing so a Iron Rune Avenger(http://www.wow-mania.com/armory/?npc=26786) will spawn. 

Rallying a Grizzly Hills Giant will not complete the objective even when the opponent dies. The Iron Rune Avenger spawns, and that one does count when you kill it.

**Comment by Deathghat** [comment]
bug still present 
09/20/2021
