### ISSUE TITLE
[Quest] It's All Fun and Games

### ISSUE THREAD

**Issue by Calebrimbor** [wow-mania/Redemption#169]
http://www.wow-mania.com/armory/?quest=12887

For this quest you'll need to use the Eyesore Blaster(http://www.wow-mania.com/armory/?item=41265) to kill the The Ocular(http://www.wow-mania.com/armory/?npc=29747). The Ocular is on top of the Shadow Vault.

After a fix it did work for a few days. Now The Ocular is a 'invalid target', tried to stand inside of it. When you do, The Ocular drops to the roof of the Shadow Vault. After respawn he does the exact same thing.

**Comment by cajamangas** [comment]
there was no Ocular when i last tried about a week ago but im going to again now.this quest opens a questline and a flight path please fix this

**Comment by cajamangas** [comment]
FIXED THANK YOU VERY MUCH :)

**Comment by Calebrimbor** [comment]
Confirmed as fixed, thanks for your reply!

**Comment by Calebrimbor** [comment]
It's bugged again, Eyesore Blaster does not target The Ocular 'invalid target' and you can't target it yourself.

**Comment by Calebrimbor** [comment]
Labeled with 'Priority' since this quest is frequently reported.

**Comment by wow-mania** [comment]
I will reapply fix as it may have regressed for some reason. Not uncommon.

**Comment by Calebrimbor** [comment]
Status BugTracker set as 'Pending'.

**Comment by Calebrimbor** [comment]
Fix is confirmed. Status on BugTracker set as 'Fixed'.

**Comment by revenant1** [comment]
Bugged again ..
Eyesore Blaster does not target The Ocular 'invalid target' and you can't target it yourself.
18/09 15:35 st
