### ISSUE TITLE
[NPC] Warchief Rend Blackhand

### ISSUE THREAD

**Issue by mariogotze** [wow-mania/Redemption#17]
ID#10429

The arena even in Blackrock Upper Spire is bugged, there is spawning just 1 wave of mobs and it's supposed to be more and then, when Rend comes with his dragon Gyth, he is supposed on some % of his life to dismount Gyth and start fighting me, but he didn't dismount and i killed him, but the gate to go forward didn't open.

**Comment by wow-mania** [comment]
Should be fixed. Please retest.
