### ISSUE TITLE
[Quest] The Fel and the Furious

### ISSUE THREAD

**Issue by Kalasbyxan** [wow-mania/Redemption#17]
The quest (http://wow-mania.com/armory/?quest=10613) requires you to use a console to take control of a mechanical. The consoles are not here on this server. Look at video to compare: https://www.youtube.com/watch?v=_hCpLHyn4tI&feature=youtu.be

**Comment by huqboss** [comment]
Console is there, problem is that you can't attack infernals with controled robot

**Comment by Calebrimbor** [comment]
status BugTracker set as 'Pending'.

**Comment by Calebrimbor** [comment]
It's not fixed. There are two spots where these consoles should be, on 27.8, 19.7 and 40.7, 21.7. The ones shown on the video is at 27.8, 19.7, but they are nowhere to be found. The ones on 40.7, 21.7 are there but they are unclickable.

**Comment by Kalasbyxan** [comment]
Report that ally side controls work but not horde. Gonna look into it later.
