### ISSUE TITLE
[NPC] Coilfang Ray

### ISSUE THREAD

**Issue by CasillasHorde** [wow-mania/Redemption#170]
The mob Coilfang Ray http://www.wow-mania.com/armory/?npc=21128 is showing as a blue and white checked box throughout the dungeon. 
![wowscrnshot_071316_124252](https://cloud.githubusercontent.com/assets/20017541/16802751/458cd898-48fa-11e6-9ffd-cacf7cdd4fc4.jpg)

**Comment by Calebrimbor** [comment]
Confirmed. I've managed to reproduce. Issue is labeled as 'Confirmed' on the BugTracker.
