### ISSUE TITLE
[Class] Druid "Omen of Clarity" 

### ISSUE THREAD

**Issue by Chunkyfajita** [wow-mania/Redemption#171]
Omen of Clarity isn't working properly I keep getting the proc in cat form but it will not allow me to use it, "not enough energy for this ability."  I have to wait for 15seconds for the buff to go away and get another proc.  

I did some testing myself, if you cast heals on yourself until you get a proc go into cat form and Omen of Clarity will not work.

**Comment by fvicaria** [comment]
Should be fixed on the next build. Monday 20th.
