### ISSUE TITLE
Riding Talbuk

### ISSUE THREAD

**Issue by kholding** [wow-mania/Redemption#171]
I recently spent multiple days farming rep for the Mag'har. I went and bought a Talbuk after finally hitting exulted only to discover I just become little cube (http://imgur.com/m56OWD6). I had a GM, Calebrimbor, try to assist the issue. He discovered it was not an out of date client issue (I am running version 2.0.5) and he also saw me as just a cube. Not sure if the Talbuks just haven't been scripted? If you could please get this fixed, thanks! keep up the good work!

http://imgur.com/m56OWD6

**Comment by Calebrimbor** [comment]
Confirmed, saw a cube as well while running 2.0.5. Could you link the wow-mania armory link of the specific mount as a reply?

Thanks for reporting!

**Comment by kholding** [comment]
(http://www.wow-mania.com/armory/?spell=34897) Here it is

**Comment by kholding** [comment]
I just discovered its only the War Talbuks that are bugged. The riding Talbuks are just fine. I seen someone on a cobalt one and bought a white one myself.

**Comment by wow-mania** [comment]
Fixed. Make sure you start with Launcher.
