### ISSUE TITLE
Ingvar the Plunderer from Utgarde Keep yet again bugged

### ISSUE THREAD

**Issue by GriffinFin** [wow-mania/Redemption#172]
The third and last boss from Utgarde Keep , Ingvar the Plunderer, is somewhat glitched.After fully depleting his HP bar , the boss get resurrrected , however he does not enter Phase 2 , thus making the boss unkillable and the instance - impossible to complete.

**Comment by Calebrimbor** [comment]
This is confirmed, there is a workaround. Just be 30 yards away from him in the phase transition. It's definitely not working as intended.

http://www.wow-mania.com/armory/?npc=23980

**Comment by Calebrimbor** [comment]
Fixed for next Wednesday, status BugTracker set as 'Pending'.
