### ISSUE TITLE
Quest: Hell Hath a Fury

### ISSUE THREAD

**Issue by Naigio** [wow-mania/Redemption#173]
http://www.wow-mania.com/armory/?quest=12674
There seems to be some phasing issues with this quest.
I had to have a GM come around  to drag me into another phase to find the NPC "High Priestess Tua-Tua" as she was not in her proper location, or rather, she wasn't in the right phase, then afterwards he had to drag me back into another phase so I could deliver the quest.

**Comment by Calebrimbor** [comment]
Closing the issue, this quest will be added to [Project](https://github.com/wow-mania/Redemption/projects/2).

**Comment by Emcitementz** [comment]
No need for it to be added to the project, i fixed it.
