### ISSUE TITLE
[Quest] The Instigator's Enchantment

### ISSUE THREAD

**Issue by domvall** [wow-mania/Redemption#174]
this is a part of the questchain for the heroism set for warriors.
no spectres spawns in dire maul (no part at all) even though the room close to library should have them.
been through the whole instance a couple of times

**Comment by Calebrimbor** [comment]
Issue added to the BugTracker for testing. Thank you for your report. 
@ Testers: Please add all details such as links etc.

**Comment by Calebrimbor** [comment]
Tested it, the Spectres are there and they do drop the quest item. Removed the issue from the BugTracker.
