### ISSUE TITLE
Trial of the Sea Lion

### ISSUE THREAD

**Issue by 09uaopsifh12** [wow-mania/Redemption#175]
The 2nd pendant (aquatic agility) isn't where it's supposed to be... :') [For horde; Silverpine forest, quest addon standard from the wow-mania download gives location, other sources verify, but it's just not there...]
Waited 15 mins, but didn't respawn (and no other players were nearby either ;))

Gm Janitor finished the Q for me.

**Comment by fvicaria** [comment]
#154
