### ISSUE TITLE
[Quest] Free Your Mind

### ISSUE THREAD

**Issue by Calebrimbor** [wow-mania/Redemption#175]
http://www.wow-mania.com/armory/?quest=12893

For this quest you'll need to kill Vile(http://www.wow-mania.com/armory/?npc=29769), The Leaper(http://www.wow-mania.com/armory/?npc=29840) and Lady Nightswood(http://www.wow-mania.com/armory/?npc=29770) and use the Sovereign Rod(http://www.wow-mania.com/armory/?item=41366) provided by the quest giver on their dead bodies to turn them over.

After killing them the Sovereign Rod not always works. Sometimes it require to kill the target the second time to let the Rod work.

**Comment by GMLucetta** [comment]
Tested again today. Vile http://www.wow-mania.com/armory/?npc=29769 The Leaper http://www.wow-mania.com/armory/?npc=29840 Lady Nightswood http://www.wow-mania.com/armory/?npc=29770 are all laid on the ground as if dead but they attack as if alive. 

The Sovereign Rod http://www.wow-mania.com/armory/?item=41366 does not work despite using it two or three times and killing the mobs repeatedly.

![wowscrnshot_081916_113942](https://cloud.githubusercontent.com/assets/20618004/17807446/8ce6d958-6602-11e6-942d-01e5b10ee9b4.jpg)

**Comment by Calebrimbor** [comment]
Labeled with 'Priority' since this quest is frequently reported.
