### ISSUE TITLE
[Quest] They Grow Up So Fast

### ISSUE THREAD

**Issue by Calebrimbor** [wow-mania/Redemption#177]
http://www.wow-mania.com/armory/?quest=13906

For this quest you'll need to return 20 Venomhide Baby Teeth(http://www.wow-mania.com/armory/?item=47196), the Venomhide Hatchling(http://www.wow-mania.com/armory/?item=46362), 20 Runecloth(http://www.wow-mania.com/armory/?item=14047), 20 Rugged Leather(http://www.wow-mania.com/armory/?item=8170), and 80 gold to Mor'vek(http://www.wow-mania.com/armory/?npc=11701) in the southeastern part of the Marshlands in Un'Goro Crater. The Venomhide Hatchling will give you a daily quest, completing them will give you 1 Venomhide Baby Tooth per quest.

The Venomhide Hatchling doesn't give any quests.

**Comment by wow-mania** [comment]
I can't see any Daily quest from the NPC.

**Comment by ingelinge40** [comment]
alliance goblin cant take the daily que
