### ISSUE TITLE
[NPC Missing] Zepik the Gorloc Hunter

### ISSUE THREAD

**Issue by stijngun12** [wow-mania/Redemption#178]
He is missing according to my leveling guide. He should spawn after i accept a quest in sholazar basin: 
http://www.wowhead.com/npc=28216/zepik-the-gorloc-hunter#starts

**Comment by fvicaria** [comment]
THis NPC is summoned by a horn you get. If you lost it you can get it again with Elder Harkek (55.55. 69.70)
