### ISSUE TITLE
Bug list for Wow-Mania by Isotissi

### ISSUE THREAD

**Issue by isotissi** [wow-mania/Redemption#179]
Bug problems@Wow-Mania by Isotissi <Rinkirunkku>

Dungeon:
Azjol'Nerub: Krik'thir the Gatewatcher: Boss comes when pulling middle pack.
Ahn'Kahet: Many adds have huge aggro range(especially the first pack)
The Nexus: Ormorok the Tree-shaper: the ice pillar skill is spread in huge stack and randomly oneshots/kills a teammember even if he/she doesnt stand in it.
Halls of Stone: Krystallus: the stone breaking AoE hits everyone and kills whole group. Too long range with AoE?
Halls of Lightning: Ionar: Super fast disperse sparks. Not intentional.
Utarge Pinnacle: Skadi the Ruthless: Gets killed by oneshot by spear and doesnt drop loot.
Violet Hold: Erekem: Hits too fast, Windfury hits aprox. 8 times.
Utarge Keep: Ingvar the Plunderer: Phase 2 Darksmash always seem to hit maintank. In retail, it stands still when casting Dark Smash

Raid:
Obsidian Sanctum: Mini drakes: No portals to teleport and the effects inside the portal activates.
-Left drake oneshots ppl randomly
-Middle drake spawns millions of adds
-Right one goes immune if not killed fast enough.

Naxxramas:
Noth the Plaguebringer: Phase 2 Teleport to the balcony, he wont teleport down, Must be gripped by DK.

Talents:
[Impoved Blessing of Might] talent doesnt give extra AP.

**Comment by fvicaria** [comment]
https://github.com/wow-mania/Redemption/wiki/How-to-Log-a-Bug
