### ISSUE TITLE
[Dungeon] Hall of Lightning's General Bjarngrim

### ISSUE THREAD

**Issue by Ashamedlol** [wow-mania/Redemption#186]
http://www.wowhead.com/npc=28586/general-bjarngrim#abilities

He is supposed to move while he's casting Whirlwind, and the Arc Weld (http://wotlk.wowhead.com/?spell=59085) spell is supposed to deal damage to you when you move while you have it, but it doesn't.

Not really sure if he intercepts or not, haven't really seen him do so.

**Comment by Kalasbyxan** [comment]
General Bjarngrim (http://www.wow-mania.com/armory/?npc=28586) does stand in one place when casting Whirlwind.

The Arc Weld (http://www.wow-mania.com/armory/?spell=59085) cast by Stormforged Tacticial (http://www.wowhead.com/npc=28581/stormforged-tactician), and should be cast by Stormforged Lieutenant (http://www.wow-mania.com/armory/?npc=29240) too accoring to Wowhead, does not deal damage when moving like it should.
