### ISSUE TITLE
Sons of Hodir quartermaster bug

### ISSUE THREAD

**Issue by Marsji** [wow-mania/Redemption#186]
Hi.
I am not able to interact with the Sons of Hodir quartermaster even tho I am exalted. I just start to attack him. He doesn't attack me before I do. It is the same with the other NPC's there, questgivers etc. 

http://www.wowhead.com/npc=32540/lillehoff <-- This is the quartermaster.

**Comment by fvicaria** [comment]
Have you done all the quest chains, or just gotten exalted rep.. if you have missed any of the quests you (as far as I understand it) should not see the items. Double check that you have done them all. There is a lot of them.

This should be working fine if you have all the quests in the chain.
