### ISSUE TITLE
[NPC] Naxxramas10: Thaddius

### ISSUE THREAD

**Issue by isotissi** [wow-mania/Redemption#187]
Bug with Thaddius. If you wipe on Thaddius and already killed Feugen and Stalagg, they wont respawn and will have same reset as Bosses(weekly lockout). 
With no Feugen or Stalagg spawning, you can't engage/attack the boss.

http://www.wowhead.com/npc=15928/thaddius

**Comment by wow-mania** [comment]
Should be fixed on next release.
