### ISSUE TITLE
[Quest] The scepter of Celebras

### ISSUE THREAD

**Issue by GMLucetta** [wow-mania/Redemption#188]
http://www.wow-mania.com/armory/?quest=7046 Celebras is supposed to walk a way across the dungeon so that players can help him complete a ritual. For some reason Celebras http://www.wow-mania.com/armory/?npc=13716 to move in order for them to complete the ritual.

**Comment by ThaydeGM** [comment]
This has happened to me on my character in game.

**Comment by wow-mania** [comment]
Works fine. Find Celebra The Cursed first. Defeat him, he will turn into the Celebras the Redeemed. Follow him and do what he asks.
