### ISSUE TITLE
[Quest]From the Depths of Azjol-Nerub

### ISSUE THREAD

**Issue by Gmsosukeaizen** [wow-mania/Redemption#193]
http://www.wow-mania.com/armory?quest=12036.In this quest you are to explore the Pit of Narjun But no matter where you go or how many mobs you kill it will not complete.

**Comment by poserbiker** [comment]
As per latest TC seems fine. 
![from the depths of azjol-nerub](https://cloud.githubusercontent.com/assets/896742/18579434/7a6a2fc4-7baa-11e6-80c3-7f16e94ceb23.PNG)
