### ISSUE TITLE
[Quest] The Frost Wyrm and its Master

### ISSUE THREAD

**Issue by Gmsosukeaizen** [wow-mania/Redemption#194]
http://www.wow-mania.com/armory?quest=11267.In this quest you are to kill a Wrymcaller Vile.Collect and Wyrmcaller's Horn and then use it to summon Glacion but no matter where you stand on the platform you can not use the Wyrmcaller's Horn.

**Comment by Demonbacks** [comment]
Yeah but right now i found her flying around and complete the quest :D Dont know if she spawns quickly.

**Comment by Calebrimbor** [comment]
Labeled with 'Priority' since this quest is frequently reported.

**Comment by Emcitementz** [comment]
Minor bug fixed, back in the days, Glacion was initially spawned in the air because you couldn't use flying mounts at this era and therefore, you couldn't kill him at all.
The only way to kill him was indeed to get the horn and then, call him down.
