### ISSUE TITLE
[Quest] We Call Him Steelfeather

### ISSUE THREAD

**Issue by Gmsosukeaizen** [wow-mania/Redemption#195]
http://www.wow-mania.com/armory?quest=11418.In this quest you are to use the Feathered Charm and be able to look into his eyes and he will take you to where his secret is but he never goes and he can not be targeted again once you use the Feathered Charm.

**Comment by wow-mania** [comment]
Fixed for next Wednesday. Please confirm.

**Comment by Calebrimbor** [comment]
Fix is confirmed. Status on BugTracker set as 'Fixed'.
