### ISSUE TITLE
[Quest] I've Got A Flying Machine

### ISSUE THREAD

**Issue by Gmsosukeaizen** [wow-mania/Redemption#196]
http://www.wow-mania.com/armory?quest=11390.In this quest you are to use the flying machine to pick up the Sack of Relics but once you pick them up you can not put them down.

**Comment by iggapres** [comment]
This quest seems to be buggy again (same problem)

**Comment by cellosgame** [comment]
http://www.wow-mania.com/armory?quest=11390

This quest is still bugged. I can pick up the bag but can't drop it off. and when I logged out and back in it kept my character running in a forward direction.  I tried to /reload and that did nothing.

**Comment by fvicaria** [comment]
Quest works fine. I have just done it. Check video.
