### ISSUE TITLE
[Quest] The Defias Brotherhood

### ISSUE THREAD

**Issue by Gmsosukeaizen** [wow-mania/Redemption#198]
http://www.wow-mania.com/armory?quest=142.In this quest you are suppose to kill the Defias Messenger but after spending about 20 minutes searching for him he is no where to be found and I have been ever inch of the map.

**Comment by huqboss** [comment]
rare spawn, but doable (did 2x)

**Comment by Emcitementz** [comment]
Nothing wrong here.
