### ISSUE TITLE
Quest - The Light of Dawn (12801)

### ISSUE THREAD

**Issue by Zhaix123** [wow-mania/Redemption#202]
The quest Light of Dawn seems to be bugged.

I picked up the quest, the regular RP happened with Darion giving his speech, then we rode off to the chapel and there were no Argent Dawn npcs to fight, then Darion and a bunch of other npcs despawned.

Tried abandoning it and picking it back up, but nothing worked.

**Comment by Zhaix123** [comment]
I had Norrell complete the quest for me, but Darion despawned earlier so i have nowhere to turn it in.

**Comment by MrNorrell** [comment]
This does seem to be affecting multiple people now. I can autocomplete it for them but the hand-in guy disappears/disappeared so they're a bit stuck. This may be because of the abnormally long respawn time and the recent server restart?

**Comment by Zhaix123** [comment]
Darion respawned and we could turn it in. tho i suppose the initial problem is still a present thing.

**Comment by duttyy** [comment]
had no any problems with this quest.. worked fine for me

**Comment by fvicaria** [comment]
The issue may be the x2 and the Heirlooms.
