### ISSUE TITLE
[Quest] No Place To Run

### ISSUE THREAD

**Issue by GMLucetta** [wow-mania/Redemption#203]
http://www.wow-mania.com/armory/?quest=12261 when placing the Destructive Ward http://www.wow-mania.com/armory/?item=37445 It doesn't charge and no mobs appear to attack it either.

**Comment by Calebrimbor** [comment]
Status BugTracker set as 'Pending'.

**Comment by Calebrimbor** [comment]
Fix is confirmed. Status on BugTracker set as 'Fixed'.
