### ISSUE TITLE
Instance Bug: Culling of Stratholome

### ISSUE THREAD

**Issue by Bravopatriot** [wow-mania/Redemption#204]
Wow-mania client and launcher
Windows 10

Culling of Stratholome (Heroic)
During part 2 of the instance where Arthus runs to the stairs leading in to the infinite dragonflight spawns 
random untargetable residents attack him and kill him. this prevents us from talking to him and starting the second phase. not sure why anything targets him at this point. have attached screenshots.

![wowscrnshot_072516_213349](https://cloud.githubusercontent.com/assets/19984295/17124339/0bb78b12-52b0-11e6-82f9-8df6ecfeec92.jpg)
![wowscrnshot_072516_213354](https://cloud.githubusercontent.com/assets/19984295/17124341/0bb7e7d8-52b0-11e6-9f5a-79151b86d957.jpg)
![wowscrnshot_072516_213402](https://cloud.githubusercontent.com/assets/19984295/17124340/0bb7adae-52b0-11e6-9834-18b79a01dbd2.jpg)

**Comment by Calebrimbor** [comment]
Fixed
