### ISSUE TITLE
[QUEST] Massacre at Light's Point

### ISSUE THREAD

**Issue by Vircotto** [wow-mania/Redemption#207]
http://www.wow-mania.com/armory/?quest=12701

When using the mine cart to have the miner NPC take you to the boat, all enemies aggro to you. You should be invisible/friendly to all enemies while in the cart.

It can be reproduced multiple times by simply getting into the cart and trying over and over. You are forced to run down to the ship yourself aggroing every mob along the way.

I tried using the /reload command and even tried exiting the game completely. Restarting and logging back in. None of these fixed the issue. I have not found this issue at all in the bug tracker.

I am using the WoW-Mania client, fully updated and on Windows 8.1.

**Comment by GMLucetta** [comment]
I can confirm that this isn't working as intended.
