### ISSUE TITLE
Cache of the Ley-Guardian

### ISSUE THREAD

**Issue by huqboss** [wow-mania/Redemption#210]
no drops on my main 8 times in a row, on alts no problem, is it normal? GM couldn't help, asked to make a topic here

**Comment by Calebrimbor** [comment]
Labeled with 'Priority' since this quest is frequently reported. It seems the end boss disappears sometimes in the middle of the fight, or when he dies not to give any loot or emblems. Not yet confirmed

**Comment by Kalasbyxan** [comment]
Confirmed. Has been an issue since server start.

**Comment by wow-mania** [comment]
Fixed.
Probability 59%
