### ISSUE TITLE
[Quest] Keeping Pace

### ISSUE THREAD

**Issue by GMLucetta** [wow-mania/Redemption#212]
http://www.wow-mania.com/armory/?quest=1190
Zamek is supposed to create a diversion for the player but he isn't doing so. Therefore the quest cannot be completed.

**Comment by wow-mania** [comment]
Missing a gossip menu probably.

**Comment by wow-mania** [comment]
#197 #148 all 3 quests are related to the same object that refuses to call OnGossipSelect

**Comment by wow-mania** [comment]
As I workaround just go inside the hut and get the plans. As the name says it's unguarded. No need to talk to Zamek.
