### ISSUE TITLE
[Quest] Dark Heart

### ISSUE THREAD

**Issue by Calebrimbor** [wow-mania/Redemption#213]
http://www.wow-mania.com/armory/?quest=3062

For this quest you'll need to gather a Horn of Hatetalon(http://www.wow-mania.com/armory/?item=9530) from Northspring Harpies. When gathered you'll need to go to the Hatetalon Stones to use the horn in order to summon Edana Hatetalon(http://www.wow-mania.com/armory/?npc=8075) and to loot her heart(http://www.wow-mania.com/armory/?item=9528) afterwards.

You can't use the Horn when being at the Hatetalon Stones.

**Comment by redhawk816** [comment]
This appears to be broken again.  I have the http://www.wow-mania.com/armory/?item=9530 and I'm at the Hatetalon Stones.  When I click on the horn it looks like it begins to cast but only for a tenth of a second before it fizzles out.  I've re-positioned to every inch around, in and over the stones and it does not finish casting the summons.
