### ISSUE TITLE
[Quest] Sarathstra, Scourge of the North

### ISSUE THREAD

**Issue by Calebrimbor** [wow-mania/Redemption#214]
http://www.wow-mania.com/armory/?quest=12097

For this quest you'll need to talk with Rokhan(http://www.wow-mania.com/armory/?npc=26859) in order for him to lure Sarathstra(http://www.wow-mania.com/armory/?npc=26858). When killing it will drop the Frozen Heart(http://www.wow-mania.com/armory/?item=36793)

You can't interact with Rokhan.

**Comment by Kalasbyxan** [comment]
Rokhan says to stay away if you want to live, but doesn't bring Sarathstra down. Sarathstra roams the air and can be aggroed by managing to aggro her while flying and manage to maintain aggro until player is grounded. It is doable, if flying and if grabbing her at a certain spot. Definitly not as intended.
