### ISSUE TITLE
NPC - Silva Fil'naveth

### ISSUE THREAD

**Issue by mjhelto** [wow-mania/Redemption#215]
It would seem that my Worgen Druid is not friendly enough with the Moonglade faction.  As a result, I cannot take the Darnassus-specific flight path back like another Druid race would be able to.  I just started playing on WoW-Mania so I cannot clarify if this is an issue for all Worgen Druids or just mine.

 - I am using the WoW-Mania client.
 - I am using the WoW-Mania launcher.
 - My OS is Windows 7 Ultimate 64-bit.
 - To recreate:
      1) Create a Worgen Druid.
      2) Get to level-10.
      3) Start the [quest](http://www.wowhead.com/quest=5923/heeding-the-call) provided by the Druid trainer [Kal](http://www.wowhead.com/npc=3602/kal) in Dolanaar > Teldrassil (55.6, 53.8).
      4) Talk to [Mathrengyl Bearwalker](http://www.wowhead.com/npc=4217/mathrengyl-bearwalker) in the Cenarion Enclave of Northern Darnassus (40.4, 27.6) and get the [quest](http://www.wowhead.com/quest=5930/great-bear-spirit).
      5) Take the new Moonglade Portal spell to Moonglade.
      6) Rejoice in all the neutral NPCs that let you talk/trade with them but not leave the area via the [flight path](http://www.wowhead.com/npc=11800/silva-filnaveth) (44.2, 45.8).
 - All links are provided in the steps above.

**Comment by Calebrimbor** [comment]
It doesn't seem to be Worgen related. As a Night Elf I wasn't able to fly as well. Horde flight path is working fine. Could you please rename your post to: Moonglade Alliance flight path is broken

In a addition:
You can't interact with Silva Fil'naveth(http://www.wow-mania.com/armory/?npc=11800).

**Comment by mjhelto** [comment]
You can interact with her but she just says hi to you and lets you say goodbye.

**Comment by hisagi0san** [comment]
This bug cause another probleme due to the fact that this NPC is needed for the quest of the sea form. You need to ask her the location of half of the pendant to be able to open coresponding the box.
