### ISSUE TITLE
Sindy

### ISSUE THREAD

**Issue by JarlOfRedemption** [wow-mania/Redemption#215]
Stopped casting ice tombs after 1 or 2 during phase 3 which left us unable to reset our stacks of mystic buffet. 

Also minor graphical thing, she appeared invisible before we fully started the encounter, couldnt even tell she was there

**Comment by fvicaria** [comment]
Was it doable or does this affect the progression?

**Comment by MissShiz** [comment]
fvicaria, it causes the Mystic Buffet ability to kill the tanks and raid as the stacks aren't resettable.
