### ISSUE TITLE
[Quest] To Venomspite!

### ISSUE THREAD

**Issue by genasi** [wow-mania/Redemption#216]
The quest To Venomspite! (http://www.wow-mania.com/armory/?quest=12182) is bugged.
The text say that you should get a bat that will fly you to Venomspite in Dragonblight. This is the quest that introduces you to dragonblight and venomspite, so its a really long run from New Agamand in Howling Fjord to hand it in without the promised bat.
The npc is Tobias Sarkhoff (http://www.wow-mania.com/armory/?npc=24155) the Flight Point in New Agamand.

**Comment by Calebrimbor** [comment]
Issue added on the BugTracker for testing. Thank you for your report.

**Comment by GMLucetta** [comment]
Confirmed. I've managed to reproduce. Issue is labeled as 'Confirmed' on the Bug Tracker.
