### ISSUE TITLE
[Class] Glyph of Sunder Armor

### ISSUE THREAD

**Issue by Sehtim** [wow-mania/Redemption#217]
The Glyph should affect a second target with an additional stack of sunder armor, when using sunder armor. But both, the main and the second target, get 2 stacks of sunder armor. So 4 stacks instead of 2 stacks are applied.

**Comment by Sehtim** [comment]
I found out, that when fighting more than 2 mobs, the 4 stacks of sunder armor are distributed randomly on them. Not even the one you target must get at least 1 stack.
So fighting 1 mob = 1 stack on it.
Fighting >=2 mobs = 4 random stacks.

**Comment by Calebrimbor** [comment]
Status BugTracker set as 'Pending'.
