### ISSUE TITLE
[Quest] Waste Not, Want Not

### ISSUE THREAD

**Issue by Calebrimbor** [wow-mania/Redemption#219]
http://www.wow-mania.com/armory/?quest=10055

For this quest you'll need to gather 8 Salvaged Metal(http://www.wow-mania.com/armory/?item=25912) and 8 Salvaged Wood(http://www.wow-mania.com/armory/?item=25911).

Can't pick up both metal and wood.

**Comment by poserbiker** [comment]
From what I see on latest TC its working just fine. 
![waste not want not](https://cloud.githubusercontent.com/assets/896742/18543249/b8884664-7ae3-11e6-9daa-66ae029640d3.PNG)
![waste not want not1](https://cloud.githubusercontent.com/assets/896742/18543250/b88fc1fa-7ae3-11e6-9c42-b4c3b86adcd1.PNG)

**Comment by Emcitementz** [comment]
Works fine, indeed.
