### ISSUE TITLE
[Quest] In Dreams

### ISSUE THREAD

**Issue by ilDavincho** [wow-mania/Redemption#22]
Hi. http://www.wowhead.com/quest=5944/in-dreams

This is the last quest from plaguelands chain and it's bugged because Taelan Fordring doesn't move. It's so frustrating. Please can you see if it's fixable?? Thanks!

**Comment by Calebrimbor** [comment]
Issue added on the BugTracker for testing. Thank you for your report. 
@ Testers: Please add all details such as links etc.

**Comment by GMLucetta** [comment]
Confirmed. I've managed to reproduce. Issue is labeled as 'Confirmed' on the Bug Tracker.
