### ISSUE TITLE
[Quest] Absholutely... Thish will Work! - Alliance - Howling Fjord

### ISSUE THREAD

**Issue by Dysenteria** [wow-mania/Redemption#223]
Given a quest item called Peppy's Special Mix, which you are suppose to use on a vrykul prisoner in the basement of Westguard castle. When you use the item it has a 2s cast bar, but nothing happens. No matter where you stand in the room and use the item, no matter your target, the cast bar will appear but nothing will ever happen.

**Comment by wow-mania** [comment]
Duplicate #49
