### ISSUE TITLE
[Quest] The Deadliest Trap Ever Laid

### ISSUE THREAD

**Issue by Calebrimbor** [wow-mania/Redemption#225]
http://www.wow-mania.com/armory/?quest=11097

Commander Hobb(http://www.wow-mania.com/armory/?npc=23434) is not entirely there. You could see his weapon, but no body. You can't interact with him to start the above mentioned quest.

http://imgur.com/a/QVW8w

**Comment by Emcitementz** [comment]
Fixed the invisibility of his body and the fact that you couldn't interact with him.
(Note that you need a certain amount of his own reputation to get the quest).
Working on the quest now.

**Comment by Emcitementz** [comment]
Quest also fixed.
