### ISSUE TITLE
[Quest] The Denouncement

### ISSUE THREAD

**Issue by GMLucetta** [wow-mania/Redemption#227]
http://www.wow-mania.com/armory/?search=the+denouncement

Players have to use http://www.wow-mania.com/armory/?item=37438 on the following NPCs
http://www.wow-mania.com/armory/?npc=27426
http://www.wow-mania.com/armory/?npc=27427
http://www.wow-mania.com/armory/?npc=27428
http://www.wow-mania.com/armory/?npc=27429

Once targeted they will denounce the Scarlet Onslaught on death. 

This does not work correctly and they cannot be given the debuff.

**Comment by Emcitementz** [comment]
Worked on test realm.
