### ISSUE TITLE
[Quest] Escape from The Staging Grounds

### ISSUE THREAD

**Issue by GMLucetta** [wow-mania/Redemption#228]
http://www.wow-mania.com/armory/?quest=10425

When you speak to http://www.wow-mania.com/armory/?npc=20763 he wanders about aimlessly rather than doing a full escort quest.

**Comment by Readerlady** [comment]
In addition on this one there is an npc that you can not attack that kills the dude you are escorting.

**Comment by wow-mania** [comment]
Working in live now.
