### ISSUE TITLE
[Item] Cleverly Encrypted Letter

### ISSUE THREAD

**Issue by Calebrimbor** [wow-mania/Redemption#233]
http://www.wow-mania.com/armory/?item=3521

Starts a quest Encrypted Letter(http://www.wow-mania.com/armory/?quest=511) part of a chain.
Item is in Alterac Mountains in Sofera's Naze.

Item is there, you can't loot it. In GM mode you can interact with it, only gives no item to start a quest with.

**Comment by Emcitementz** [comment]
This a false report.
