### ISSUE TITLE
[Quest] Back so Soon?

### ISSUE THREAD

**Issue by Demonbacks** [wow-mania/Redemption#234]
Can´t interact with the npc High-Oracle Soo-say, so you can´t deliver the quest.
http://www.wowhead.com/quest=12574/back-so-soon

**Comment by Karokx** [comment]
you cannot interact with Mistcaller Soo-gan, not soo-say
http://www.wowhead.com/npc=28114/mistcaller-soo-gan

**Comment by Calebrimbor** [comment]
Closing the issue, this quest will be added to [Project](https://github.com/wow-mania/Redemption/projects/2).
