### ISSUE TITLE
ITEM: Ebonweave Robe, Spellweave Robe and Spellweave Gloves won't show up in AH search

### ISSUE THREAD

**Issue by Ackpfft** [wow-mania/Redemption#235]
Unless someone specifically types "Ebonweave Robe" in the search tab at the auction house, this item will not show up on a typical search for cloth chest gear. It also happened when trying to sell a "Spellweave Robe" and "Spellweave Gloves" a couple months ago.   I despise trying to sell items in chat, due to the trolling, so if this weird bug could be addressed I'd be incredibly grateful.

**Comment by wow-mania** [comment]
Item will appear under Cloth but not under chest for some reason. Given the nature of the bug and the simple work around I won't be fixing this.
