### ISSUE TITLE
Bug @ HoR HC escape-event

### ISSUE THREAD

**Issue by typho0nz** [wow-mania/Redemption#24]
Are you using our client? -> yes

Are you using the latest Launcher? -> yes (but without wod-models cause they result in dc's @ dalaran)

Did I include the operating system I am using?
not needed (happens to whole group with different pc-setups)

Did I include the steps to reproduce the problem?
We (Drakthes, Noarms, Jensitoh, Surrenety) were in Halls of Reflection Hero at the final boss (LK-event).
First waves worked fine until the final wave. We killed the mobs just in time and Sylvanas opend the last ice-wall for us. Before we could move the LK killed us all with his aoe.
We saw the airship but had to revive and reenter the instance. Then we walked to the end but the airship was stucked midair without the stairs to get on top.
I tested flying to the ship but there was just a portal to dalaran and an unusable chest.
We decided to redo the event which was possible cause both npc's resetted.
So we slapped the LK until we're able to talk to Sylvanas again and we repeated the escape-event.

In the end Sylvanas was doing her monolog and the airship landed. The lootchest was still not clickable and we were suprised to could talk to Sylvanas again in front of the airship, which was rly strange.
Cause we got no choise we talked with her, the Lichking spawnd and insta-aoed us to death.
We were still unable to loot the chest and gave up and decided to make a ticket which leaded me here ;)

Hope i could help (ign: Dachdagger skype: Christian S.)

Best regards and thanks in advance!

**Comment by Calebrimbor** [comment]
Fixed a while ago.
