### ISSUE TITLE
[Quest] Take Down Tethyr!

### ISSUE THREAD

**Issue by gibbs0007** [wow-mania/Redemption#24]
The quest line works all the way to the end where you have to defend the harbor from Tethyr. Tethyr doesn't actually come into the harbor but running from the left mortar to the center mortar and back to the left mortar enough times will kill the monster. After he dies, however, the quest does not advance.

**Comment by fvicaria** [comment]
http://www.wowhead.com/quest=11198/deprecated-take-down-tethyr

**Comment by fvicaria** [comment]
Fixed. Sometimes I noticed that Tethyr does not move up so you have to use the side cannons only. Also you only have 6 minutes to do the quest or it will fail.
