### ISSUE TITLE
[Quest] The Missing Diplomat

### ISSUE THREAD

**Issue by GMLucetta** [wow-mania/Redemption#241]
http://www.wow-mania.com/armory/?quest=1249

Players are to subdue http://www.wow-mania.com/armory/?npc=4962 Tapoke "Slim" Jahn and then return to the quest giver. 

When accepting the quest http://www.wow-mania.com/armory/?npc=4962 does not become interactable with.

**Comment by wow-mania** [comment]
Works in live.

**Comment by Rushor** [comment]
on live*
