### ISSUE TITLE
Quest bug : The last line of defence (Icecrown)

### ISSUE THREAD

**Issue by Gallowsmere** [wow-mania/Redemption#244]
Only one gun on the towers at the far corner, small mobs are ok but they cluster around the base and are difficult to target. The problem is the big frost worms, you hit them they attack the tower but before you can kill them they evade and heal up, this means starting again but the tower losses health and each time they evade. Time to evade is not based on health or time and seems random maybe position ?
I was shaman lv 79

**Comment by fvicaria** [comment]
Fixed.
