### ISSUE TITLE
Quest: A race against time (Borean Tundra)

### ISSUE THREAD

**Issue by antonius123** [wow-mania/Redemption#248]
Hi Janitor,
I've been trying to do A race against time. I've done it twice without problems but on my 3rd character, it didn't work. I have to use a bomb to break the beryl force field, then the Inquisitor Sarland attacks and I kill her. This time, the shield doesn't seem to break at all, I can go through it anyway, and Inquisitor Sarland is always out of my line of sight. I've tried throwing bomb at her (recommended by Norrell as the issue's solution) and it didn't work either. 

Thanks.

http://www.wowhead.com/quest=11671/a-race-against-time

**Comment by wow-mania** [comment]
THis one works fine the follow up quest doesn't.
