### ISSUE TITLE
[PvP] Targeting in arena

### ISSUE THREAD

**Issue by Lokkek** [wow-mania/Redemption#25]
GAME BREAKING for competitive arena.
Enemy players maintain targeting on player from Prep phase into the arena battle.  Players are able to start the arena with stealth players targeted and cast spells on stealth / phased players and pets.

Effects: rogues, druids, mages while invis (probably), warlock imp pet, hunter stealthed pets.  Pets matter as if the player chooses to use an invis or stealthed pet, then the enemy is able to pretarget them and dps them down.  Killing pets is a common strategy when dealing with -any- pet class.  While targeting of enemies in arena during preparation is blizzlike, upon arena start of the match you should lose targeting on any player that has stealthed or invis prior to match.  Arena enemy frames should populate upon entering arena (blizz frames and Gladius addon) but enemy should lose targeting on any player that stealths/invis, even during Prep period.

Suggestion: force target drop of enemy at arena start?  Also might have to fix bug which allows players to continue casting on stealth/invis players should they have them targeted prior to stealth/invis?

How to replicate: 
- zone into an arena, target enemy player rogue/druid/mage or pet.  Have rogue go into stealth prior (or during, I think this is a bug as well) to arena beginning, once the match starts cast on the rogue (Hunter's Mark, any spell while in range; game breaking in Ring of Valor).

**Comment by Lokkek** [comment]
Did some testing.. Stealth does not work in arena.  Regardless of vanish state or stealth then enemy can see through stealth and invis from any range.

This is way beyond game breaking. There is no way to get sap or open on a team when they can see you from a mile away.

**Comment by wow-mania** [comment]
Should be fixed by Wednesday.
