### ISSUE TITLE
[QUEST] The Chain Gun and You

### ISSUE THREAD

**Issue by djdougie** [wow-mania/Redemption#251]
Quest requires you to man a chain gun and cover 7th Legion soldiers running back to safety. 

Soldiers do not move, gun is moveable (should be immobile). Not able to be completed.

Wintergarde Quest Line, Alliance, Dragonblight

**Comment by wow-mania** [comment]
Fixed. 
1. Use cannon to get rid of mobs
2. to call soldier
3. go after soldier and guide him to stairs
