### ISSUE TITLE
Northrend Quest; Keristrasza

### ISSUE THREAD

**Issue by 09uaopsifh12** [wow-mania/Redemption#252]
The quest is completed, I need to talk to "Keristrasza" NPC, but she vanishes
There is a quest item that I need, but it disappeared, I need to talk to this guy Raelorasz to get a new one, but he doesn't give it...

So ehh, how to fix this?!

**Comment by wow-mania** [comment]
Keristrasza is not always there. Use the Augmented Arcane Prison to summon her. If you lost the item ask Raelorasz to give you another one.
http://www.wowhead.com/item=35671/augmented-arcane-prison
