### ISSUE TITLE
[Quest] A fall from grace

### ISSUE THREAD

**Issue by GMLucetta** [wow-mania/Redemption#254]
http://www.wow-mania.com/armory/?quest=12274

Players, whilst under the http://www.wow-mania.com/armory/?spell=48761 have to go to the top of the Abbey in New Hearthglen and ring a bell. This will summon the bodyguards and enable the player to talk to http://www.wow-mania.com/armory/?npc=27245 

This does not happen, the bodyguards don't appear upstairs and there are no dialogue options with http://www.wow-mania.com/armory/?npc=27245

**Comment by wow-mania** [comment]
Quest works perfectly.
