### ISSUE TITLE
[PVP] Arena points weekly distribution

### ISSUE THREAD

**Issue by Tapenade** [wow-mania/Redemption#255]
On this server : there is no arena points distributions.

Normally : In fact, to gain arena points you have to play with your arena team at least 10 games a week. You have to play at least 33% of the arena games played during this week. 
If you did this, the same day of each week (for example each sundays if sunday is the distribution day), the arena week will stop and a new one will start right after the points will be distributed. Obviously the more your rating is high, the more points you gain.

**Comment by fvicaria** [comment]
Fixed. Should be pushed this Friday.
