### ISSUE TITLE
[Priest] Discipline tier 9 talent "Grace" functionality issue

### ISSUE THREAD

**Issue by Inbreaded** [wow-mania/Redemption#258]
I believe this issue was reported ~7 hours ago but the report lacked any sort of information; I recommend closing that one or attaching it to this one.

Bug Description [Current Outcome]:
When healing a target with Penance, Flash Heal, or Greater Heal, Grace talent applies 3% healing buff to target stacking up to 3 times, but only when within melee range.

Expected Outcome:
When healing a target with Penance, Flash Heal, or Greater Heal, Grace talent applies 3% healing buff to target stacking up to 3 times.

Steps to reproduce:
1. Have a priest of level 61 or higher with Grace talent maxed.
2. Have a target to heal other than self.
3. Heal target with Flash Heal.
4. Check to see if 3% healing buff "Grace" is applied.
5. Repeat steps 3 and 4 two additional times, checking each time to see if buff stacks up.
6. Repeat steps 3 through 5, substituting Greater Heal for Flash Heal.
7. Heal a target with Penance.
8. Check to see if 3% healing buff is applied 3 times.
Grace effect ID (couldn't find it on wowhead, this is from openwow):
Apply Aura: Unknown_Aura(283) 
Value: 3

Issue self checklist:
I am using wow-mania client
I am using wow-mania launcher
Operating system windows 7

**Comment by Holiia** [comment]
Confirmed just tested this bug my self  
Spell ID: 47517 http://www.wow-mania.com/armory/?spell=47517
Spec: Discipline
Out of melee rang  target does not get Buff

**Comment by nesttt** [comment]
Hi
Any progress? i see its still bugged.
Thanks

**Comment by Calebrimbor** [comment]
status BugTracker set as 'Pending'.

**Comment by Calebrimbor** [comment]
Fix is confirmed. Status on BugTracker set as 'Fixed'.
