### ISSUE TITLE
[Raid] Karazhan's Attumen the Huntsman

### ISSUE THREAD

**Issue by Ashamedlol** [wow-mania/Redemption#259]
Attumen is supposed to jump on the horse and fight you with him after a certain time/percentage, however he's just stuck on 1% and refuses to continue the phase, making him invulnerable/unkillable.

**Comment by Kalasbyxan** [comment]
This is an issue when high level players damaged the boss too quick. If the dmg excesses the phase % it might stuck. It can happen in retail too.

**Comment by wow-mania** [comment]
Damage limited now.
