### ISSUE TITLE
[PvP] Targeting after stealth or vanish

### ISSUE THREAD

**Issue by Lokkek** [wow-mania/Redemption#26]
Issue: I have seen players send pets (charge type specifically) and cast spells on rogues after the rogue either manually stealths (drop combat) or vanishes.  I have vanished and had pets continue to follow and ultimately attack me, I have vanished off Hunter's Mark (intended gameplay) only to have the hunter reapply Hunter's Mark while I am in both a vanish and stealthed state.

**Comment by Lokkek** [comment]
Did some testing.. Stealth does not work in arena.  Regardless of vanish state or stealth then enemy can see through stealth and invis from any range.

This is way beyond game breaking. There is no way to get sap or open on a team when they can see you from a mile away.

**Comment by wow-mania** [comment]
Should be fixed by Wednesday. Please reopen if not.
