### ISSUE TITLE
[Quest] The Hunter and the Prince (13361, 13400)

### ISSUE THREAD

**Issue by ChemicalSerenity** [wow-mania/Redemption#26]
After talking to Mathais Lerner to get the quest, he informs you that you should "find a bloodstained stone and pick it up". The stone does not spawn (according to comments on other sites, it should spawn at 47:72 in icecrown).

To Reproduce:

- Accept the quest
- Look futilely for the aforementioned stone
- Get killed a few times by a Boneguard Commander standing nearby

**Comment by wow-mania** [comment]
quest id # 13361
mathais id #32497

Need confirmation of this bug.

**Comment by fvicaria** [comment]
Fixed. The stones will despawn now after 60 seconds instead of 30. You need to find one of them quick. If you fail to find them or lose to Illidan you have to abandon and retake the quest.
