### ISSUE TITLE
[Quest] Bodyguard for Hire

### ISSUE THREAD

**Issue by Calebrimbor** [wow-mania/Redemption#262]
http://www.wow-mania.com/armory/?quest=5821

For this quest you'll need to escort Cork Gizelton's Caravan through the Kolkar Centaur Village.

This Caravan is nowhere to be found.

**Comment by wow-mania** [comment]
Fixed for Wednesday. This was a regression.

**Comment by Calebrimbor** [comment]
Fix is not working, issue still persists with the exact malfunction. Reopened the issue.

**Comment by Calebrimbor** [comment]
Fix is confirmed. Status on BugTracker set as 'Fixed'.
