### ISSUE TITLE
[Quest] A Mammoth Undertaking

### ISSUE THREAD

**Issue by Calebrimbor** [wow-mania/Redemption#265]
http://www.wow-mania.com/armory/?quest=12607

For this quest you'll need to use the Mammoth Harness(http://www.wow-mania.com/armory/?item=38627) on a Shattertusk Mammoth(http://www.wow-mania.com/armory/?npc=28374) and bring the Mammoth to the quest giver.

Nothing happens when you apply the harnass.

**Comment by wow-mania** [comment]
This quest works. Unfortunately the harness is only used to make the mammoth friendly you need to click on it to mount it.
