### ISSUE TITLE
[Quest] Leading the Charge

### ISSUE THREAD

**Issue by Calebrimbor** [wow-mania/Redemption#266]
http://www.wow-mania.com/armory/?quest=13380

For this quest you'll need to talk with Karen No(http://www.wow-mania.com/armory/?npc=31648), she will put you on a airplane bomber so you could throw bombs to 40x Bombardment Infantry, 8x Bombardment Captain(http://www.wow-mania.com/armory/?npc=32410) and 15x Gargoyle Ambusher(http://www.wow-mania.com/armory/?npc=32188).

Nothing happens when you select 'Give me a bomber' when talking to Karen No.

**Comment by wow-mania** [comment]
Will be fixed after next update.

**Comment by Calebrimbor** [comment]
Karen No gives you a bomber now, only the Gargoyle Ambushers are not killable, they take no damage while using the AA gun. They set the bomber on fire. The Bombadment Infantry and Bombardment Captains are nowehere to be found. I've located 1 Gargoyle, you'll need 15 to complete the objective. I've reopened the issue

**Comment by wow-mania** [comment]
It was fixed a while back. I just tested and it works.
