### ISSUE TITLE
[Quest] Cold Hearted

### ISSUE THREAD

**Issue by GMLucetta** [wow-mania/Redemption#269]
http://www.wow-mania.com/armory/?quest=12856

Players have to fly on their own mounts to Dun Niffelem then use the Freed Proto-Drake (http://www.wow-mania.com/armory/?npc=29709) to rescue 9 Liberated Brunnhildar (http://www.wow-mania.com/armory/?npc=29734)

The Freed Proto-Drake do not allow the player to fly without the player having pressed the spacebar first. Whilst this is a workaround the quest isn't working as intended.

**Comment by Calebrimbor** [comment]
Status BugTracker set as 'Pending'.

**Comment by wow-mania** [comment]
This quest works. As per video you have to fly your own mount.
The spacebar issue is a vehicle quirk that cannot be fixed.
So if the quest is completable just close it please.

**Comment by GMLucetta** [comment]
Quest is easily doable so closing the issue.
