### ISSUE TITLE
[Core] Random resource nodes aren't

### ISSUE THREAD

**Issue by ChemicalSerenity** [wow-mania/Redemption#27]
This is something I've noticed over the last couple weeks - when a resource node (I've specifically noticed mining nodes, but fishing seems to do it as well, and I suspect other types would) spawns, it will always spawn with the same "type". For instance, a mining node in Icecrown has the following probabilites: Saronite 75%, Rich Saronite 15%, Titanium 10%... but after a restart, once a node has been "decided" as being saro, rich saro or titanium, it will continue to be that type exclusively until the next server restart. As mentioned, the same seems to happen with fishing, and likely others.

I don't know if this is desired behaviour. Optimally, each node should be "in play", and each spawn should be decided from the probabilities and a fix should be implemented for that. Alternately, and this is the way retail has done it (if I recall correctly from back in the day), a short daily reset would re-scramble the node collection so things would change up every day.

To reproduce:

1. Restart server
2. Find a resource node
3. Harvest the node
4. Wait for the node to respawn
5. Notice that the node is identical to the last one harvested
6. if(!BORED && !CONVINCED), go to step 2

**Comment by ChemicalSerenity** [comment]
Did a little extra testing on this. After today's unscheduled downtime, I decided to track the titanium nodes exclusively in Stormwind and Icecrown, and did a tight loop mining them. Most of the time, they respawned titanium, but every now and then one of the nodes would respawn as a saronite. So whatever's happening, it's not a case of always-spawn-as-the-same, it's just really really persistent.

**Comment by fvicaria** [comment]
GridUnload = 0 solved this.
