### ISSUE TITLE
[Quest] Mutiny on the Mercy

### ISSUE THREAD

**Issue by Calebrimbor** [wow-mania/Redemption#270]
http://www.wow-mania.com/armory/?quest=11527

For this quest you'll need to gather 5 Barrel's of Blasting Powder(http://www.wow-mania.com/armory/?item=34387) from the Mutinous Sea Dogs(http://www.wow-mania.com/armory/?npc=25026).

Quest works but definitely not as intended. The respawn time some of the Mutinous Sea Dogs in the hold of the ship is ridiculous long. 4 of them respawns normally. The other ones not, you'll have to wait way to long to get your last Barrel if someone did the quest right before you.

**Comment by Marvin023** [comment]
this quest is still not working. no sea dogs or barrels are spawning.

**Comment by Feuerwiesel** [comment]
> this quest is still not working. no sea dogs or barrels are spawning.

same here

**Comment by Kitzunu** [comment]
Works. 
They are spawned on the stationary ships too, but on the moving ones they fall through.
