### ISSUE TITLE
[Quest] The Valiant's Challenge (part 2)

### ISSUE THREAD

**Issue by Calebrimbor** [wow-mania/Redemption#272]
http://www.wow-mania.com/armory/?quest=13713

For this quest you'll need to talk with Squire Danny(http://www.wow-mania.com/armory/?npc=33518) to summon a and defeat a Argent Champion(http://www.wow-mania.com/armory/?npc=33708).

You can't talk with Squire Danny

**Comment by Rushor** [comment]
fixed?

**Comment by wow-mania** [comment]
Yes. I had to change the credit spell to kill monster credit I also had to do a small hack and award it to the closest player.
