### ISSUE TITLE
Character creation error

### ISSUE THREAD

**Issue by Asincine** [wow-mania/Redemption#276]
As of the WoD models being put into the game the barber shop hairstyles are now in the character creator. When people select these hairstyles and try and make a character they get a message reading "error creating character".

**Comment by MrNorrell** [comment]
Multiple people unable to create characters for this reason.

**Comment by fvicaria** [comment]
Not a bug. This is an issue with the client. You started the game before patch completed downloading.
Delete cache and the 2 patch files: patch-W and patch-enGB-W and restart the launcher and wait for it to finish the download.
