### ISSUE TITLE
[instance] Ruby Sanctum  (Shadow Orb) possible malfunction

### ISSUE THREAD

**Issue by gmadaman00** [wow-mania/Redemption#28]
On 04/09/2016 at approximately 20:00 server time, I observed a 25 man normal encounter. The mechanic was  originally structured that  Shadow Orbs (2 in normal mode | 4 in heroic mode) rotate in a clockwise circular motion on opposite sides of the fight area. They are designed to activate a beam (a.k.a cutter) every 20 seconds and remain active for 10 seconds, then deactivate for 10 seconds.ect.

While I was invisible with GM mode "On",  I observed one of the two Shadow Orbs did not rotate as designed, but rather remained stationary throughout both 2nd and 3rd phases of the encounter. I was also able to time the duration in between Cutters being active, and I was a steady 16 seconds instead of 10.    This resulted in the cutters only effecting a very minimal portion of the fight area making them (at times) a non-issue to the raid group.

It is possible that any discrepancies I observed, were due to my GM Mode being "on"

Thank you,   Adaman

**Comment by Kalasbyxan** [comment]
See no issue with the Shadow Orbs on 25 man nm and 25 man hc. Also timed cutter to 10 seconds. Perhaps this was a single occasion issue. Will close and investigate anew if situation rises again.
