### ISSUE TITLE
[Quest] Basic Chemistry (13279, 13295)

### ISSUE THREAD

**Issue by ChemicalSerenity** [wow-mania/Redemption#28]
Not all waves spawn. After pouring the mixture into the cauldron, only the first two waves appear, then the quest stalls.

To reproduce:

- Pour mixture into cauldron
- Kill slimes
- Wait for 2nd wave
- Kill more slimes and a ghoul
- Wait for 3rd wave that never comes

**Comment by fvicaria** [comment]
http://www.wowhead.com/quest=13279/basic-chemistry
http://www.wowhead.com/item=44010/pustulant-spinal-fluid

Couldron id: 193580

**Comment by fvicaria** [comment]
THe exact location is a bit tricky but it does work. I few players have done it.

**Comment by AielloA** [comment]
The second wave didn't even spawn when my friend and I did it. Just the first Ghoul and two slimes.
