### ISSUE TITLE
[Arena] The Dalaran Sewers

### ISSUE THREAD

**Issue by Muffinbutton13** [wow-mania/Redemption#281]
The Dalaran Sewers arena should have a "knock off" effect to players a few seconds after the arena starts, and at the moment we don't have that. There's players who will even stay out back in their sewer starting spot and not come down out of spite for losing. 

This is also very annoying as people could even go afk (even if not on purpose) and stay up there, without any way of reaching them.

**Comment by Calebrimbor** [comment]
Issue added to the BugTracker for testing. Thank you for your report. 
@ Testers: Please add all details such as links etc.

**Comment by Calebrimbor** [comment]
Status BugTracker set as 'Pending'.

**Comment by wow-mania** [comment]
I looked into this and there is nothing special or different to the other arenas. The effect is equal to both sides. Changing it would add nothing.

**Comment by Calebrimbor** [comment]
Removed it from the BugTracker
