### ISSUE TITLE
Betrayel [Quest]

### ISSUE THREAD

**Issue by xXDzepniXx** [wow-mania/Redemption#282]
The issue with this quest is that the boss Drakarri or Drakari (not sure which) is bugged, you can start the quest and go to him, the issue is that there's a gas thing, in case you fall off the platform where he teleports you. Although, the gas is everywhere even on the platform which is not suppose to be there, you can check out the boss fight on youtube, the place where the player is spawned is where the gas is not suppose to be located, and the guess does 1200 damage, which kills the player very quickly, and it does it ever 1 second or so. Thus making the quest impossible.

I posted this last time, but something weird happened, got placed in some website with like a different language, wasn't the wow-mania.com that I know of, just reposting for safety.

**Comment by fvicaria** [comment]
Fixed. Should be in for the next release.
