### ISSUE TITLE
The Amphitheater of Anguish

### ISSUE THREAD

**Issue by xXDzepniXx** [wow-mania/Redemption#283]
Everything is fine, the quests work well, the only issue is sharing it with members in the party. I had to do all the quests with my party members 3 times, by this I mean, first quest of the chain, 3 times, second, 3 times, third quest 3 times, and on and on. This was very annoying and time consuming. The quest appears to do its job, when a player starts it in the party, you will get a notification if you want to do it with the party members, when you click accept or yes, the quest does not appear in your quest book and when you do the boss, it does not work for you, only for the person who started the fight. So if a person in your group starts the fight and you don't have the quest before hand (and if you do have it for some magical reason, it still completes only for the person who started the fight) it will show whether you want to accept the share (it does it automatically) and if you click accept, it does not work. That's basically it, the share doesn't work.

**Comment by fvicaria** [comment]
This is a known issue. Duplicate #63
