### ISSUE TITLE
[Quest] We have the Power - Horde

### ISSUE THREAD

**Issue by GMLucetta** [wow-mania/Redemption#284]
http://www.wow-mania.com/armory/?quest=12197

Players have to kill Rune-Smith Durar (http://www.wow-mania.com/armory/?npc=26409) and Rune-Smith Kathorn (http://www.wow-mania.com/armory/?npc=26410) in order to receive Durar's Power Cell (http://www.wow-mania.com/armory/?item=36857) and Kathorn's Power cell (http://www.wow-mania.com/armory/?item=36858)

The item does not always drop on the first try of killing both NPCs leading players to report the quest as bugged. This is not working as intended as it is supposed to be a 100% drop rate.

**Comment by wow-mania** [comment]
Drop rate is 65%.
