### ISSUE TITLE
[Quest] Ursius of the Shardtooth

### ISSUE THREAD

**Issue by GMLucetta** [wow-mania/Redemption#286]
http://www.wow-mania.com/armory/?quest=5054

Players have to go to Winterspring to kill Ursius (http://www.wow-mania.com/armory/?npc=10806)

The bear is not visible on the map and is hiding inside the mountain making him unkillable. Therefore the quest is not working as intended.

**Comment by Emcitementz** [comment]
Working properly on dev, needs testing on live.
