### ISSUE TITLE
[Quest] The Air Stands Still

### ISSUE THREAD

**Issue by Calebrimbor** [wow-mania/Redemption#287]
http://www.wow-mania.com/armory/?quest=13125

For this quest you'll need to to kill Salranax the Flesh Render(http://www.wow-mania.com/armory/?npc=30829), Underking Talonox(http://www.wow-mania.com/armory/?npc=30830) and High Priest Yath'amon(http://www.wow-mania.com/armory/?npc=30831) making use of the War Horn of Acherus(http://www.wow-mania.com/armory/?item=43206) provided by the quest giver.

The War Horn of Acherus sometimes need to be used a couple of times to summon the NPC's. The Horn does sound, but nothing happens. It's not spot on every time, but between killing the mobs I've confirmed this it malfunction. Quest is doable but needs some tweaks.

**Comment by wow-mania** [comment]
Fixed for next update.

**Comment by Calebrimbor** [comment]
Status BugTracker set as 'Pending'.

**Comment by Calebrimbor** [comment]
Fix is confirmed. Status on BugTracker set as 'Fixed'.
