### ISSUE TITLE
[Raiding] ICC10 Heroic - Valithria Dreamwalker bugs out after wiping

### ISSUE THREAD

**Issue by Ainpat** [wow-mania/Redemption#288]
Necropolis has been progressing in ICC10 HC very quickly and we faced this bug 2 times already when encountering the Heroic Mode version of Valithria Dreamwalker.

The Valithria encounter spawns minions for the raid to kill during the fight. After not managing to kill Valithria the first try, resulting in a wipe, the minions dont stop spawning though. Valithria does reset, but the minions of the encounter still keep spawning, and they keep becoming more and more. Only after a few minutes there will be so many Blazing Skeletons (which cast an area of effect fire spell that affects the player in all of ICC) that anybody entering the raid will take lethal damage and just die again. The encounter basically becomes undoable unless a GM heals Valithria to full HP, thus ending the encounter.

Norrell has already helped out Necropolis on this last week and should be able to confirm this issue, he used some weird "Stoneskin" Spell to heal her to full health after about 10 minutes.

**Comment by fvicaria** [comment]
A first attempt to fix this. I will push it Friday.
