### ISSUE TITLE
[Raiding] ICC10 (Normal and Heroic) - Sindragosa's

### ISSUE THREAD

**Issue by Ainpat** [wow-mania/Redemption#289]
Multiple GMs should be aware of this as both raid groups of Necropolis have required help with this boss before.

The first phase of Sindragosa works perfectly fine now (thanks for fixing that, Janitor), but in the second phase, she will usually go wild on casting Icy Veins (Extend tendrils of frigid wind to pull all nearby enemies to the caster.) and Blistering Cold (Deals 30,000 Frost damage to enemies within 25 yards. 5 sec cast. 45,000 damage on Heroic). This massively screws over all of the raids cause nobody gets any time to cast healing spells and this usually leads to a wipe. I've never seen multipler casts of this combination in succession in any Boss Video or other server, thus we from Necropolis think it is bugged.

GMs so far handled this by giving us the debuff you get while encased in ice in this encounter, which gives you a handy 75% less damage taken from frost damage.

**Comment by fvicaria** [comment]
Should be fixed. I will try to push this this Friday.
