### ISSUE TITLE
[Quest] Mending Fences 

### ISSUE THREAD

**Issue by GMLucetta** [wow-mania/Redemption#289]
http://www.wow-mania.com/armory/?quest=12915

Players have to pick up Granite Boulder (http://www.wow-mania.com/armory/?item=41506) and use Thorim's Charm of Earth (http://www.wow-mania.com/armory/?item=41505) to throw the boulder at 5 Stormforged Iron Giants (http://www.wow-mania.com/armory/?npc=29375) and then use the boulder and charm again to attack Fjorn (http://www.wow-mania.com/armory/?npc=29503)

The Stormforged Iron Giants are killable using the above method but when using the charm on Fjorn it says "Invalid target" Meaning that the quest cannot be completed.

**Comment by wow-mania** [comment]
This quest works fine after the update. Elysium is updated. Redemption tomorrow.

**Comment by Calebrimbor** [comment]
Not fixed. Fjorn is still a 'Invalid target' when you use Granite Boulder. Also, despite the fact I have done all the prequests I had to unaura meself several times to be able to see the Stormforged Iron Giants, Boulders and Fjorn.

**Comment by Calebrimbor** [comment]
Fix is confirmed. Status on BugTracker set as 'Fixed'.
