### ISSUE TITLE
Quest in Icecrown. 

### ISSUE THREAD

**Issue by Bellyh** [wow-mania/Redemption#29]
The quests [Leading the Charge] and [Watts my target] says that you will receive a "bomber" to help you complete the quests, but said "bomber" does not arrive. After speaking to the NPC Karen No, you get a "buff" that says you're waiting for a bomber. I waited 20 mins last night and no bomber arrived. I tried abandoning the quests and pick them up again, relog, reload, but nothing helped.

**Comment by Calebrimbor** [comment]
Double issue, still on the list
