### ISSUE TITLE
[Talent] Desecration

### ISSUE THREAD

**Issue by mocmihai** [wow-mania/Redemption#293]
Unholy Death Knight's pvp talent "Desecration" doesn't work at all.Please fix

**Comment by genasi** [comment]
Since this is almost useless and doesnt look like the original poster even read the "how to report"-wiki I will add a link to the talent/spell..
desecration: http://wotlk.openwow.com/spell=55666

And for OP: https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue

**Comment by Calebrimbor** [comment]
Issue added on the BugTracker for testing. Thank you for your report.

**Comment by Calebrimbor** [comment]
Status BugTracker set as 'Pending'.

**Comment by Calebrimbor** [comment]
Status on BugTracker set as 'Fixed'.
