### ISSUE TITLE
[Boss] Valithria Dreamwalker 10 man HC

### ISSUE THREAD

**Issue by MissShiz** [wow-mania/Redemption#293]
Encountered problems two weeks in a row on Valithria Dreamwalker in 10 man heroic (http://wow-mania.com/armory/?npc=36789) when she does not reset properly after a wipe. She will despawn and respawn, but at the respawn, the adds will be stacked behind the closed gates and then come through the gate all at once at first but then also keep spawning and coming. This means when we start the fight, adds are there and sometimes Blazing Skeletons (http://wow-mania.com/armory/?npc=36791#summoned-by) already stood there for a while killing everyone that portals up to the spire.

After a wipe and despawn, Valithria Dreamwalker should spawn along with 4 adds surrounding her, no adds behind the gates and then adds spawn on a timer, one kind at a time.

**Comment by fvicaria** [comment]
Duplicate #288
