### ISSUE TITLE
Arena door doesn't open in blackrock spire

### ISSUE THREAD

**Issue by JeanMabru** [wow-mania/Redemption#295]
In blackrock spire, on the way to general drakksomthing you need to fight in the arena. The arena (kinda) works fine. (by kinda I mean that the mobs don't always spawn but the event still goes on). 
Once the last wave arrives, a mob on the back of a dragon arrives, and you need to kill him.
The issue comes from the fact that once dead, the door that gives access to the general doesn't open and you're just stuck in the arena. Norrell opened up the door for me and told me to flag this.

Thanks for the read :)

**Comment by wow-mania** [comment]
Duplicate #17
