### ISSUE TITLE
[Quest] Springing the Trap

### ISSUE THREAD

**Issue by GMLucetta** [wow-mania/Redemption#297]
http://www.wow-mania.com/armory/?quest=11969

Raelorasz (http://www.wow-mania.com/armory/?npc=26117) requires the player to use Raelorasz' Spark (http://www.wow-mania.com/armory/?item=44950) at the signal fire on Coldarra. This will summon Keristrasza (http://www.wow-mania.com/armory/?npc=34310) and allow the trapping of Malygos. 

The quest works through all the cutscenes and the player flying on Keristrasza, Malygos appears as intended but after he's frozen Keristrasza both NPCs despawn with no quest complete being given to the player. 

This is not working as intended.

**Comment by wow-mania** [comment]
Stay close to Keristrasza  at all times. Did the quest and it works.

**Comment by GMLucetta** [comment]
The quest works through all the cutscenes and the player flying on Keristrasza, Malygos appears as intended but after he's frozen Keristrasza both NPCs despawn with no quest complete being given to the player.

I stood directly under Keristrasza at all times where possible and still didn't get the complete on the quest. 

This is not working as intended.

**Comment by wow-mania** [comment]
try focusing her. I have done it multiple times and although most of them worked I also had a case where credit was not given. I will try to change the way credit is given to improve it.

**Comment by Calebrimbor** [comment]
Quest has been fixed. It seems when you keep standing near to Keristrasza you won't get the objective. She does say: Flee! When you flee it seems to give you the objective. I tried several times and it worked

**Comment by Calebrimbor** [comment]
Status BugTracker set as 'Pending'.
