### ISSUE TITLE
[Quest] Suntara Stones

### ISSUE THREAD

**Issue by GMLucetta** [wow-mania/Redemption#299]
http://www.wow-mania.com/armory/?quest=3367

Players have to speak to Dorius Stonetender (http://www.wow-mania.com/armory/?npc=8284) and then escort him to a point in Searing Gorge where he is shot dead. 

Speaking to him to accept the quest, adds the quest to the log but Dorius remains lying on the ground. This is not working as intended.

**Comment by wow-mania** [comment]
Fixed for next update or crash. :)
