### ISSUE TITLE
[Quest] Army of the Damned (13236, 13395)

### ISSUE THREAD

**Issue by ChemicalSerenity** [wow-mania/Redemption#30]
If you don't target an enemy with your "Death Storm" ability, the ability hits you instead, likely killing you unless you have over 20k HP or a lot of shadow resistance. The ability is also non-interruptable, so if you trigger it without a target, you get to enjoy a second or two of "Oh shit..." before your death.

Effect may also work as a "bounce back", if you're standing too close to an enemy. Jumps from it to you, similar results.

Repro Steps:

- Ask Matias to show you Arthas' history
- Fumble a little bit in targeting and don't actually click on an enemy
- Trigger Death Storm
- Panic for a short period while the spell casts and you realize you haven't targeted anyone
- Die horribly
- Fly a long way to do it again
- When you finally pull your head out of your ass and do it right, fly somewhere else to repair armor.

**Comment by fvicaria** [comment]
This should be partly fixed on the next build. Please retest.

**Comment by Daethalion** [comment]
I attempted this quest and met with the same result.  Death Storm always chains back to caster for 25,000 damage.  Also, you can't attack the mobs with your melee ability - it tells you there is no target.

**Comment by fvicaria** [comment]
Should be fixed now.

**Comment by fvicaria** [comment]
```
SET @DEATHSTORM := 58912;
SET @SOULCLEAVE := 58913;

DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` = 13 AND `SourceEntry` = @DEATHSTORM;
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` = 17 AND `SourceEntry` = @SOULCLEAVE;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`)
VALUES (13, 1, @DEATHSTORM, 0, 0, 33, 0, 1, 1, 0, 1, 0, 0, '', 'Deathstorm cannot hit self'),
      (17, 0, @SOULCLEAVE, 0, 0, 32, 0, 8, 0, 0, 0, 0, 0, '', 'Soul Cleave can target units');
```

**Comment by Rushor** [comment]
because of EffectChainTarget = 12, you will still hit yourself with the ability :D

**Comment by fvicaria** [comment]
I checked your suggestion on TC. I looks like there something not quite right with the parameter:

```
Spell `58912` Effect `Index: EFFECT_0 Target: 6` of script `spell_icecrown_deathstorm` did not match  dbc effect data - handler bound to hook `OnObjectAreaTargetSelect` of SpellScript won't be executed
```

**Comment by Rushor** [comment]
change TARGET_UNIT_TARGET_ENEMY to TARGET_UNIT_TARGET_ANY in the spellscript
