### ISSUE TITLE
Latherworking trainer not teaching Light Leather recipe

### ISSUE THREAD

**Issue by meesterexx** [wow-mania/Redemption#30]
Learned leatherworking from the trainer just outside Darnassus and the recipe for making Light Leather form ruined leather scraps was missing. Unlearned LW there and went to the trainer in Craftsman terrace and still light leather not taught.

Unlearned again, logged out, cleared cache and relearned LW, still no Light Leather.

 Should be available from level 1 by default from trainer.

**Comment by wow-mania** [comment]
Right click on stacks of 5 leather scraps at the time to convert them.
Do do click on 20 or any other number. Separate them into 5s.
