### ISSUE TITLE
[NPC] Tallhorn Stag

### ISSUE THREAD

**Issue by GMLucetta** [wow-mania/Redemption#300]
http://www.wow-mania.com/armory/?npc=26363

When you use a Freezing arrow (http://www.wow-mania.com/armory/?spell=60192) or Freezing Trap (http://www.wow-mania.com/armory/?spell=14311) on the stag it freezes them in place as intended. However when the trap/arrow timer breaks the stag does not attack the player. 

We have tested this extensively on multiple types of mobs and is only an issue on the Tallhorn Stags.

**Comment by wow-mania** [comment]
Should be fixed on next update (Wednesday 31/08/16)
