### ISSUE TITLE
[Quest] The Black Knight's Fall

### ISSUE THREAD

**Issue by Calebrimbor** [wow-mania/Redemption#301]
http://www.wow-mania.com/armory/?quest=13664

For this quest you'll need to defeat The Black Knight(http://www.wow-mania.com/armory/?npc=33785) while using your Argent Lance(http://www.wow-mania.com/armory/?item=46106) and mounted on a Argent Warhorse(http://www.wow-mania.com/armory/?npc=33863). You could summon The Black Knight when talking to Squire Cavin(http://www.wow-mania.com/armory/?npc=33522).

The Black Knight will evade when you try to defeat him on the warhorse. You could kill him when engaging normal combat. The quest is doable but definitely not working as intended.

**Comment by wow-mania** [comment]
Fixed for next Wednesday. Please confirm.

**Comment by Calebrimbor** [comment]
Fix is confirmed. Status on BugTracker set as 'Fixed'.
