### ISSUE TITLE
[NPC]

### ISSUE THREAD

**Issue by dimman321** [wow-mania/Redemption#302]
Hi there!
This happened to me all the time when i fought ghouls or any undead npcs. I got 3-4 of same desease slowing me down up to 132% (Contagion Rot) I dont think it supposed to get stacked like that but instead renew the duration time. I mean with same logic (im a warrior) i should be able to rend mobs 10000x times and dot would allso stack.... dont think so, right?

**Comment by fvicaria** [comment]
Core issue. Being looked at.
