### ISSUE TITLE
[Quest] Cleansing of the Orb of Orahil

### ISSUE THREAD

**Issue by allytili** [wow-mania/Redemption#303]
This quest needs some adjustment.
The demon to be killed is way too hard for the warlock in intended level. But so it was in retail, almost. The biggest difference is that when the player's warlock dies the demon gains full health, something it didn't do in retail. If you can kill the demon with 2-3 tries in that 3 minute time limit, that should be sufficient. But that would require that the demon does not regain its health.

**Comment by wow-mania** [comment]
All NDC's gain full health when they go OOC. I will try to adjust the damage a bit.
