### ISSUE TITLE
[Quest] Bloody Breakout

### ISSUE THREAD

**Issue by GMLucetta** [wow-mania/Redemption#303]
http://www.wow-mania.com/armory/?quest=12727

Koltira Deathweaver (http://www.wow-mania.com/armory/?npc=28912) gives you the quest to kill High Inquisitor Valroth (http://www.wow-mania.com/armory/?npc=29001) and take his head (http://www.wow-mania.com/armory/?item=39510).

Koltira is supposed to use an anti-magic shell (http://www.wow-mania.com/armory/?spell=31662) to help you fight the High Inquisitor. Which the player is supposed to stand inside during the fight, this is not working as he doesn't use the shell and players are killed.

This needs tweaking so that he does cast the spell.

**Comment by wow-mania** [comment]
Fixed for next update.

**Comment by Calebrimbor** [comment]
Status BugTracker set as 'Pending'.

**Comment by Calebrimbor** [comment]
I don't know if it's a phasing issue. But the High Inquisitor Valroth is only visible for me in GM mode. Did all the DK quests up to this one. Zoned out zoned in, no avail, unaura nothing works. Could someone else test this one to determine if it's a error from my side?

**Comment by wow-mania** [comment]
Yes it's a phase thing. Normally you would be in phaze = 4

**Comment by Calebrimbor** [comment]
Status on BugTracker set as 'Fixed'.
