### ISSUE TITLE
[Quest] Cave Medicine

### ISSUE THREAD

**Issue by Calebrimbor** [wow-mania/Redemption#304]
http://www.wow-mania.com/armory/?quest=13055

For this quest you'll need to obtain 1 Jormungar Toxin Gland(http://www.wow-mania.com/armory/?item=42927) and 8 Cave Mushrooms(http://www.wow-mania.com/armory/?item=42926). 

The Toxin Gland does not drop from any Jormungar in the cave.

**Comment by poserbiker** [comment]
I've done research on this one, The loot is in the DB but drop rate is super low like 5% is the highest from only one mob. This is also shown here https://www.youtube.com/watch?v=7zMqTeJCiLE in the comments "the drop rate is too small -_- ive killed 50 of these worms and still did not get the item.﻿" I've added what was shown in wowhead on some extra mobs that show it drops but again they are about .003%.

**Comment by Calebrimbor** [comment]
Fix is confirmed. Status on BugTracker set as 'Fixed'.
