### ISSUE TITLE
[Quest] Gambling Debt

### ISSUE THREAD

**Issue by Calebrimbor** [wow-mania/Redemption#306]
http://www.wow-mania.com/armory/?quest=11464

For this quest you'll need to collect "Silvermoon" Harry's Debt(http://www.wow-mania.com/armory/?item=34115) from Silvermoon Harry(http://www.wow-mania.com/armory/?npc=24539). 

Silvermoon Harry does not give you anything after you've ended a fight.

**Comment by wow-mania** [comment]
Fixed for next Wednesday. Please confirm.

**Comment by Calebrimbor** [comment]
Status BugTracker set as 'Pending'.

**Comment by Calebrimbor** [comment]
Fix is confirmed. Status on BugTracker set as 'Fixed'.
