### ISSUE TITLE
[NPC] Spirit Healer

### ISSUE THREAD

**Issue by Calebrimbor** [wow-mania/Redemption#307]
http://www.wow-mania.com/armory/?npc=32537

None of the Spirit Healers in Darkshore(http://www.wow-mania.com/armory/?zone=148) are not available for Horde. You end up as a spirit in Ashenvale(http://www.wow-mania.com/armory/?zone=331), Nightsong Woods if you die in Darkshore. That's extremely far away. Even though it's Alliance Territory there should be at least 1 available Spirit Healer for both factions. Considering the size of the map there should be 2.

**Comment by wow-mania** [comment]
Fixed for next Wednesday. Please confirm.

**Comment by Calebrimbor** [comment]
Tested the fix, you do not spawn at Spirit Healer but you can revive at the spot you died. Label set to 'Tweaking'.

**Comment by Calebrimbor** [comment]
Fix is confirmed. Status on BugTracker set as 'Fixed'.
