### ISSUE TITLE
[Vote Points] Only six maniac points are assigned

### ISSUE THREAD

**Issue by glspisso** [wow-mania/Redemption#308]
Voting is advertised as yielding up to 7 maniac points, but I never got more then six, despite voting in all the sites.

**Comment by wow-mania** [comment]
Votinf works. The variation has to be with voting site returning or not successful vote message. Check FAQ.

**Comment by glspisso** [comment]
All voting site report success. Every single one
Il giorno 04/set/2016 10:13, "Janitor" <notifications@github.com> ha
scritto:

**Comment by wow-mania** [comment]
The page is out of date. This has now been fixed the maximum is 6 now as the last 2 sites do not have a postback mechanism.
