### ISSUE TITLE
[Raid] Trial of the Crusader 10/25 Man IceHowl

### ISSUE THREAD

**Issue by GMSunShield** [wow-mania/Redemption#309]
Trial of the Crusader 10Man and 25man
Boss: IceHowl http://www.wow-mania.com/armory/?npc=34797

Normal play:  Icehowl does a Raid stun http://www.wowhead.com/spell=66683/massive-crash . and then should do a small jump back and face a random member in the raid and do http://www.wowhead.com/spell=66734/trample.
If Icehowl does not hit any player he smashes in to the wall and gets a debuff http://www.wowhead.com/spell=66758/staggered-daze

Problem: Icehowl does http://www.wowhead.com/spell=66683/massive-crash and jumps back in to the wall   https://s21.postimg.org/vgmswjyrb/Wo_WScrn_Shot_090416_053800.jpg Witch players then must normal melee / White Damage hit him if a player  changes  targets  they cant go back to hitting him and the boss cant be done

Video of fight: https://youtu.be/oEcCItDmIz0?t=285

**Comment by wow-mania** [comment]
Fixed for next Wednesday. Please confirm.

**Comment by wow-mania** [comment]
Sunshield confirmed it fixed yesterday.

**Comment by Calebrimbor** [comment]
Status on BugTracker set as 'Fixed'.
