### ISSUE TITLE
[Quest] Return of the High Chief

### ISSUE THREAD

**Issue by Kalasbyxan** [wow-mania/Redemption#31]
The quest (http://wow-mania.com/armory/?quest=12069) is completed by killing a NPC and looting an item. The item (http://wow-mania.com/armory/?item=36759) is unlootable.

**Comment by poserbiker** [comment]
This one states the object is already in use not sure if this is a scripting issue or a gobject issue. TC has a "Fix" from 2014 but I don't think it was tested cause I used it and same result. Error in console shows "Table `event_scripts` has invalid gameobject (GUID: 21202) in SCRIPT_COMMAND_RESPAWN_GAMEOBJECT for script id 4845". Might rewrite script in SAI and see if we get a different result.

**Comment by poserbiker** [comment]
![return of the high chief](https://cloud.githubusercontent.com/assets/896742/18339386/196a1a4c-7554-11e6-9b6b-12605f418a25.PNG)

Looks like I was able to get it fixed pending test!
