### ISSUE TITLE
[Quest] Volatility (13239, 13261)

### ISSUE THREAD

**Issue by ChemicalSerenity** [wow-mania/Redemption#31]
You can create the dummies by collecting the necessary materials (armor and bones and so on), but when you spawn the dummy and the ice wyrm takes it they don't asplode and you get no credit for them.

Repro Steps:

- Collect materials
- Fashion dummy
- Place dummy
- Watch wyrm snatch dummy and fly off
- Wave goodbye with a somber face, thinking of all the cool places the dummy will visit, like a gothic travelocity gnome.

**Comment by fvicaria** [comment]
Fixed
