### ISSUE TITLE
[Quest] High Commander Halford Wyrmbane

### ISSUE THREAD

**Issue by genasi** [wow-mania/Redemption#310]
The quest (http://wotlk.openwow.com/quest=12174) have you delivering a missive (http://wotlk.openwow.com/item=37003) to High Commander Halford Wyrmbane (http://wotlk.openwow.com/npc=27136).
To deliver the missive you are supposed to be given a hippogryph ride from Star's Rest to Wintergarde (http://wotlk.openwow.com/spell=48013) by Palena Silvercloud (http://wotlk.openwow.com/npc=26881).

This doesnt happen, so players are forced to make their own way to Wintergarde.

**Comment by Calebrimbor** [comment]
Issue added on the BugTracker for testing. Thank you for your report

**Comment by wow-mania** [comment]
Fixed for next Wednesday

**Comment by Calebrimbor** [comment]
Status BugTracker set as 'Pending'.

**Comment by Calebrimbor** [comment]
Fix is confirmed. Status on BugTracker set as 'Fixed'.
