### ISSUE TITLE
[Raid] Blackwing Lair Nefarian

### ISSUE THREAD

**Issue by GMSunShield** [wow-mania/Redemption#311]
[Raid] Blackwing Lair    http://www.wow-mania.com/armory/?achievement=685
Boss: Nefarian  http://www.wow-mania.com/armory/?npc=11583

When you start the fight with Nefarian. He will have a shield on you can't do damage to him. Players have to fight his adds he summons  after X amount of time Nefarian will then go in to phase 2 where he comes back as a dragon and fly in to the room >Nefarian is Landing<, Tanks then have to pick up Nefarian in dragon form and dps him down well adds are being spawned.
>https://s14.postimg.org/to8t3zk2p/image.jpg
>^^^^^^^^Nefarian's Balcony^^^^^^^^^

 >Issue: When Nefarian changes in to dragon form he does not target anyone and will not land he will then despawn after 20secs and does not come back to fight again making this fight undoable.
^^Sometimes he will respawn but under his chair do SHIFT V should show his health bar^^

 >Work around: When Nefarian is in dragon form if a player uses a long range spell/attack to hit him he will aggro and come in to the room and you can fight him and kill him.

**Comment by Calebrimbor** [comment]
Status BugTracker set as 'Pending'.

**Comment by Calebrimbor** [comment]
Status on BugTracker set as 'Fixed'.
