### ISSUE TITLE
[Quest] Loramus

### ISSUE THREAD

**Issue by Calebrimbor** [wow-mania/Redemption#316]
http://www.wow-mania.com/armory/?quest=3141

For this quest you'll need to listen to Loramus Thalipedes(http://www.wow-mania.com/armory/?npc=7783) his story. 

He doesn't tell you anything, button 'Continue' is greyed out.

**Comment by wow-mania** [comment]
Fixed for next Wednesday. Please confirm.

**Comment by Calebrimbor** [comment]
Status BugTracker set as 'Pending'.

**Comment by Calebrimbor** [comment]
Status on BugTracker set as 'Fixed'.
