### ISSUE TITLE
(NPC) Farseer Nobundo

### ISSUE THREAD

**Issue by GMLucetta** [wow-mania/Redemption#317]
http://www.wow-mania.com/armory/?npc=17204 Has managed to clone himself in the Exodar. He is visible both in GM mode and in player mode.

**Comment by GMLucetta** [comment]
Confirmed. I've managed to reproduce. Issue is labeled as 'Confirmed' on the Bug Tracker.

**Comment by wow-mania** [comment]
Fixed.

**Comment by Calebrimbor** [comment]
Status on BugTracker set as 'Fixed'.
