### ISSUE TITLE
The Plains of Nasam

### ISSUE THREAD

**Issue by Floopers** [wow-mania/Redemption#318]
This quest which is picked up in Borean Tundra called "The Plains of Nasam" is bugged. The enemies die too slowly and i think the hit ratio of the cannon is too small. This results in only killing 1 enemy after every 2 cannon shots. And since you're supposed to kill 100 enemies, it's not exactly efficient.

**Comment by fvicaria** [comment]
Works fine as is. Use saw and other spells.
