### ISSUE TITLE
[QUEST] Bury Those Cockroaches!

### ISSUE THREAD

**Issue by Floopers** [wow-mania/Redemption#319]
Two sinkholes cannot be completed. This quest is picked up in borean Tundra and the quest is called "Bury Those Cockroaches!"

**Comment by mariogotze** [comment]
Absolutly working.

**Comment by Iambugged** [comment]
The problem is that the bomb is bugged so that it's a npc that charges to attack mobs around it, and when it moves out of the sinkhole and explodes while not in the correct spot it doesn't give you the kill credit.
