### ISSUE TITLE
[Quest](s) DK newbie chain giver marks "?" disappear due to levelling

### ISSUE THREAD

**Issue by ChemicalSerenity** [wow-mania/Redemption#32]
Due to the x2 XP gains, it's possible (indeed, inevitable) that a newbie DK will grow faster than the quest givers marks will appear. This can cause a lot of confusion for people who are either unfamiliar with the DK newbie area, or who haven't played in a long time and forget that sort of thing can happen. The fix is very simple, just bump the quest levels with this query:

 UPDATE quest_templates SET level=60 WHERE RequiredClasses=32 AND level=55;

The only RC=32 L=55 quests in the db are the DK newb quests, updating the quest level to 60 (but leaving minlevel alone) should resolve the problem of disappearing "?"s.

Repro Steps:

- Roll a new DK
- Follow the quest chain faithfully
- Get confused and lost after hitting level 60 because all the ?'s disappear
- Eventually find them
- Grumble a bit
- Finish those
- Wait for approximately 17 minutes while NPCs talk shit to each other before and after a big battle, like a medieval Dragon Ball Z episode.
- Rejoice that you're finally well the fuck gone from the DK newbie zone

**Comment by fvicaria** [comment]
Fixed for Release 9.
