### ISSUE TITLE
[Quest] The Grand Melee

### ISSUE THREAD

**Issue by Kalasbyxan** [wow-mania/Redemption#32]
The quest (http://wow-mania.com/armory/?search=the+grand+melee) has a reset issue with the NPC attacked. Confirmed with players fighting for Undercity (http://wow-mania.com/armory/?quest=13782) but might be for all factions or more than one. 

When the mounted player attacks the NPCs reset after the first attack, making them instant 100% hp and unkillable. This is confirmed for all Valiants in the Horde Area.

**Comment by genasi** [comment]
I can confirm the same for Alliance. You can finish the quest if you attack the npc unmounted, but that is kinda hazardeous as they do considerable damage.

**Comment by Calebrimbor** [comment]
The issue is for all factions. The NPC just keeps evading. Entering the combat normal, without a mount will work. It's doable but not working as intended.
