### ISSUE TITLE
[Quest] Army of the Damned

### ISSUE THREAD

**Issue by Calebrimbor** [wow-mania/Redemption#321]
http://www.wow-mania.com/armory/?quest=13395
http://www.wow-mania.com/armory/?quest=13236

For this quest you'll need to raise an army of 100 Ghoulish Minions(http://www.wow-mania.com/armory/?npc=31329) while being transformed into Arthas.

This quest has 3 bugs. 1, raising the minions doesn't count for the objective, 2, Soul Cleave(ID 58913) does not work as you get the error 'No Target' and 3, The Lordaeron Footsoldiers(http://www.wow-mania.com/armory/?npc=31254) should be hostile, now they are neutral.

**Comment by Calebrimbor** [comment]
Labeled with 'Priority' since this quest is frequently reported.

**Comment by wow-mania** [comment]
OK this quest is now doable but Soul Cleave still does not work.
It will be marked as fixed as it doesn't look as it will ever get better than this.

It will take talking to Matthias a few times to re-transform you as you cannot kill the footsoldiers yourself.

**Comment by Calebrimbor** [comment]
Status BugTracker set as 'Pending'.

**Comment by Calebrimbor** [comment]
Fix is confirmed. Status on BugTracker set as 'Fixed'.

Although it's fixed to make it doable, I would still suggest to find a fix for Soul Cleave.
