### ISSUE TITLE
[Talent] Sacred Cleansing

### ISSUE THREAD

**Issue by Muffinbutton13** [wow-mania/Redemption#322]
I can't really speak for PvE environments, since it's not my cup of tea and it's more of a PvP talent, but at least in arenas Sacred Cleansing is definatly broken. 
As far as self targeting cleanse for the proc to occur on ourselves it appears to be pretty normal, but if I try cleansing a friend/partner, it almost never proc's. I'm sure it has actually proc'ed on him, so it's not completly broken, but as a Holy Paladin I look and cleanse my partner a lot, and for a 30% chance proc, it is so silly the amount of times it proc's on other targets. After so many fights I can say for sure it has a proc rate that would make those 1% low level effect trinkets and run for their money. It really is that low.

I almost never do more then 5 cleanses without it proccing at least once on me, although on other targets I spend whole games spam cleansing 80% of the time against dotting classes and most of the times, doesn't even proc once.

**Comment by Calebrimbor** [comment]
Issue added to the BugTracker for testing. Thank you for your report. 
@ Testers: Please add all details such as links etc.

**Comment by Calebrimbor** [comment]
status BugTracker set as 'Pending'.

**Comment by GMSunShield** [comment]
confirmed Fixed!
