### ISSUE TITLE
(Quest) Bury Those Cockroaches!

### ISSUE THREAD

**Issue by GMLucetta** [wow-mania/Redemption#324]
http://www.wow-mania.com/armory/?quest=11608

Players are given a Seaforium Depth Charge (http://www.wow-mania.com/armory/?item=34710) so they can blow up Nerub'ar Sinkhole (South)(http://www.wow-mania.com/armory/?npc=25402) Nerub'ar Sinkhole (East) (http://www.wow-mania.com/armory/?npc=25403) Nerub'ar Sinkhole (West)(http://www.wow-mania.com/armory/?npc=25404) Nerub'ar Sinkhole (North)(http://www.wow-mania.com/armory/?npc=25405)

When a player visits the location and uses the Seaforium Depth Charge the countdown and the explosion doesn't happen meaning the player cannot get credit or complete the quest. 

This is not working s intended.

**Comment by GMLucetta** [comment]
Confirmed. I've managed to reproduce. Issue is labeled as 'Confirmed' on the Bug Tracker.

**Comment by Kalasbyxan** [comment]
Previously, this was doable by walking around the sinkhole in small movements finding the trigger point. Means it's not working as intended, but doable.
