### ISSUE TITLE
[Quest] Kickin' Nass and Takin' Manes

### ISSUE THREAD

**Issue by Calebrimbor** [wow-mania/Redemption#325]
http://www.wow-mania.com/armory/?quest=12630

For this quest you'll need to use Nass(http://www.wow-mania.com/armory/?npc=28521) his to collect 10 hair samples from Withered Trolls(http://www.wow-mania.com/armory/?npc=28521). You could give Nass a kick to start collecting the hair by using the item Stefan Steel Toed Boot(http://www.wow-mania.com/armory/?item=38659) provided upon accepting the quest.

Nass does not collect anything from the Withered Troll. Kickin him 10 times does not help either.

**Comment by Calebrimbor** [comment]
Labeled with 'Priority' since this quest is frequently reported.

**Comment by Emcitementz** [comment]
Working fine on dev.
