### ISSUE TITLE
[Quest] Dark Horizon

### ISSUE THREAD

**Issue by Kalasbyxan** [wow-mania/Redemption#326]
The quest (http://www.wow-mania.com/armory/?quest=12664) in completed by talking to Gorebag (http://www.wow-mania.com/armory/?npc=28666) who sends the player on a gargoyle (http://www.wow-mania.com/armory/?npc=28759) to tour around Zul'Dark. The spell listed from Gorebag ishttp://www.wow-mania.com/armory/?spell=52194. 

The player gets thrown into the air behind a gargoyle, and was stuck with no take off.

**Comment by Calebrimbor** [comment]
Issue is labeled as 'Confirmed' on the BugTracker.
