### ISSUE TITLE
[Raiding] EoE10 (Normal) - Malygos undefeatable

### ISSUE THREAD

**Issue by Ainpat** [wow-mania/Redemption#328]
We tried the Malygos must die weekly quest recently and have met 2 bugs, one of those makes the boss extremely difficult if not uncompletable.

In Phase 1, the Power Sparks that are supposed to be summoned, don't have a travel path and just fall into the abyss, making the boss fight lose a very cool mechanic.

In Phase 3, everybody is mounted on a red dragon. Malygos will cast the spell "Surge" multiple times onto players, which deals 72k damage over the course of 3 seconds, which is almost lethal to any player on his drake. The intent is to use the Flame Shield ability of the dragon to reduce the damage taken by 80% for 6 seconds, but here is the catch: Flame Shield is uncastable, it just doesn't work, no matter how much you mash your button, thus the raid just slowly falls apart, cause every player targetted by Surge just dies.

If a GM wants to test the dragon, there is a daily quest in Coldarra that makes you use the same red dragon as in the raid, and that one also can't use his Flame Shield.

The quest would be this one -> (http://www.wow-mania.com/armory/?quest=13413)

**Comment by fvicaria** [comment]
I have made it slightly easier.
