### ISSUE TITLE
[Quest] Magic Carpet Ride

### ISSUE THREAD

**Issue by Arawyn** [wow-mania/Redemption#328]
http://www.wow-mania.com/armory/?quest=11636

For this quest you will need to Talk to Yanni(http://www.wow-mania.com/armory/?npc=25459} on the top of Warsong Hold in Borean Tundra.

Yanni should arrange a ride on a magical carpet from Warsong Hold to Garrosh's Landing, where you need to speak to Gorge the Corpsegrinder(http://www.wow-mania.com/armory/?npc=25329) in order to complete the quest.

You talk to Yanni and he spawns the Amazing flying carpet which you are placed on but the carpet does not travel/move and as such you are stuck for 5 minutes unable to move, Player has to re-log or abandon the quest in order to exit the carpet early.

**Comment by Calebrimbor** [comment]
Issue is labeled as 'Confirmed' on the BugTracker.
