### ISSUE TITLE
[Quest] Cold Hearted (12856)

### ISSUE THREAD

**Issue by ChemicalSerenity** [wow-mania/Redemption#33]
Upon accepting this quest, a drake is supposed to spawn that you use to fly to Dun Niffelheim and free other captured drakes. This drake never spawns, leading to a series of problems you must overcome to complete the quest:

- You lose your disguise, quest giver attacks you, requiring you to either kill her or run to the vill to regain your disguise

- You are provided no means of getting a drake, so you must provide your own. You can mount a drake from your own flyer, but that requires losing your disguise to mount.

- The initial drake mount results in a mount that is EXCEPTIONALLY slow. First hand in took over 5 minutes because it was moving at the "saunter" player pace. Drake also couldn't gain or lose altitude, so villager recovery could only happen on the ones that were "higher up" in Dun Niffelheim (fortunately, there are two that were within reach). After the hand-in, the second drake mount gave me full mobility and speed. This COULD be related to paladin auras, as I've noticed other npc mounts doing odd things with some auras being turned on, specifically and especially retribution, which toggles on and off with each heartbeat.

At present, the quest IS DOABLE, but is quite annoying. Not as annoying as The Dakkensryd though (see other bug)

Repro Steps:

- Obtain quest
- WTF as the quest giver promptly attacks you
- Fall off a cliff so you can lose your disguise and mount your ride
- Rescue a drake and marvel at flying what essentially amounts to a winged zeppelin in terms of overall speed and maneuverability
- Grab a beer, check the game scores waiting for the first turn in

**Comment by fvicaria** [comment]
Fixed.
