### ISSUE TITLE
[Raiding] ICC10 (Normal and Heroic) - Sindragosa once again

### ISSUE THREAD

**Issue by Ainpat** [wow-mania/Redemption#331]
Sindragosa has an ability called Blistering Cold, which pulls in all players of the raid at once into melee range. During Phase 2, Sindra also encases a player in a tomb, and the timing on the tomb is so that it happens together with Blistering Cold. Resulting in everybody getting frozen and the fight is over. Those two abilities are not supposed to happen at the same time.

**Comment by fvicaria** [comment]
Should be fixed for next release. Very nice bug report. This makes my work so much easier. Please enlighten other to follow this.
