### ISSUE TITLE
[Quest] Raise the Barricades

### ISSUE THREAD

**Issue by GMLucetta** [wow-mania/Redemption#332]
http://www.wow-mania.com/armory/?quest=13332

Players have to use the Barricade Construction Kit (http://www.wow-mania.com/armory/?item=44127) to erect 5 Barricades (http://www.wow-mania.com/armory/?npc=31887)

On using the quest item nothing happens.

**Comment by GMLucetta** [comment]
Issue added to the BugTracker for testing. Thank you for your report.

**Comment by Emcitementz** [comment]
This is working properly on dev, needs testing on live.
