### ISSUE TITLE
(Quest) Basic Chemistry

### ISSUE THREAD

**Issue by GMLucetta** [wow-mania/Redemption#333]
http://www.wow-mania.com/armory/?quest=13279

Players have to use Pustulant Spinal Fluid (http://www.wow-mania.com/armory/?item=44010) which is provided to neutralize Plague Cauldron (http://www.wow-mania.com/armory/?npc=31767). The item has a 1min30seconds cooldown. 

When used mobs are supposed to appear to attack the player and eventually after 3 or for uses of the Spinal Fluid the quest complete notification will be given. 

This is not working correctly, as no mobs spawn and no quest complete is given. Therefore it is not working as intended.

**Comment by GMLucetta** [comment]
Confirmed. I've managed to reproduce. Issue is labeled as 'Confirmed' on the Bug Tracker.

**Comment by Calebrimbor** [comment]
status BugTracker set as 'Pending'.

**Comment by Calebrimbor** [comment]
Quest works now, but not as intended. The cauldron should have more waves and spawns and the cauldron should give more warnings like: 'Neutralizing agent failing! Add fluid soon!, 'Something emerges from the cauldron' (this is when the mobs should spawn), 'The cauldron continues to boil...'. Our cauldron just gives 1 warning: 'The plague cauldron begins to boil vigorously'. Check https://www.youtube.com/watch?v=HvO7ZRdkyhA and see how many waves it normally takes to complete this objective. Also the number of spawns in should be more.

**Comment by Calebrimbor** [comment]
Fix is confirmed. Status on BugTracker set as 'Fixed'.

**Comment by Dmw1981** [comment]
working my ass
been at it over an hour
