### ISSUE TITLE
[Quest] It Rolls Downhill

### ISSUE THREAD

**Issue by Calebrimbor** [wow-mania/Redemption#334]
http://www.wow-mania.com/armory/?quest=12673

For this quest you'll need to use the Scepter of Suggestion(http://www.wow-mania.com/armory/?item=39157) on the Blight Geists(http://www.wow-mania.com/armory/?npc=28750) and then order them to harvest 7 Blight Crystals(http://www.wow-mania.com/armory/?npc=28740). This quest is part of the quest So Far, So Bad(http://www.wow-mania.com/armory/?quest=12669), you'll need to complete this task for Drakuru.

The Blight Gheists won't harvest the Crystals, tried on many different ones. Because of that you are not able to complete this quest but also not So Far, So Bad.

**Comment by respectdat1** [comment]
It still doesn't work. Not fixed.
