### ISSUE TITLE
[Quest] Krolmir, Hammer of Storms

### ISSUE THREAD

**Issue by Calebrimbor** [wow-mania/Redemption#336]
http://www.wow-mania.com/armory/?quest=13010

For this quest you'll need to talk to King Jokkum in Dun Niffelem and discover what he knows of Krolmir(http://www.wow-mania.com/armory/?object=192492). You will mount him and walk you to Thorim(GUID 371994). 

After the lore you won't receive the credit for it. Also, Thorim spawns several times
![wowscrnshot_091216_213012](https://cloud.githubusercontent.com/assets/20358867/18449840/0acd1efe-7931-11e6-9e41-d73bce3d8492.jpg)

**Comment by Calebrimbor** [comment]
Issue is labeled as 'Confirmed' on the BugTracker.

**Comment by wow-mania** [comment]
Fixed for next Wednesday. Please confirm.

**Comment by Calebrimbor** [comment]
status BugTracker set as 'Pending'.

**Comment by Calebrimbor** [comment]
Fix is confirmed. Status on BugTracker set as 'Fixed'.
