### ISSUE TITLE
Quest bug or quest removal?

### ISSUE THREAD

**Issue by empressnyx** [wow-mania/Redemption#337]
[A] quest "Freedom for All Creatures" in Feralas (Quest giver Kindal Moonweaver) is bugging. I'm not sure if the quest is supposed to be available and completable or if it was supposed to be removed. I thought the quest was removed by Blizz in Cata, but available in WotLK. 

I can pick up the quest and the timer starts, but the darters don't leave the cage when I unlock it, and Kindal doesn't follow along with me (as she should be) so the quest fails once the timer is over (5 minutes).

I just want to know if it's bugged or if it's not even supposed to be available. 

Thank you for your time,
~Bonnie

**Comment by fvicaria** [comment]
Should be fixed on next release
