### ISSUE TITLE
[PVP] Winterspring Graveyard Bug

### ISSUE THREAD

**Issue by glspisso** [wow-mania/Redemption#337]
Graveyards on the west side of Wintergrasp don't work as intended. 

**The Broken Temple one has no spirit guide** (and I believe during battle not even spirit healer) and forces you to go to Horde Landing Camp to obtain a res. Even there, **no resurrection happens at countdown** and one is forced to talk to the Spirit Guide an pick one of the other available resurrection spots. **One then get ressed, but with only half life / half mana**. This is annoying and also changes the intended bg dynamics, making the working temple (Sunken Ring) much more valuable.

This is from horde side, and speaking with alliance members they confirm having the same bug.

**Comment by Calebrimbor** [comment]
Issue added to the BugTracker for testing. Thank you for your report.

**Comment by wow-mania** [comment]
![image](https://cloud.githubusercontent.com/assets/12248683/18470633/5c6c657a-79a5-11e6-9e9a-edb4e240e3db.png)

Seems to work OK for me.

**Comment by glspisso** [comment]
I can confirm that it didn't work as of this morning. It has not worked for a while, and today I went and tested. You get the cooldown, but then nothing happens.
