### ISSUE TITLE
Quest : High Commander Halford Wyrmbane

### ISSUE THREAD

**Issue by sairynade** [wow-mania/Redemption#339]
Quest in Star's Rest, Dragonblight that is supposed to taxi you to Wintergarde Keep, Dragonblight. Quest and item are recieveable, but the taxi doesn't come nor can you take a flight path to Wintergarde. Tried abandoning and retaking with no success. (reposting this bug because it was from June 29th with no solution <3)

**Comment by wow-mania** [comment]
Duplicate #144 Please search before entering a new issue.
