### ISSUE TITLE
[Quest] Test of Lore (6)

### ISSUE THREAD

**Issue by CobaltConqueror** [wow-mania/Redemption#34]
http://wowwiki.wikia.com/wiki/Quest:Test_of_Lore_%286%29

This passage on this chain quest is bugged.  Parqual Fintallas, the NPC with whom you should talk, does not allow any interaction with regard to the question that you should ask him, not allowing it to respond and coompletare the mission and move on to the final step of the chain.

**Comment by ThaydeGM** [comment]
Confirmed on both horde and alliance.
 http://www.wow-mania.com/armory/?quest=6627 
http://www.wow-mania.com/armory/?quest=6628
The NPC does not allow any interaction regarding the question.
