### ISSUE TITLE
[Quest] The Drakkensryd (12886)

### ISSUE THREAD

**Issue by ChemicalSerenity** [wow-mania/Redemption#34]
This quest is ALMOST undoable. Like the Cold Hearted (12856) bug, you're supposed to be given a wyvern mount that doesn't spawn, requiring you to fly to the lightning temple on your own mount.

Once there, you CAN use the grapple, but combat is extraordinarily hard. H-t-H is impossible, ranged attacks only work at certain specific times. It's difficult to tell exactly, but it appears as though there's a difference between where the client thinks the enemies are and where the server thinks the enemies are, allowing attacks only when they're within the appropriate range. For some classes, this may be very difficult to finish (eg: primarily melee classes with no significant ranged capability). For all classes, this will be super annoying.

Kills do count. You can get to 10 dead. However, once you have killed 10, you are not dropped off at Thorim. The only way off is to dismount the dragon and fall. Most people will die as a result, but from there you can turn the quest in.

Repro Steps:

- Obtain the quest
- Find some way of ditching your disguise so you can mount your flyer and head to the temple
- Grapple a dragon and see "Too far away" and "Facing the wrong direction" when attempting to attack the rider
- Spam ranged attacks continuously for a couple minutes, waiting for the occasional one or two to hit
- Eventually kill 10 riders this way
- Dismount, enjoy your brief vertical flight
- Notice that your fall is actually longer than 12 seconds, as determined by the fact that your pally bubble disappears just prior to your scheduled meeting with the ground
- Respawn
- Finish the quest at Thorim.

**Comment by fvicaria** [comment]
Fixed. Just don't target the drake.
