### ISSUE TITLE
(Quest) Alien Egg

### ISSUE THREAD

**Issue by GMLucetta** [wow-mania/Redemption#340]
http://www.wow-mania.com/armory/?quest=4821

Players have to collect an Alien Egg (http://www.wow-mania.com/armory/?item=12467) when interacting they are unable to pick the item up. This is not working as intended.

**Comment by GMLucetta** [comment]
Confirmed. I've managed to reproduce. Issue is labeled as 'Confirmed' on the Bug Tracker.

**Comment by wow-mania** [comment]
Works fine in dev.

**Comment by Calebrimbor** [comment]
Tested it, it's working on both frostmourne and redemption
