### ISSUE TITLE
[Talent] Blood Craze

### ISSUE THREAD

**Issue by lunatizm** [wow-mania/Redemption#341]
The talent Blood Craze in the Fury warrior talent tree never procs

**Comment by Calebrimbor** [comment]
http://www.wow-mania.com/armory/?spell=16492

Issue added to the BugTracker for testing. Thank you for your report.

**Comment by wow-mania** [comment]
Can somebody confirm this. I think it works but it may have an issue with particular debuffs

**Comment by Emcitementz** [comment]
Tested, fully working.
