### ISSUE TITLE
[Quest] Kharan's Tale

### ISSUE THREAD

**Issue by Kalasbyxan** [wow-mania/Redemption#342]
In the quest (http://www.wow-mania.com/armory/?quest=4342) upon interacting with Kharan (http://www.wow-mania.com/armory/?npc=9021) he tells you a tale.

Upon interacting with Kharan, he says "Allow me to finish telling my story." but nothing happends, both with GM mode off and on. Respawning NPC did not work.

**Comment by wow-mania** [comment]
Fixed for next Wednesday. Please confirm.

**Comment by Calebrimbor** [comment]
Fix is confirmed. Status on BugTracker set as 'Fixed'.
