### ISSUE TITLE
[Quest] Load'er Up!

### ISSUE THREAD

**Issue by Calebrimbor** [wow-mania/Redemption#344]
http://www.wow-mania.com/armory/?quest=11881

For this quest you'll need to help Jenny(http://www.wow-mania.com/armory/?npc=25969) make her way from the crash site to Fezzix Geartwist at Taunka'le Village without losing all her cargo. In order to summon Jenny you use Jenny's Whistle(http://www.wow-mania.com/armory/?item=35272) when being at the crash site.

No matter where I stand, in the ceash site or the surrounding area, Jenny can't be summoned. According to the error message you 'Requires Crashed Flying Machine'.

**Comment by wow-mania** [comment]
![image](https://cloud.githubusercontent.com/assets/12248683/18583009/0e1aafb4-7c00-11e6-9373-ff65ae297fa4.png)

**Comment by wow-mania** [comment]
Fixed the credit credit issue.
Fixed for next Wednesday. Please confirm.

**Comment by Calebrimbor** [comment]
Fix is confirmed. Status on BugTracker set as 'Fixed'.
