### ISSUE TITLE
Sindragosa

### ISSUE THREAD

**Issue by Kyliss** [wow-mania/Redemption#346]
Sindragosa is not working well.
When blistering is coming, Sindragosa is not doing any damage to people.
Also in air phase, there are 4 bombs coming down. The last one is coming in same time with Sindragosa.
The last Phase, when someone get the arrow blue. The first one is fine, after that sindragosa is doing the second target with arrow blue in same time with blistering and i take everyone is hear bully and all the raid got freez. The time is wrong and Blistering.

**Comment by wow-mania** [comment]
Should be fixed. It will be not exactly like Blizzard but it is doable.
