### ISSUE TITLE
[Quest] Neutralizing the Plague

### ISSUE THREAD

**Issue by Kalasbyxan** [wow-mania/Redemption#347]
The quest (http://www.wow-mania.com/armory/?quest=13281) requires the player to kill a Pustulent Horror (http://www.wow-mania.com/armory/?npc=31139) to loot a Flesh Giant Spine (http://www.wow-mania.com/armory/?item=44009) to create Pustulant Spinal Fluid (http://www.wow-mania.com/armory/?item=44010). Player is then supposed to use the fluid on a Blight Cauldron at Mord'rethar: The Death Gate. This will create emotes and spawn waves of mobs.

Everything works up until using the fluid on the Blight Cauldron. The initial emote upon using the Pustulant Spinal Fluid (The plague cauldron begins to boil vigorously) happens but nothing more, neither in player mode or GM mode. In GM mode I see I'm followed by Summoned Plague Cauldron Bunny 2.

Also see https://github.com/wow-mania/Redemption/issues/333 for the previous step and same issue.

**Comment by wow-mania** [comment]
Works. It will take 2 or 3 times and it's a random result each time you use the Pustulant Spinal Fluid.
