### ISSUE TITLE
(Quest) Kodo Roundup

### ISSUE THREAD

**Issue by GMLucetta** [wow-mania/Redemption#348]
http://www.wow-mania.com/armory/?quest=5561

Players have to use the Kodo Kombobulator (http://www.wow-mania.com/armory/?item=13892) provided to target Ancient Kodo (http://www.wow-mania.com/armory/?npc=4702) or Aged Kodo (http://www.wow-mania.com/armory/?npc=4700) or Dying Kodo (http://www.wow-mania.com/armory/?npc=4701) Players have to do this with five separate Kodo's running back to the quest giver Smeed Scrabblescrew (http://www.wow-mania.com/armory/?npc=11596) with each one. 

Players are able to target the Kodo's with the Kodo Kombobulator, but if the Kodo's follow them they are not getting the dialogue from Smeed Scrabblescrew so are not given the partial quest completion for each one. However, some Kodo's refuse to move when being targeted and again cannot be handed in. 

This is not working correctly as players cannot get the quest complete. 

Added to the bugtracker as confirmed.

**Comment by GMLucetta** [comment]
Confirmed. I've managed to reproduce. Issue is labeled as 'Confirmed' on the Bug Tracker.

**Comment by jarvik76** [comment]
> However, some Kodo's refuse to move when being targeted and again cannot be handed in.

This appears to be back in some form of regression, I had exactly this scenario on Red tonight.
