### ISSUE TITLE
[Quest] The Kor'kron Vanguard! (12224)

### ISSUE THREAD

**Issue by ChemicalSerenity** [wow-mania/Redemption#35]
This is slightly misleading, as I think the actual problem lies in the quest "The Might of the Horde" (12053) and equivalent alli quest.

To get the quest giver's mark from Overlord Agmar (26379), one must complete a long series of prior quests. [You can see the chain here.](http://www.wowhead.com/quest=12053/the-might-of-the-horde)

However, 12053 does something odd. It appears that it has two conditions (1 - defend the banner, 2 - return the banner to base) but it will permit the next quest in the chain to be taken before the banner is returned. Later on, if one notices that the quest is marked as "failed", the standard procedure is to abandon it and retry which leads to a weird database bug where there's a timestamp entry in both the completed AND the abandoned column. That in turn seems to screw things up for trying to obtain the Kor'kron Vanguard quest, because it prevents the quest giver's mark from being displayed.

For anyone afflicted by this bug, the best solution for the moment would likely be to remove 12053 The Might of the Horde and subsequent quests to allow the player to redo them and making sure the banner gets returned to base (the banner is also bugged, it follows you like a pet rather than being mounted on your back like a pennant - apparently, all pennant style things are broken in that way). The best solution for future people is to refuse the next quest in the chain without the banner being returned. It's unclear how that one completion requirement is sufficient to allow the next quest in the chain to be selected.

Repro Steps:

- Semi-complete "The Might of the Horde", turning in the quest
- Notice later that it's marked as "Failed"
- Abandon the failed quest, but notice you cannot redo it as you've already moved on to the next quest in the chain
- Be annoyed when the quest marker never appears above Overlord Agmar, despite completing all the other pre-requisites
- Never see the wrathgate cutscene, which makes you a sad panda

**Comment by fvicaria** [comment]
The quests have the correct dependencies.
If are not given the credit the quest is not complete.
As long it can be completed if done correctly I will not do anything (at least for now)
