### ISSUE TITLE
(Quest) Steamtank Surprise

### ISSUE THREAD

**Issue by GMLucetta** [wow-mania/Redemption#350]
http://www.wow-mania.com/armory/?quest=12326

Players are required to use an Alliance Steam Tank (http://www.wow-mania.com/armory/?npc=27587) in order to destroy 6 Plague Wagons (http://www.wow-mania.com/armory/?npc=27625) and rescue 7th Legion Elite (http://www.wow-mania.com/armory/?npc=27588)

On targeting the steam tank there is no way to get inside it to use it for the quest. therefore the quest cannot be completed.

**Comment by dothie** [comment]
the q is bugged again
