### ISSUE TITLE
[Raid] Icecrown Citadel's Professor Putricide (most likely 10m nm/hc only)

### ISSUE THREAD

**Issue by Ashamedlol** [wow-mania/Redemption#351]
Oozes (both green and red) do not start their locating unless touched or spat on or p1 -> p2 phase switch, so makes them ignorable which leads into a Professor vs raid and abom, no oozes.

On 10 heroic, after Professor mixes his pots (during phase switch of phase 1 to phase 2), he casts choking bombs and/or malleble goo when not supposed to (while transforming to his second form which means he should freeze).

**Comment by wow-mania** [comment]
Fixed for next Wednesday. Please confirm.
