### ISSUE TITLE
[Talent] Retribution Paladin's Swift Retribution + Sanctified Retribution

### ISSUE THREAD

**Issue by Ashamedlol** [wow-mania/Redemption#353]
Swift Retribution: Talent does not give your raid a 3% haste bonus, does not work on other auras (when supposed to do so).

Sanctified Retribution: Talent does not give your raid a 3% damage bonus, does not work on other auras as well (supposed to do so).

**Comment by wow-mania** [comment]
Fixed for next Wednesday. Please confirm.
