### ISSUE TITLE
[Raid] Icecrown Citadel's Gunship Mortar Team/Rocketeers

### ISSUE THREAD

**Issue by Ashamedlol** [wow-mania/Redemption#356]
They freeze and do nothing, sometimes happens to one rifleman out of the many thousands, but it happens 100% on mortar or rocketeer unless damaged/touched, they should be triggering automatically.

**Comment by Kalasbyxan** [comment]
Skybreaker Mortar Soldier (http://www.wow-mania.com/armory/?npc=36978) on the Alliance Ship does not engage in combat, not even when damaged.

Kor'kron Rocketeer 8http://www.wow-mania.com/armory/?npc=36982) on the Horde Ship does not engage in combat, not even when damaged.

Only tested on 25nm so far.
