### ISSUE TITLE
[Raid] Icecrown Citadel's Rotface

### ISSUE THREAD

**Issue by Ashamedlol** [wow-mania/Redemption#358]
Slime Spray should be frontal (rotface faces a direction and everyone has to move away from the front) and UN-INTERUPTABLE. Slimes should be immune to stun and their movement speed should be slower than what we experience right now.

Also, some random bug happens where the slime pipes leak slime in the air instead of on ground (it still damages without being visual on the ground, just visual on air).

**Comment by GMSunShield** [comment]
**Raid:** Icecrown Citadel http://www.wow-mania.com/armory/?zone=4812

**Boss:** Rotface http://www.wow-mania.com/armory/?npc=36627

**Boss's Fight Ooze**
- The third and last aspect of the fight are the oozes spawned through Mutated Infection. Every so often Rotface will target a random raider and debuff them with a dispellable Mutated Infection (this debuff is used more frequently as time goes by). The infection will last 12 seconds or until removed (it's a disease), and will spawn a Small Ooze. It doesn't do much damage, but is not tauntable and starts with huge lead in threat on the formerly infected target. This means that the Small Oozes will stay with the person who spawned them until they merge with another ooze. If there are no Big Oozes, have the newly infected person stay with the add tank until another Mutated Infection is cast, and another Small Ooze spawns. The two small oozes will merge and form a Big Ooze, which will follow normal threat rules (and is tauntable). The add tank should kite the Big Ooze in a circle around the room, avoiding the Sticky Ooze puddles the Big and Small Oozes shoot at him/her. Every time there is a Mutated Infection, the player with it should run between the tank and the Big Ooze, drop its Small Ooze there, wait for the Small Ooze to be absorbed, and only then return to the middle. Tanks, the Big Oozes are not tankable, their damage is too high. Kite them!

**The first two Small Oozes that merge will form a Big Ooze. Every next Ooze that merges with the big one will add a stack to its Unstable Ooze. When that stack reaches 5 (after the 6th ooze has spawned), the Big Ooze will freeze in place and cast Unstable Ooze Explosion. As soon as the cast is over, everybody should scatter to avoid the flying ooze missiles. Don't forget to avoid the ooze floods, and make sure to stack back in the middle as soon as you can.**

**Radiating Ooze:** http://www.wowhead.com/spell=69760/radiating-ooze - Inflicts 4,388 to 4,612 damage every 2 seconds to players within 10 yards. Causes the Big Ooze to merge with other nearby Big Ooze. When a Big Ooze merges with another one, it gains a stack of Unstable Ooze. 
**Ooze Skill**
- Unstable Ooze Explosion -http://www.wowhead.com/spell=69839/unstable-ooze-explosion The Big Ooze explodes, sending 3 ooze missiles flying at random players' locations. Each missile inflicts 9,750 to 10,250 Nature damage to players within 6 yards. Cast when a Big Ooze reaches 5 stacks of Unstable Ooze.

>**Issue:** Radiating Ooze can be stunned when casting Unstable Ooze Explosion this should not happen. All raid members should move away from the ooze when it cast Unstable Ooze Explosion.
_________________________________________________________________________________________________________

**Boss Skill:** Ooze Flood http://www.wowhead.com/spell=69789/ooze-flood

- **Skill Info**
The Ooze Flood inflicts 4826 to 5074 damage every 1 sec and reduces move speed by -10% for 5 sec.

>**Issue:** Sometimes the Ooze Flood visual will be in the air but still do damage to any players under it on the ground. this makes it hard to say for some players  or players that run in to it.
