### ISSUE TITLE
[Raid Optional] Icecrown Citadel's Hellscream's Warsong and Strength of Wrynn (30% BUFF)

### ISSUE THREAD

**Issue by Ashamedlol** [wow-mania/Redemption#359]
When you talk to Garrosh or Varian inside ICC (based on faction), they should be giving you the option to turn off the 30% bonus-to-all buff, but neither do right now.

**Comment by GMSunShield** [comment]
Confirmed both NPCs do not take the buff off when you talk to them.

**NPC Varian:** http://www.wow-mania.com/armory/?npc=39371 lets you talk to him but does not take the buff off. 
**NPC Garrosh:** http://www.wow-mania.com/armory/?npc=39372 does not let you talk to him just has Greetings (Playername)
