### ISSUE TITLE
[Quest] Scouring the Desert (9419, 9422)

### ISSUE THREAD

**Issue by ChemicalSerenity** [wow-mania/Redemption#36]
Vanilla world PVP quest in Silithus. You can obtain the quest and find Silithyst nodes, but when you attempt to harvest them nothing happens. As I recall, a silithyst aura should be applied to the toucher which slows the player and increases aggro radius.

Repro Steps:

- Go to Silithus
- Obtain quest
- Try to harvest nearby silithyst
- Notice that nothing happens
- Bemoan the fact that the armies of bugs in Ahn Qiraj will proceed unimpeded

**Comment by wow-mania** [comment]
http://www.wowhead.com/spell=29519/silithyst
http://www.wowhead.com/object=181598/silithyst-geyser

**Comment by fvicaria** [comment]
Fixed.
