### ISSUE TITLE
I can't optimize wow

### ISSUE THREAD

**Issue by HeroMarine** [wow-mania/Redemption#360]
Whenever I enter the game, it has the default video and resolution settings. When i go to change them, it works but some of the settings need me to restart the game. The problem is every time i restart the game, it resets my settings to default again. This means that i can't optimize for let's say the better character models because it requires a game restart, and when i do that, it resets everything back to default. I don't know if this is a bug only affecting me, but it kind of makes optimizing wow hard.

**Comment by Rushor** [comment]
ne need to start wow as administrator - then all your stff will be saves

**Comment by fvicaria** [comment]
@Rushor thanks for helping.

**Comment by HeroMarine** [comment]
Thank you so much bro! :+1:
