### ISSUE TITLE
[Raid] Kologarn

### ISSUE THREAD

**Issue by GMSunShield** [wow-mania/Redemption#361]
**Raid:** Ulduar10 http://www.wow-mania.com/armory/?zone=4273#npcs

**Boss:**http://www.wowhead.com/npc=32930/kologarn#article

Kologarn and his two Arms can all be targeted, so the raid can choose what, when and how to kill. 

Kologarn himself has the most hit points and number of abilities. His Overhead Smashes require an Offtank, as they reduce the armor of the main tank by a big percent, and stack. Focused Eyebeams will need to be avoided by everybody (similarly to the Tribunal of Ages event in Halls of Stone). If there are no players in melee range, Kologarn will quickly wipe the raid with Petrifying Breath. If both of his Arms are dead, he will channel Stone Shout, which is massive raid-wise AoE your group will want to avoid.

Kologarn's Right Arm has only one ability, and it is Stone Grip. It grabs 1 players and inflicts damage to them, until the Arm is damaged enough to drop them, or until at least one of the players dies. Killing the Arm reduces Kologarn's health by 15%; it also spawns 5 Rubble creatures, that have AoE and should be offtanked and killed quickly; it takes 30 seconds for an Arm to respawn.

Kologarn's Left Arm casts Shockwave periodically, which is a raid-wide AoE the healers will just need to heal through. Killing this Arm has the same effect on Kologarn's health, and also spawns 5 Rubbles.

>**Issue1:** If the raid dies to him they cant attack him again he will evade every attack other then his arms you can still attack them.

>**Issue2:** Bosses arms spin to his back after they break, Does not mess the boss up just looks bad.
>When the boss dies his body despawns and does not become the pathway to the other side of the room you can still get to the other side. His dead graphic is just not there so you end up walking on air.

Boss fight Video: https://www.youtube.com/watch?v=PSkUlEvZdww

**Comment by wow-mania** [comment]
Seems to be fixed now.
