### ISSUE TITLE
Now This is Ram Racing... Almost. 11318

### ISSUE THREAD

**Issue by xPUNJABx** [wow-mania/Redemption#362]
The quest requires you to ride the quest mount at three speeds for 8 seconds.  However the quest is not updating as each speed is held for the correct time (8 secs) please refer to here http://wotlk.openwow.com/quest=11318 for quest details

**Comment by GMSunShield** [comment]
I have tested this and the quest does not update when doing it the right way
Alli quest: http://www.wow-mania.com/armory/?quest=11318
Horde quest: http://www.wow-mania.com/armory/?quest=11409

Quest item: http://www.wow-mania.com/armory/?item=33306
quest mount: http://www.wow-mania.com/armory/?spell=43883

**Comment by wow-mania** [comment]
Should have been fixed already.
