### ISSUE TITLE
Heated battle

### ISSUE THREAD

**Issue by Coen1982** [wow-mania/Redemption#364]
Aid Captain Iskandar in holding the canyons by participating in the death of 12 Frigid Ghoul Attackers, 8 Frigid Geist Attackers, and 1 Frigid Abomination Attacker.
Captain Iskandar is supposed to walk between two caverns and if you follow him you get ambushed by the mobs you're supposed to kill. You should get credit even if you do just a little bit of damage to the mobs, like an aoe attack.

Thing is that Captain Iskandar isn't walking around but is always in the same place, and even if you do 70-80% damage to a mob you don't get the kill. You can only get the kill if you and only you attack one mob and kill it. These are mostly the stray ones and you'll find just a few of them in a day.

**Comment by fvicaria** [comment]
Quest works fine.

**Comment by 09uaopsifh12** [comment]
Nope it doesn't, bug confirmed!
