### ISSUE TITLE
[Raid] XT-002 Deconstructor

### ISSUE THREAD

**Issue by GMSunShield** [wow-mania/Redemption#365]
**Raid:** Ulduar10. http://www.wow-mania.com/armory/?zone=4273

**Boss:** XT-002 Deconstructor. http://www.wow-mania.com/armory/?npc=33293

**Boss Fight**
- XT-002 Deconstructor is mostly a straight-forward fight. He has two Phases - Boss phase (Phase 1) and Heart phase (Phase 2). He will begin the fight in his Boss phase and switch to Heart phase for every 25% of his health lost (unless he is in his hard mode). XT-002 will be inactive during heart phases, which last 30 seconds each. His Hard Mode can also be activated during any one of the Heart phases.

When he is in Phase 1, the raid will need to stay close to each other, while the person charged with Searing Light/Gravity Bomb runs away. The occasional Tympanic Tantrums will damage all players for almost their maximum health, so healers will need to be well assigned, and no player be left without a healer for the 8 seconds duration of the spell. Players with Searing Light or Gravity Bomb during the Tantrums will need extra heals.

XT-002 will enter Phase 2 whenever his health reaches 75%, 50%, and 25%. During this phase he will be unattackable and three kinds of adds will spawn - XM-024 Pumellers (melee), XS-013 Scrapbots (healers), and XE-321 Boombots (exploders). Pumellers should simply be tanked and killed; Scrapbots will head directly towards XT-002 and heal him if they get to him, so they need to be killed quickly; Boombots will also follow normal aggro table, but will explode when their health reaches zero, damaging players and NPCs in proximity. XT-002's Hard Mode can be unlocked during any of the Heart phases (although the first one is most convenient). His heart is exposed during this phase and can be damaged; as long as it is not destroyed, XT-002 will take double the damage done to the heart after the Phase ends. It is absolutely possible to force XT to enter a second Heart phase right after the first one has ended, if you inflict enough damage.

**Main Point**
- At every 25% of the XT-002 Deconstructor fight the boss will shut down for 30 seconds and expose its heart. During this time adds will also spawn around the room.

The heart takes double damage from all attacks, and any damage done to the heart is done to the boss as well. The heart will heal to full between every exposure.

Killing the heart while it's exposed engages Hard Mode for the encounter, increasing the boss' health by 45% 50% and its damage done by 40%.

> **Issue1:** Heart phase http://www.wowhead.com/npc=33329/heart-of-the-deconstructor The damage done to the heart does not get done to the boss as well. This makes the heart pointless unsure if you can even do hard mode on the boss if the heart is not working.
> Hard mode: http://www.wowhead.com/spell=65737/heartbreak

**Comment by Ashamedlol** [comment]
Recent: Now the heart spawns for the first 5 seconds then disappears as you cannot dps it and it does not spawn adds so you're sitting AFK in front of XT-002 as he drops his unexistant heart.

**Comment by barfmachine** [comment]
confirmed:)
