### ISSUE TITLE
[Raid]Icecrown Citadel: Festergut Vile Gas

### ISSUE THREAD

**Issue by GMSunShield** [wow-mania/Redemption#368]
**Raid:** Icecrown Citadel 10HC / 25normal / 25HC http://www.wow-mania.com/armory/?zone=4812

**Boss:** Festergut http://www.wowhead.com/npc=36626/festergut#abilities:mode=h10

**Missing Boss Skill**
- Vile Gas http://www.wowhead.com/spell=69240/vile-gas 
  Inflicts a Vile plague in targeted area, inflicting 4387 to 4613 damage every 2 sec for 6 sec. The plague causes the infected targets to vomit uncontrollably inflicting 4387 to 4613 damage to nearby allies.
- http://s17.postimg.org/sq9o1qx67/Vilegas.png

> **Issue1:** Festergut does not cast this skill in 10hc / 25n / 25hc it seems to be missing from his skill list even on Wow-Maina armory skill list http://www.wow-mania.com/armory/?npc=36626 seems to only show 10man normal skill list.
> 
> **Issue2:** Vile Gas seems to do more damage then it should on Rotface 10 hc should only do 4387 to 4613 seen it do 7k+ should be checked!. Seeing how the skill IDs are the same for Vile Gas Rotface and Festergut the damage should be checked

Boss fight 25 normal with Vile Gas
https://www.youtube.com/watch?v=cQYVvu-2a60

**Comment by Ashamedlol** [comment]
Don't forget that Vile Gas's damage increases if more targets are near, so it's unclear if the damage is bugged or not.

Also, Gastric Explosion is bugged: It only kills the tank, doesn't deal the 30k to the 10-yard people.
