### ISSUE TITLE
[Dungeon] Blackrock Depths Bugs and Bugged Quests

### ISSUE THREAD

**Issue by PreludeToRuin** [wow-mania/Redemption#376]
I've been doing a quest run in BRD, and I noticed a number of issues both inside the instance and in dungeon-related quests. I'll list what I've found here, then they could be treated individually. 

1) http://www.wowhead.com/quest=4121
[Precarious Predicament]: This quest happens in Burning Steppes. You have to escort Grark Lorkrub (http://www.wowhead.com/npc=9520) from the Blackrock Stronghold, through Blackrock Mountain and into the Searing Gorge exit. The problem is, after you accept the quest, Grark never starts moving, or even goes to assist in your battles. Upon attempting to abandon and retake the quest, the [Thorium Shackles](http://www.wowhead.com/item=11286) are destroyed and don't reappear on retaking. I'm not sure how that affects the completion when you reach your destination, but it would have to since it's listed in the prerequisites. This quest is followed up by [Operation: Death to Angerforge](http://www.wowhead.com/quest=4132), which in turn can't be completed.

2) http://www.wowhead.com/quest=3982
[What Is Going On?]: In Blackrock Depths. You find Commander Gor'Shak (http://www.wowhead.com/npc=9020) in a cage in the Detention Block. When you accept his quest, you should be attacked by insta-spawned mobs and defend him to complete and open the next quest. Nothing spawns, so the quest is uncompletable.

3) http://www.wowhead.com/quest=4134
[Lost Thunderbrew Recipe]: In Blackrock Depths. In the Grim Guzzler, you have to attack the 3 kegs left of the entrance. Hurley Blackbreath (www.wowhead.com/npc=9537) will spawn and, after defeating him, you can loot the [Lost Thunderbrew Recipe] from him. However, after you attack the kegs, no one spawns, making the quest uncompletable.

4) http://www.wowhead.com/quest=27596
[The Heart Of The Mountain]: In Blackrock Depths. You have to collect [Relic Coffer Keys](http://www.wowhead.com/item=11078) from mobs to open all the coffers in The Black Vault. Watchman Doomgrip (http://www.wowhead.com/npc=9476) will appear and, on defeat, drop [The Heart of The Mountain](http://www.wowhead.com/item=11309). Even after I've opened all 12 safes, though, nothing spawns, so the quest can't be completed. In WoWHead, it's been mentioned that the Dark Keeper safe is optional. Regardless of that, I've tried searched for the keepers, but none of the six have spawned in one of their respective positions.

5) http://www.wowhead.com/quest=4941
[Eitrigg's Wisdom]: You have to go to Orgrimmar and speak with Eitrigg, in Grommash Hold, and then talk to Thrall. However, when you talk to Eitrigg, the bubble below his text that would continue the conversation and lead to completing the quest doesn't appear. This quest is followed up by [For The Horde!](http://www.wowhead.com/quest=4974), which is, in turn, uncompletable.

6) It is possible that some doors can bug if you don't use [Shadowforge Key](http://www.wowhead.com/item=11000) even if you have superior lockpicking skill. I reached the door to the Lyceum and tried to use Lockpicking on it (400 skill). It budged, stayed closed and became untargettable, blocking my progress.

**Comment by wow-mania** [comment]
Fixed most of them. If any is still an issue log them separately. We do not accept bundled reports.
