### ISSUE TITLE
[NPC] Bleeding Hollow Tormentor (19424) fear effect backfires

### ISSUE THREAD

**Issue by ChemicalSerenity** [wow-mania/Redemption#38]
When the Bleeding Hollow Tormentors in Hellfire Peninsula cast their fear effect, it doesn't land on the target, it lands on the tormentor itself.

Repro steps:

- Pick a fight with a Tormentor outside of Zeth'gor
- Laugh as they repeatedly terrify themselves

**Comment by wow-mania** [comment]
This should be fixed for next restart. Release 10.
