### ISSUE TITLE
DK Final quest doesnt work, impossible to start a dk now

### ISSUE THREAD

**Issue by senpai12305** [wow-mania/Redemption#382]
Quest The Light of Dawn doesnt work. Mograine charges at the chapel and then dissapears, minions will go there and dissapears after a moment too. Please repair it, its really annoiyng and it makes starting DK impossible

**Comment by wow-mania** [comment]
It works and if by any chance it fails you can ask a gm to restart it. Long way from "impossible to start a DK".
Please look at our [How to Log an Issue Properly](https://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue) next time. No rants here please.
