### ISSUE TITLE
Quest Summons

### ISSUE THREAD

**Issue by Lhorr** [wow-mania/Redemption#383]
Each quest in "Old World" that I have done so far involving summoned mobs summons twice as many as it should, two of each.

If you need a specific quest to test, I most recently attempted "Lard Lost His Lunch" in Hinterlands, which should summon three mobs, but instead summoned six.

Thanks,
Lhorr

**Comment by wow-mania** [comment]
Here are a list of some of quest that need summoning and summoned 2x mobs, this was noticed after the recent patch.
Barren - Echeyakee - 2x normal mobs
Ishamuhale - 2x normal mobs
The binding - 2x normal mobs
Hinterland - Lard lost his lunch - 3x normal mobs now 6x
Hellfire - Natural Remedies - 2x elite mobs
Icecrown - If he cannot be turned - 2x elite generals
It seems that all summon quests will summon double and also quests which required to use x item on y will give a double count. You an easily deal with the normal mob but for elite it become undoable especially [If he cannot be turned] which is supposed to be solo quest.

**Comment by fvicaria** [comment]
Fixed on next release.
