### ISSUE TITLE
[Achievement] Share The Love

### ISSUE THREAD

**Issue by Kalasbyxan** [wow-mania/Redemption#383]
This achievement (http://www.wow-mania.com/armory/?achievement=2152), a part of the WoTLK Dungeon Achievement (http://www.wow-mania.com/armory/?achievement=2136) that rewards a mount when completed.

In Gun'Drak the boss Gal'darah (http://www.wow-mania.com/armory/?npc=29306) uses the ability Impaling Charge ( (http://www.wow-mania.com/armory/?spell=59827). He charges a player and impales them on his horn. When all five party members have been impaled at least once, the achievement is granted.

The achievement does not get granted even though five different party members got impaled.

**Comment by wow-mania** [comment]
Fixed for next Wednesday. Please confirm.
