### ISSUE TITLE
An Embarassing Incident - Sholazar basin quest

### ISSUE THREAD

**Issue by Cpburk** [wow-mania/Redemption#384]
You need to loot and pile of sand and get a key.. we tryd for a long time with our mains aswell when we lvled.. and it just keeps spawning mobs and mobs.. nothing to loot.

**Comment by Dynamo12** [comment]
There are many piles in the pond. You need to find the right one, the wrong ones spawn eels.

**Comment by Rushor** [comment]
there is only one go which contains the key :D and that's blike - so closing
