### ISSUE TITLE
[Quest] multiple escort quests

### ISSUE THREAD

**Issue by Mooci** [wow-mania/Redemption#389]
Same issue encountered trying to do 2 escort quests in Darkshore:
- Therylune's Escape ( http://www.wow-mania.com/armory/?quest=945 )
- Escape Through Force ( http://www.wow-mania.com/armory/?quest=994 )

Issue specifically occurs with the sharing of the escort quest in a party: it will only be able to be completed by the person who initially took the quest, not by a person accepting the quest from the pop up.
(possibly an issue with all escort quests in a party? not confirmed tho)

to recreate:
1: be in a party of at least 2, with both people able to take the quest (prerequisites completed, not already completed the quest)
2: first person takes the quest from quest giver
3: second person will get ta pop up warning that first person is starting an escort quest. click "accept". the quest will be added to the second persons quest log
4: escort the subject till the end, completing the quest
5: only the person initially taking the quest from the quest giver will get credit for completion, the person accepting through the pop up will not

**Comment by wow-mania** [comment]
![image](https://cloud.githubusercontent.com/assets/12248683/19292277/d2f0343c-9012-11e6-9caa-b5ca812a56a6.png)

**Comment by Mooci** [comment]
While that may be true, this issue was not about trying to share the quests.
In fact the quests DO share, _automatically_, as soon as someone in the party picks it up, as all escort quests do afaik.

When somebody in party picked up the quest, i did get a popup asking if i wanted to join it, i did get the quest added to my log when clicking accept. So clearly the quest does share, maybe not with the share button, but with the intended automatic sharing of escort quests.
The problem was that even tho it got added to the quest log and got started for both of us, it could not be completed by anyone other than the person talking to the questgiver.

So there are 2 possibilities: 
1: It's supposed to be automatically shared, but something is wrong with it not getting completed for everyone
2: It's not supposed to be shared at all, so there should be no automatic popup to share it.

**Comment by wow-mania** [comment]
There is a distance criteria. If you are not close to the NPC within a specified range you don't get credited.
Was that what happened?

**Comment by Mooci** [comment]
Hard to be sure, but generally we stick together and it happened twice. 
I was at least close enough to hear the NPC give there lines at the end of the escort (like "i can find my own way from here, go tell .... i'm ok" or some variant of that). But i don't know exactly how close or far i was, or what the max range on it is, so i guess i should try it again some time.
