### ISSUE TITLE
Trinket does not follow its tooltip

### ISSUE THREAD

**Issue by Whalecow1** [wow-mania/Redemption#389]
The meteorite crystal trinket does not follow its description. USE: "Each spell cast within 20 seconds will grant a stacking 60 mp5 regen. Expires after 20 seconds. Abilities with no mana cost will not trigger this trinket" 
instead the trinket gives a buff which says that it "gives a chance to grant a stack 75 mp5 bonus" 
The original text says that the bonus should be guaranteed on spellcast and not by chance. a scripting fix for this stack would be lovely. =)

**Comment by Whalecow1** [comment]
Hopefully already solved through link provided.

**Comment by wow-mania** [comment]
Fixed.
