### ISSUE TITLE
[Quest] - Alpha Worg 11324

### ISSUE THREAD

**Issue by pamshoney2003** [wow-mania/Redemption#39]
Quest #11324: Alpha Worg not working correctly.

Upon completing previous quest in series (Eyes of the Eagle: 11417), turned in to NPC (Ulfang: 24261), which made me immediately consume the Eyes of the Eagle (Item 34027) and granted the buff, but this buff lasted only 5 seconds. This isn't long enough to find your next target (Garwal: 24277) and kill him. After finding Garwal, buff is gone and he cannot be attacked.

**Comment by Oriden** [comment]
Fixed!
