### ISSUE TITLE
[Spell] Mark of the wild (druid buff)

### ISSUE THREAD

**Issue by Mooci** [wow-mania/Redemption#390]
Unable to buff MotW rank 3 _(http://www.wow-mania.com/armory/?spell=6756#.)_ on a target with Spirit buff from Scroll of Spirit II _(http://www.wow-mania.com/armory/?item=1712)_

to recreate: 
1: use Scroll of Spirit II 
2: use Mark of the Wild (rank 3) on same target. -> target will not gain the buff
3: remove scroll of spirit buff
4: use mark of the wild again -> target will now gain the buff 

possible cause?: the scroll gives 5 spirit, where as motw rank 3 only gives 4, thus maybe triggering the "cant override stronger buff" mechanic? This ofc should not happen since motw gives many other stats as well.

**Comment by Kalasbyxan** [comment]
This issue goes for every stat increase spell or scroll granting any stat more than the 2, 4, 6, 8, 10, 12, 14, and 37 granted by the different ranks of Mark of the Wild and Gift of the Wild.

**Comment by wow-mania** [comment]
This seems to be the way it worked on live.
http://wow.allakhazam.com/forum.html?forum=69&mid=125293771051776082
http://www.wowhead.com/forums&topic=48207/mark-of-the-wild-overwriting-scrolls

I will keep an eye on it but it but for now it will be marked as is.
