### ISSUE TITLE
I can't optimize wow

### ISSUE THREAD

**Issue by HeroMarine** [wow-mania/Redemption#391]
So every time i go and change the video settings, and then restart wow, they are back at their defaults.( I need to restart wow because some of the video settings don't take affect until a restart) Someone told me to start wow as administrator, i did but it still doesn't save, can someone please tell me how to fix this?

**Comment by fvicaria** [comment]
This is not a server issue. It's a client issue. There should be loads of info online on how to sort it.

**Comment by HeroMarine** [comment]
ok i'll look it up, thank you! :+1:
