### ISSUE TITLE
The Last Line Of Defense Bugged

### ISSUE THREAD

**Issue by Fierceangel07** [wow-mania/Redemption#392]
When you get into the cannon on the towers it looks like you are shooting out into the minions but it isn't leaving the tower and exploding right in front of the cannon.

**Comment by fvicaria** [comment]
Needs to confirm. It was working fine.

**Comment by AielloA** [comment]
I can confirm this, the explosion happens right on top of the cannon. The barrel is still around the cannon too, should it be doing that?

**Comment by Daethalion** [comment]
Confirmed.  The cannons are placed inside the tower mounts so there's no way to shoot out beyond the tower walls.

**Comment by fvicaria** [comment]
Fixed.

**Comment by mariogotze** [comment]
Bugged again.

**Comment by fvicaria** [comment]
The fix is going to be out on next release. Tomorrow or monday.
