### ISSUE TITLE
[Quest] Waterlogged recipe

### ISSUE THREAD

**Issue by hornista** [wow-mania/Redemption#392]
Quest Waterlogged recipe http://www.wowhead.com/quest=14203/waterlogged-recipe
Item http://www.wowhead.com/item=48681/waterlogged-recipe

Fishing up the recipe always the player to take and turn in a quest in Dalaran for 5 cooking tokens
This is a repeatable daily quest

Player cannot repeat the quest. Error 'you are already on that quest' msg.
No quest in quest log

.lookup shows the quest has been completed and rewarded,  player claims this was days ago.

Can remove quest and player can retake from the recipe to complete

**Comment by barfmachine** [comment]
there are two versions of it so it may be possible that the one fished up was the first quest version not the repeatable version :)

**Comment by wow-mania** [comment]
Made it repeatable.
