### ISSUE TITLE
[ITEM] Nibelung valkyrs won't attack

### ISSUE THREAD

**Issue by perlotk** [wow-mania/Redemption#394]
Hi, about 2-3 weeks ago, I noticed that when my staff Nibelung generates the valkyrs, they don't attack. They're stuck in the floor. 

I opened a ticket in-game for this and they asked me to post here.

Thanks!

**Comment by perlotk** [comment]
Hi - can you tell me how to test this please? It is still broken for me. Thanks!

**Comment by Emcitementz** [comment]
Will be fixed on the next update .. :)

**Comment by perlotk** [comment]
OK - thank you!
