### ISSUE TITLE
[Quest] Tome of Valor

### ISSUE THREAD

**Issue by Folgore22** [wow-mania/Redemption#396]
Started Tome of Valor by talking to Daphne Stillwell in Westfall. She walks forward a few yards, then says the enemies are coming and I'm supposed to defend here, but no enemies show up and then you can no longer interact with here.

Tome of Valor is a paladin quest line

**Comment by fvicaria** [comment]
Duplicate #357 Please search before entering new issues.

**Comment by Folgore22** [comment]
Oh sorry, search function searches automatically in "code" instead of "issues", didnt notice that.
