### ISSUE TITLE
ICC 25 HC Sindragosa

### ISSUE THREAD

**Issue by elagen** [wow-mania/Redemption#397]
hi, i would to report the issue on sindragosa 25 hc that during the air phase the melee still get chilled to the bone which is making it harder to nuke down the tombs and the casters are still getting unchained magic during this phase which is also making it harder to nuke down the tombs

during this phase of the fight the melee shouldn't get the chilled to the bone while hitting the tombs

**Comment by wow-mania** [comment]
For god's sake there was one right at the top.
Please read instructions before posting issues.
