### ISSUE TITLE
maul problem (druid bear form)

### ISSUE THREAD

**Issue by Radghar** [wow-mania/Redemption#398]
the ability maul (bear form) doesn't work correctly. After few seconds i press it the spell works and does damage

**Comment by genasi** [comment]
Thats how maul is supposed to work, it boosts the damage from your normal attack and isnt an ability of its own.

**Comment by Kalasbyxan** [comment]
Working as intended at 3.3.5 where the damage is applied onto the next melee attack. Closing.
