### ISSUE TITLE
[Raidboss] Ulduar 10 man Razorscale

### ISSUE THREAD

**Issue by MatthiasNicolai** [wow-mania/Redemption#40]
In the Ulduar bossevent of Razorscale are the Harpoons unclickable after they are marked as ready.
The NPC's go to the Harpoons as intended, the adds keep spawning and the harpoons are not useable.
For further questions ask Jensitoh, Dachdagger or Drakthes.

Kind regards, Jensit/Jensitoh

**Comment by Calebrimbor** [comment]
Closing the issue, this quest will be added to [Project](https://github.com/wow-mania/Redemption/projects/3).
