### ISSUE TITLE
Instance Bug: Stratholme - Gate Before Baron

### ISSUE THREAD

**Issue by mercymania** [wow-mania/Redemption#400]
If you wipe on Ramstein, the gate that closes off that area remains closed and players cannot return to attempt to fight him again. I believe the gate event triggers when the aboms are engaged while clearing the area. That gate needs to reset as open when the aboms die or if players wipe. Failing that a lever outside the gate to open it would suffice.

**Comment by Rushor** [comment]
there is a tc pr for this isse, the pr from tc can be merged here, it works fine with the pr

**Comment by fvicaria** [comment]
https://github.com/TrinityCore/TrinityCore/issues/6377
