### ISSUE TITLE
New Launcher Bug - Crash when re-enabling wod models

### ISSUE THREAD

**Issue by mercymania** [wow-mania/Redemption#401]
I disabled the wod textures to see my the old style. When I went to re-enable the launcher crashes. Restarting the launcher shows the wod texture box checked by they aren't actually enabled when I start the game. unchecking and rechecking the box consistently crashes the launcher.

Just an fyi I am running windows 7 64-bit

**Comment by fvicaria** [comment]
You need to do that with wow closed. If the files were already locked by wow it won't work.

**Comment by mercymania** [comment]
WoW was closed while doing this. I cannot re-enable the wod textures. I have no programs running. I start the launcher. The box shows as checked even though the textures are not enabled when I press play to start the client. I can uncheck the box and start the client with the old textures. When I exit the client and restart the launcher the box shows as unchecked. But checking it crashes the launcher. I don't know what else to say to describe the issue.

**Comment by fvicaria** [comment]
I am looking into this now.

**Comment by mercymania** [comment]
Just in case this info is useful. I reverted to the previous launcher and it is currently downloading "patch-Z.mpq" not sure if that is relevant to the issue.

**Comment by fvicaria** [comment]
I have uploaded a new one.
Please give it a try and let me know please.

**Comment by mercymania** [comment]
Still having similar issues. Maybe it's just me. If no one else is reporting the issue changing between the textures it might just be my machine/config. I can work around it and still play though. So if mine is an isolated case, I wouldn't spend too much time over it.

**Comment by fvicaria** [comment]
I have just uploaded another one.

**Comment by mercymania** [comment]
Whatever you did fixed it ty!
