### ISSUE TITLE
Thassarian (29799) gives way too many quests!

### ISSUE THREAD

**Issue by Synathy** [wow-mania/Redemption#403]
[Seen on Redemption]
As the title say, Thassarian (http://www.wow-mania.com/armory/?npc=29799) on the Alliance gunship in the Icrocrown area gives way too many quests at once.
![wowscrnshot_101116_112058](https://cloud.githubusercontent.com/assets/22718174/19276680/293f9b70-8fa5-11e6-920c-b441c818a151.jpg)

**Comment by wow-mania** [comment]
As is. You left all your quests to the end so you will get all of them plus dailies.

**Comment by Synathy** [comment]
Drag and Drop and his daily version are both there, somehow.
