### ISSUE TITLE
[Talent] Infusion of Light

### ISSUE THREAD

**Issue by Sheevamania** [wow-mania/Redemption#405]
Class: Paladin. http://www.wow-mania.com/armory/?class=2#spells:type=7

Talent: Infusion of Light. http://www.wow-mania.com/armory/?spell=53576

Your Holy Shock critical hits reduce the cast time of your next Flash of Light by 2147483.6 sec or increase the critical chance of your next Holy Light by 20%. In addition, causes your Flash of Light to heal targets with Sacred Shield for an additional 100% over 12 sec.

Issue: The talent isnt working, it doesnt even procs after a critical heal from Holy Shock.
Pls fix it ASAP this is very crucial for a Hpala for pvp and pve.

Edit: If i heal someone with Holy Shock and the beacon is on me i dont receive the healing from it, so the problem might be on Holy Shock itself (Spell).

**Comment by wow-mania** [comment]
Updated reverted.
