### ISSUE TITLE
[Glyph] Glyph of Seal of Light

### ISSUE THREAD

**Issue by Sheevamania** [wow-mania/Redemption#406]
Class: Paladin. http://www.wow-mania.com/armory/?class=2#spells:type=7

Glyph: Glyph of Seal of Light. http://www.wow-mania.com/armory/?item=41110

Use: While Seal of Light is active, the effect of your healing spells is increased by 5%.

Issue: The glyph isnt working at all.

**Comment by wow-mania** [comment]
Updated reverted.
