### ISSUE TITLE
List of problems :)

### ISSUE THREAD

**Issue by sWcz** [wow-mania/Redemption#406]
hi :)
I was playing for a while now on wow-mania and discovered a few problems, that might be anoying for some players. This list is from my point of view and is missing problems that I didnt find anoying...or that I already forgot :).

A) Questing

1) Everything (resp. every mob), that is summoned during any quest is summoned twice (I'm quite sure, that I'm not the first, that  brought this issue, but it's by far the most serious and anoying problem).

2) the q 'Boiling Point' in Borean Tundra is not working. The elementals when beaten change to friendly as supposed to...but the q wont recognize it and the objective is not completed. What's anoying is that they stay friendly for an absurd amount of time (20 minutes or so) probably also for other players. I think that it's part of a chain quest so...it should be fixed.
edit: worked when I was realy close to them...still the respawn time is too long :)

3) The quest 'Oh Noes, the Tadpoles' also in Borean Tundra works as supposed to, but in original there might be more than 1 little murloc in the cages (1-3). It makes it much faster to finish it and it's more balanced with the other quests in that area. So you dont have to kill 80 murlocs just to finish this one.

4) mobs (anywhere), that are patrolling, sometimes keep following the predefined trail when pulled...and casting while walking :D 

5) drop rate of quest items and quest giving items in Hellfire Peninsula (OL) seems to be much lower than is supposed to (but maybe I'm just that unlucky). For example I killed 16 Raging Colossuses and did not get a single Crimson Crystal Shard.

6) Every NPC summoner on the server is not linked with his demon pet. Unless attacked the pet just stand there and watch his/her master die. Then disapear as supposed to. Most of the NPC pets seems not to be linked to their masters anyway.

B) Dungeons

1) The Underbog - contains much less trash mobs than is supposed to. For example there are supposed to be 4 bog lords right before the 1st boss and there's none.

2) The Nexus - the respawn time for the book, that is an objective for a quest 'Have They No Shame?', is way too long...results in players backtracking one by one just to get the objective completed

3) Groups of mobs that are supposed to be linked, pets and masters, aso are often not linked, resulting in interesting pulls sometimes

4) Trip mines in Gnomeregan are defined as an extra mob and walking around :/

5) The NPCs in Blood Furnance are spawning the trip mines way too fast. While casting nova, the final boss is not supposed to follow tank.

C) Classes that I tried

1) Hunter
    - after using feign death auto attack si stucked sometimes.
2) Priest 
    - after using levitate there is not supposed to be a walking animation. The character should keep  the levitating animation (just like standing in water) even when moving.

D) other

Transmog drops on disconnect sometimes...results in loosing 5 maniac points

**Comment by wow-mania** [comment]
Please do not file multiple issues in one. This dooms the report to be never looked at.
Please split it in to separate one and check if they have not been reported yet first.
