### ISSUE TITLE
[Quest] You'll Need a Gryphon

### ISSUE THREAD

**Issue by pamshoney2003** [wow-mania/Redemption#41]
Upon receiving the Onslaught Gryphon Reins (item 40970), when you summon the gryphon, one of two things can happen:

1. If the gryphon is summoned and he is standing on the ground, he will not fly when pressing the space bar, only jump.
2. If the gryphon is flying when he is summoned, he will fly, but at only -85 speed. This takes a long time to get to the quest giver to turn in.

Workaround: Use a regular flying mount to get to the quest giver, then mount your Onslaught Gryphon, and turn in the quest.

**Comment by GMLucetta** [comment]
This has been tested extensively and is working as intended. Had no issues with getting the gryphon to fly or the speed of it.
