### ISSUE TITLE
It's all fun and games... not fixed... still broken

### ISSUE THREAD

**Issue by MotleyCode** [wow-mania/Redemption#412]
This issue hasn't been fixed

**Comment by wow-mania** [comment]
It is fixed. I have just checked and it;s not like this that you report a bug. You either comment on the closed one create another.

**Comment by MotleyCode** [comment]
Well, I'm here right now with another player and it ISN"T working

**Comment by MotleyCode** [comment]
Now it's working. 10/13/16 @ 1:30pm EST
