### ISSUE TITLE
[Quest] Across Transborea

### ISSUE THREAD

**Issue by Bobthewicked** [wow-mania/Redemption#414]
Quest: http://www.wowhead.com/quest=11930/across-transborea

When you accept the quest a Taunka'le Evacuee follows you.

NPC http://www.wowhead.com/npc=26167/taunkale-evacuee (Maybe http://www.wowhead.com/npc=26159/taunkale-evacuee not sure)

While escorting them to the quest location, they are supposed to emote at points along the way, including one that completes the quest requirements. The NPC does not currently do so, leaving the quest uncompletable.

**Comment by Echinaceax** [comment]
GM asked me to check this quest credit for them

all fine
https://i.gyazo.com/912c2d747ca423129cd06110ed53304f.mp4
