### ISSUE TITLE
The Drakkensryd (Part 6 of 8)

### ISSUE THREAD

**Issue by Mark-Colley** [wow-mania/Redemption#416]
Hi Guys,

When you get this quest to defeat the riders, the first issue is that as you get to the location on the drake you get kicked off the drake.
You can mount another drake with a rider on it using the harpoon however you cannot attack that rider as he EVADES your attacks.
You can harpoon to other drakes but every rider EVADES any attack, even if you attack a rider on another drake nothing happens.
So you cannot complete this quest

**Comment by iz0r0** [comment]
Same issue still persits can attack any rider all else jumping and landing works

**Comment by iz0r0** [comment]
Cant attack the riders still
but jumping between riders and landing works as it is supposed to

**Comment by wow-mania** [comment]
The target works but many times you will get "not in range" also.
