### ISSUE TITLE
The Oracle rep quest chains ( Friendly or enemy ?)

### ISSUE THREAD

**Issue by warrea** [wow-mania/Redemption#417]

**Comment by warrea** [comment]
in sholazar basin in the Mistwhisper refuge Area there is a quest chain related to THE ORACLES reputation
which it should be completed in order to get reputation but the minions and NPC s there are not friendly 
but Oracles main base is friendly i thought maybe its a area reputation bug janitor could fix

**Comment by Kalasbyxan** [comment]
This is an ongoing project. Await a fix in the future.
