### ISSUE TITLE
[Quest] Amped For Revolt! and Fringe Science Benefits

### ISSUE THREAD

**Issue by pamshoney2003** [wow-mania/Redemption#42]
Quest giver (Fringe Engineer Tesla - NPC 32430) does not have script or dialog to summon the bomber needed to complete the quest.

**Comment by Demonbacks** [comment]
Same as Fringe Science Benefits ID 13373, both quests are similar and can´t be completed.

**Comment by schwebs** [comment]
Finally the NCP will give you the Bomber, but you can not kill the "Gargoyl Ambusher", so you are dead when the first mobs occure.
