### ISSUE TITLE
[Quest] Ned, Lord of Rhinos... (11884)

### ISSUE THREAD

**Issue by ChemicalSerenity** [wow-mania/Redemption#42]
The Nedar npc spawns in two places simultaneously, one by himself at (48.2,40.3) and another where he's mounted on Lunchbox at around (46.5,44.3) and pats around. The quest can only be completed by killing Nedar and Lunchbox, so the standalone spawn will almost certainly cause confusion.

Repro steps:

- Pay the Neds a visit

**Comment by fvicaria** [comment]
Fixed.
