### ISSUE TITLE
Shadow Hold doesn't trigger dismounting/Indoor

### ISSUE THREAD

**Issue by muckyfright** [wow-mania/Redemption#422]
Felwood, Jaedenar, Shadowhold 35.7, 59.5. 

Doesn't trigger you to dismount once you enter the massive tunnle system that is Shadow Hold. One can stay mounted for days

**Comment by MrKandola1** [comment]
I have tried, multiple ways, even with a flying mount; to actually run around, (with a mount) inside, and all it does is dismount at the entrance. Norrell and I, had also tried to freeze you, and we were unable to do so, which also set off the Anti-Cheat alarms. 

-Murlin
(PM me about this in game, on your other account if you wish. Or Janitor can clear it up for you whenever he is free)

**Comment by muckyfright** [comment]
Hi Murlin

I didnt see anyone while flying in, it is possible that i was lagging
because i only saw people at the end of the tunnle which is quite a way in.
and also round about the time i got disconnected

**Comment by wow-mania** [comment]
Reopen if it is confirmed.
