### ISSUE TITLE
Quest Bug: If He Cannot Be Turned

### ISSUE THREAD

**Issue by mercymania** [wow-mania/Redemption#424]
This quest suffers from the bug that many quests do where two mobs are spawned instead if one. Not only is this an elite mob that's getting doubled, but the npc helper Vile's taunts are not working and he dies very quickly to the onslaught making completion of the quest impossible for a lone player and asking for help very difficult because its a phased quest. GM Tyreal told me to bug report this.

**Comment by fvicaria** [comment]
Duplicate
