### ISSUE TITLE
Dungeon Azjol-Nerub

### ISSUE THREAD

**Issue by JuliaLimaa** [wow-mania/Redemption#427]
All adds, in all dungeon are spamming a lot, they just dont stop appearing.
So its hard complete a dungeon like this.

**Comment by Kalasbyxan** [comment]
First boss: Krik'thir the Gatewatcher
The boss is guarded by three groups of three spiders. The pulls are successive, meaning that once you pull the first group an event has started. Each pull consists of a miniboss and two adds.
See https://www.youtube.com/watch?v=dbyPaztbdGg
18 Skittering infectors
Countless Skittering swarmers


ANUB'ARAK (http://www.wow-mania.com/armory/?npc=29120)
During this encounter, the following abilites and adds are being used. He burrows three times during the encounter. 

Impale (http://www.wow-mania.com/armory/?spell=53454)
Anub'ar Assassin (http://www.wow-mania.com/armory/?npc=29214)
Anub'ar Guardian (http://www.wow-mania.com/armory/?npc=29216)
Anub'ar Venomancer (http://www.wow-mania.com/armory/?npc=29217)
Anub'ar Darter (http://www.wow-mania.com/armory/?npc=29349)

The fight should look like this (https://www.youtube.com/watch?v=tFWTsp8yv7k):
First Burrow: 2 anub'ar assassins, 1 impale, 2 anub'ar guardians, 1 impale, 2 anub'ar assassins.

Second Burrow: 2 anub'ar assassins, 1 impale, 2 anub'ar guardians, 1 impale, 2 anub'ar assassins, 1 impale, 2 anub'ar venomancers (heroic mode only), 1 impale, 2 anub'ar assassins

Third Burrow: 2 anub'ar assassins and 1 anub'ar darter, 1 impale, 2 anub'ar guardians and 1 anub'ar darter, 1 impale, 2 anub'ar assassins and 1 anub'ar darter, 1 impale, 2 anub'ar venomancers (heroic mode only) and 1 anub'ar darter, 2 anub'ar assassins.


At the moment, each time Anub'arak burrows and the amount of Anub'ar Assasssins spawning is around 16-20, not 2. Also, the Impale should happen on 1 person, it happens on every person.

**Comment by JuliaLimaa** [comment]
Well, but its not like that. When i say a lot of adds its a lot of adds!
In all dungeon... Not only on bosses!!

**Comment by Ebonlox** [comment]
The Anub'arak fight is still (or is again) broken. Too too many adds when he burrows and too many impales. It is nearly impossible for a group of appropriately leveled and geared players.
