### ISSUE TITLE
Fingers of Frost (Mage Frost Talent)

### ISSUE THREAD

**Issue by funkmasta** [wow-mania/Redemption#429]
Fingers of Frost is an effect that should last for the next TWO spells, however it currently only lasts for 1 spell, making it only 50% functional. Fingers of Frost is in the Frost talent tree for Mages.

**Comment by Kalasbyxan** [comment]
Confirmed. 

Fingers of Frost (http://www.wow-mania.com/armory/?spell=44545) buff is removed after one spell is cast, even though it should have two charges.
