### ISSUE TITLE
[Quest] Kaw the Mammoth Destroyer (11879)

### ISSUE THREAD

**Issue by ChemicalSerenity** [wow-mania/Redemption#43]
You can take the quest and mount a bull elephant fine, but Kaw doesn't mount his elephant. This requires you to dismount to kill his elephant (your elephant won't engage his directly) and then take Kaw out in ground combat.

[As seen in this video,](https://www.youtube.com/watch?v=x2sFMvXdg4A) Kaw *should* run to his mount as the encounter begins. Instead he stays still (and not attackable) until his mount is killed, at which point he engages.

Repro steps:

- Start the quest
- Find a healthy bull and mount up
- Go to the encounter location
- Attempt to engage Kaw
- Fail
- Attempt to engage his mount
- Fail
- Dismount, kill his mount
- Fight Kaw, who finally figures you're worth his time

**Comment by fvicaria** [comment]
If the quest can be completed as is at the moment I will postpone the fix until I have more time.
