### ISSUE TITLE
Issue with Drakkensyrd

### ISSUE THREAD

**Issue by Tundrik1982** [wow-mania/Redemption#432]
I can get the quest and im flown there on a drake but when I harpoon or use the mouse click to jump onto a drake to attack and kill the rider it puts me there but doesn't let me attack the rider. They either evade or just not in range. This makes the quest impossible.

**Comment by fvicaria** [comment]
It does work and it has been improved for next patch. You have to keep changing from drake to drake some will let you hit some will not. Wait for next update and reopen.

**Comment by Fiky995** [comment]
Most of mobs still dont work, when i try to attack them it says "Out Of Range" even tho im a mage and my frostbolt has a 36 yard range. Its doable but it takes a LOOOOONG time.
Also theres no way to get off the drake except by dismounting and falling to death
