### ISSUE TITLE
[Quest] Battle at Valhalas: The Return of Sigrid Iceborn

### ISSUE THREAD

**Issue by Marilock** [wow-mania/Redemption#434]
When i accept the quest the NPC Sigrid Iceborn spawns but can't be interacted with, she doesn't attack and can't be attacked, making the quest impossible to complete.
I tried attacking her protodrake, but the result is still the same, the npc spawning impossible to be attacked.

**Comment by wow-mania** [comment]
http://www.wowhead.com/quest=13213/battle-at-valhalas
