### ISSUE TITLE
[Quest] Hungry Nether Rays

### ISSUE THREAD

**Issue by Arrakoan** [wow-mania/Redemption#435]
The quest gives me a box which i need to open to summon Nether Rays. Near Skettis in Terokkar Forest (Location) Are Blackwind Warp Chasers. My quest objective is open the box to summon a Hungry Nether Ray http://www.wowhead.com/npc=23439/hungry-nether-ray and kill the blackwind warp chaser http://www.wowhead.com/npc=23219/blackwind-warp-chaser and wait for the Nether rays to eat it after, bringing back a meal to feed them. This should be done 10 times. The Hungry Nether rays CAN be summoned but do not eat the Blackwind Warp Chasers once u kill them. I tried if looting them changes anything, but it does not. They simply do nothing thus gathering the Nether ray meals 0/10 is not possible.

**Comment by wow-mania** [comment]
http://www.wowhead.com/quest=11093/hungry-nether-rays
