### ISSUE TITLE
Debuff from set mage

### ISSUE THREAD

**Issue by Silva69** [wow-mania/Redemption#437]
The debuff call "pushing the limit"( more 12% haste for 5 seconds) from the set mage, are bug because is appears in the beggining when you cast one of the three spells , and only must appears when the spell is consumed.

exemple: im arcane mage, when i cast arcane missiles, the debuff already appears, and only must show when i end my spellcast

**Comment by wow-mania** [comment]
I have no idea what you are talking about. Please send link to the spells or items.
