### ISSUE TITLE
[Quest] Chains of the Anub'ar

### ISSUE THREAD

**Issue by Tapenade** [wow-mania/Redemption#439]
ID#12064
On this server : You have to collect some fragments from each mobs. Sinok is correctly spawned, but there are 2 Tivax at 2 different places. The 3rd mob, Anok'ra, isn't spawned at all. I assume that one of the Tivax is spawned in Anok'ra stead.

**Comment by fvicaria** [comment]
They are all there. The one that has two you only have to kill one of them.
