### ISSUE TITLE
[Quest] Saragosa's End (11957)

### ISSUE THREAD

**Issue by ChemicalSerenity** [wow-mania/Redemption#44]
When you teleport to the platform where Saragosa is supposed to descend and then transform into humanoid form, nothing happens instead. Saragosa never appears.

Note - her human form is often found at ground level in a non-attackable state. When one tries to attack, it says "out of range". The human form appears to be "falling" for an instant when it spawns, which may be significant.

This quest failure blocks the rest of the quest chain.

Repro steps:

- Obtain the mana crystals necessary to gain this quest
- Talk to Keristrazsa and tell her you're ready to confront Saragosa
- Be teleported to platform
- Wait around a while for a dragon lady that never comes

**Comment by Upperfoot** [comment]
Related Issue: https://github.com/TrinityCore/TrinityCore/issues/8767
Patch: https://github.com/TrinityCore/TrinityCore/commit/e9d97466dafaabe68dff00820b6366b928ee5b51

In reference to Smart AI Script to spawn Saragosa on gossip complete.
