### ISSUE TITLE
[Spell] Hunter's Deterrence

### ISSUE THREAD

**Issue by Ashamedlol** [wow-mania/Redemption#444]
https://www.wow-mania.com/armory/?spell=19263 , It sometimes decides to not work and makes the hunter attackable which causes a huge disadvantage for the hunter.

**Comment by Kalasbyxan** [comment]
Would need further information regarding this issue. What attacks are made that are ignored by Deterrence?

**Comment by Ashamedlol** [comment]
Only attacks that can exceed parry/dodge mechanics should be possible, such as Overpower and Counterattack.

I was dueling a hunter on a paladin and I hit him around 5 times while he's in deterrence, so it doesn't seem to be working sometimes.
