### ISSUE TITLE
Mana strudels and possibly other food not healing

### ISSUE THREAD

**Issue by MrNorrell** [wow-mania/Redemption#447]
Mana strudels increase mana but not health. I had to conjure food as well as strudels to get my health back up as well as mana. This is a new issue as they were previously working fine.

A player pointed out that the following items are affected by a similar bug:
shoveltusk soup
shoveltusk steak

They do not cause you to eat (for health) and it's been reported they don't add buffs they should either (although I got "well fed" buff after eating one of each).

**Comment by wow-mania** [comment]
This fixed but it did not go on today's update. I will push it Wednesday.
