### ISSUE TITLE
Invalid Target

### ISSUE THREAD

**Issue by marshalldavis** [wow-mania/Redemption#448]
I spotted a rare spawn (Icehorn) and went to kill it. I couldn't attack it directly. After trying a few spells, it got close and aggroed on me. While attacking me, it was still an invalid target to my direct attacks. I was able to use AoE spells and thorns (I'm a druid), and those brought him down. 

Once he was down, I could open the loot interface and there was some really nice items in there. I couldn't loot any of it though. 

I called a GM and he thought it was odd. He couldn't offer any help, such as respawning the rare, as it had a chance of destabilizing the server. So, at that point, I was SOL. He left.

I went to town to empty bags and I couldn't sell anything. The inventory box opened up, but I couldn't sell. 
I called another GM (the first had already went offline) to check that out. He was able to sell stuff to that NPC. I couldn't.

A few things we tried:
/reload - didn't work
/logout - didn't work
restart the client completely - This worked.

If I'm needed to test things out, I'm Thanduil on the server.

**Update: I believe I found the culprit. When I go into my video options and choose maximize window, this problem happens. I went back and forth and it comes and goes with that setting.**

**Comment by wow-mania** [comment]
Thanks for the info.
