### ISSUE TITLE
[Quest] Warsong Supplies

### ISSUE THREAD

**Issue by Kalasbyxan** [wow-mania/Redemption#449]
In the quest (http://www.wow-mania.com/armory/?quest=6571), players need to visit Wharfmaster Lozgil (http://www.wow-mania.com/armory/?npc=4631) to pick up a Warsong Axe Shipment (http://www.wow-mania.com/armory/?item=16745).

Wharfmaster Lozgil does not provide the quest item.

**Comment by Emcitementz** [comment]
It is working fine, you need to pick it up from the docks where the crate will be found.
