### ISSUE TITLE
[Quest] A Race Against Time (11671)

### ISSUE THREAD

**Issue by ChemicalSerenity** [wow-mania/Redemption#45]
Quest gives you a Beryl Shield Detonator to destroy the shield around Inquisitor Salrand, allowing you to complete the quest. However, tossing the bomb does nothing. Attempting to engage Salrand melee results in the message "You are too far away!", which perhaps means there's a difference between where the client thinks the NPC is, and where the server does (could be a similar error to the Saragosa bug I just submitted.)

Repro steps:

- Someone set up Salrand the bomb
- It's not very effective
- Her HP remains over 9000
- Haz a sad
- (Fill in meme reference of choice here)

**Comment by wow-mania** [comment]
duplicate #20
