### ISSUE TITLE
[Quest] To Star's Rest

### ISSUE THREAD

**Issue by genasi** [wow-mania/Redemption#45]
When doing the quest To Star's Rest (id=12440) you are supposed to talk the flight master at Wintergarde Keep to get a free flight to Star's Rest, but when I try talking to him I only get the option for a regular flight master.
This has happened on both Corbin, worgen druid, and Daeron, Draenei shaman, so it isnt character specific and it isnt about the new "races".

The flight master in question is called Rodney Wells
wowhead quest link: [http://www.wowhead.com/quest=12440/to-stars-rest](http://www.wowhead.com/quest=12440/to-stars-rest)

Are you using our client? Yes
Are you using the latest Launcher? Yes

**Comment by Oriden** [comment]
Fixed
