### ISSUE TITLE
Wintegrasp Vehicles

### ISSUE THREAD

**Issue by Sheevamania** [wow-mania/Redemption#450]
There's a big problem with wintergrasp vehicles (Siege Engines and Catapults)

Catapults are doing 12k per tick of the ability Flame Breath, wich can completly one shot a player, im pretty sure its not as its supposed to be.

Siege engines are unable to move, after you build a siege engine you cant take it out of the workshop you can only get into the turret and shot from there.

With this bugs its absolutely impossible for the faction who is attacking to win the battle, so pls make this a priority.

Thanks

**Comment by wow-mania** [comment]
I need spell ID or NPC id please

**Comment by wow-mania** [comment]
As is. Also there is no logic on how this can be one-sided as it will be the same for both factions.

**Comment by Sheevamania** [comment]
Spell ID for Catapults Flame breath: http://www.wow-mania.com/armory/?spell=50989

NPC ID for Siege Engines: http://www.wow-mania.com/armory/?npc=34776

**Comment by wow-mania** [comment]
This has been fixed. Should be pushed tomorrow (28/10)
