### ISSUE TITLE
It's all fun and games

### ISSUE THREAD

**Issue by Arrakoan** [wow-mania/Redemption#451]
The ''It's all fun and games'' quest, in this quest u have to kill the Ocular above the Shadow Vault in Icecrown. It sometimes bugs and enters an ''Evade'' state and because of it u cannot use the eyesore blaster. It is use-able in gm mode but he will absorb the damage because of this state. After some testing with both Alliance and horde chars we found out it's the Ocular that doesn't work, instead of the quest/blaster. It is also possible sometimes that the eye is not selectable at all. Shorter said, it sometimes bugs.

**Comment by Arrakoan** [comment]
We are now aware of all fun and games and no longer needs reports, seems

**Comment by Lemayonaise** [comment]
seems to be bugged atm, tried several times on my gnome, was also confirmed by another player trying to do it at the same time. item starts the channel but interrupts it immediately and it does no damage to the eye
