### ISSUE TITLE
Ferocitas the Dream Eater

### ISSUE THREAD

**Issue by custos7** [wow-mania/Redemption#453]
Windows 10

Killing the NPC - "Ferocitas the Dream Eater"[npc=7234] for the quest with same name "Ferocitas the Dream Eater"[quest=2459] doesn't provide the necessary quest item "Tallonkai's Jewel". [item=8050]

Maybe you can add this item to the loot table of the creature, or if that is broken, to the Gnarlpine Mystics [npc=7235] which are also required to finish the quest. Unless it's more complicated than that. Thanks for all the work with the server by the way!

**Comment by Emcitementz** [comment]
There's nothing wrong, this quest is working fine, you'll have to loot a clickable necklace on this NPC and then open it to receive the "Tallonkai's Jewel".
