### ISSUE TITLE
NPC's Killing Quest Mobs

### ISSUE THREAD

**Issue by mercymania** [wow-mania/Redemption#454]
In areas where npc's battle mobs, the npcs are supposed to do MUCH reduced dmg vs mobs. Currently they kill mobs with relative ease and make finishing some quests difficult. Areas where this can be seen include the area on the isle of queldanis where players are supposed to bomb the demons. The scourge are killing many of the required demons before the player can making finishing this quest very difficult. Another area where this can be observed is Farshire in Borean Tundra. The farmers kill the scourge ghouls fairly quickly making it difficult to kill the 14 necessary for the quest. Another area in Borean where this can be seen is at Kaskala where the Kakalan Defenders kill the Kvaldir Raiders far too quickly.

**Comment by fvicaria** [comment]
Duplicate.
