### ISSUE TITLE
Can't login. Stuck: Retrieving character list

### ISSUE THREAD

**Issue by Fierceangel07** [wow-mania/Redemption#456]
I can't get into the game it just stays at the Retrieving character list. 
![wowscrnshot_082315_105754](https://cloud.githubusercontent.com/assets/13836339/9428715/da0180e8-4985-11e5-8f1e-9cd9b7a3f13e.jpg)

**Comment by Fierceangel07** [comment]
It just came up. After about 5 minutes of leaving it there on the screen my character list came up. It has done this before in the past but not this long.

**Comment by fvicaria** [comment]
Should be fixed on next release
