### ISSUE TITLE
[Quest] Chicken Clucking for a Mint

### ISSUE THREAD

**Issue by Kalasbyxan** [wow-mania/Redemption#457]
The quest (http://www.wow-mania.com/armory/?quest=8354) is completed by doing a /chicken emote at the npc (http://www.wow-mania.com/armory/?npc=6741). This quest is part of a bigger quest (http://www.wow-mania.com/armory/?quest=8312).

**The quest gets completed but Innkeeper Norman does not recognize it as completed, making it unable to turn in.**

**Comment by wow-mania** [comment]
Should be fixed on tomorrow's update.
