### ISSUE TITLE
[Quest] Breaking Through (11898)

### ISSUE THREAD

**Issue by ChemicalSerenity** [wow-mania/Redemption#46]
After teleporting to the 2nd level to fight Prince Valanar, there's no way to get back to the main level or to ground level. The only way out is to stone or die.

This is a relatively minor bug - the quest is entirely doable, it's just a pain afterwards trying to get out to turn it in.

Repro steps:

- Teleport to the first level
- Run up the ramp so's to activate the teleporter to the second level
- Do what you need to do on the second level
- Get concerned when you find you cannot teleport back to the first level
- Run around like a twit trying to find an exit that doesn't exist

**Comment by fvicaria** [comment]
Fixed (sort of) with a custom portal between the two level.
