### ISSUE TITLE
[SPELL] CHARGE/INTERCEPT

### ISSUE THREAD

**Issue by Bugreports** [wow-mania/Redemption#461]
from lv 1 to 80 Charge and Intercept are BUGGED(bad programing) they should Charge downhil without hitting the floor on the charge path ,same as intercept spell ,well .. IN FACT theh do : You cast Charge/intercept on a target clif(example : 2 metters down) and  you HIT URSELF on the floor downhill and THEN u charge the mob...... that wasn't like this in the Original WoW and is a HUGE bugg for warriors PvE or PvP(on Pve server like this)

Please i speak of behalf ALL the warriors have the same bugg and don't care to report cuz i have seen happen to others warriors and i was "LOL" cuz Full HP on the warrior then half one and then charge/intercept...

Another thing very important.. HUGE ..... warrios could charge/intercept  underwater,GM are aware of this and their response is " why u need charge underwater to pvp if here is PvE server" well then.. how do i charge a mob under water(PvE)?

Please.. fixt that enormous bugg on this server

Thanks and best regards to the amazing job of all the GM and Janitor server ;)

**Comment by wow-mania** [comment]
TC 11526

This will be looked at before next update.

**Comment by Bugreports** [comment]
Ty!!!

**Comment by fvicaria** [comment]
Merging the issues. #143
