### ISSUE TITLE
[Spell] Hunter auto shot

### ISSUE THREAD

**Issue by rafirstgod** [wow-mania/Redemption#462]
1. I just found and learned find fish/ now that finished fishing i wanted to change it back to find minerals and for my surprise i couldn't ... the only way i can change it back and go to find nothing and move again for find humans/beasts minerals; but every time i go to fishing=> i change for my fishing pool and back to my sword i get the same bug on the tracker... find fish stayed the same doesn't change to weapon find minerals in my case .
2. second problem is that some times auto shot doesn't work ... i need to use a skill just to activate basic shot...

**Comment by huqboss** [comment]
in addition to problem nr 2:
problem with impossible to AA on hunter happends when enemy do some "strange movement", like for example BQ air phase - after this AA after right click doesn't work, can attack only with abilities. Changing target is fixing this problem (after 1AA on another target u can back to 1st one). It's a big problem for example at BQ, when u have no other target to attack.

**Comment by rafirstgod** [comment]
to be more exact about 1 point ... you can't change from find fish to find minerals ...
