### ISSUE TITLE
PvP combat

### ISSUE THREAD

**Issue by empressnyx** [wow-mania/Redemption#464]
Putting aside the PvP "baiting" that people do (flagging themselves and running into my fighting area while I'm questing, forcing me to flag, and then ganking me like a giant turd waffle) the PvP flag gets stuck. turning it off allows for the countdown timer to begin, but once the timer ends, the flag doesn't go away. It requires a total relog of the game (a /reload does not work).
Is it possible to implement a "no pvp ever" option? Like... shut it off. I will forever abstain from pvp. I want to be some sort of pvp deity. Pure and clean from the evil temptations of pvp. I can waive any right to even request to have it turned back on. I just want to play the game without getting harassed by people who thinks it's fun to force me to flag when I'm not paying attention to pvp. This is the worst. Those people are the worst. There are PvP servers for that. But the least that I need is the ability to unflag properly.

**Comment by wow-mania** [comment]
We have improved the system now by no allowing players lower than 80  or player inside sanctuaries (Stormwind, Orgrimmar, etc) to be flagged.
