### ISSUE TITLE
Rejuvanation and Wild Growth not popping.

### ISSUE THREAD

**Issue by jurrianvg** [wow-mania/Redemption#465]
Hello GM, i might found something like a bug, The ICC reputation ring and the from frost buyable trinket  ( Purified Lunar Dust) Won't proc when I cast Rejuvenation or Wild Growth. While it says:"Equip: Your helpful spells have a chance to increase your spell power by 285 for 10 sec.  This only procs when I cast Regrowth or Nourish. Same with the Purified Lunar Dust. Lightweave Embroidery tells:"Giving you a chance to increase you spellpower for 295 (15secs) when CASTING a spell. it procs when i cast Rejuvanation. So i think the other should work too right? 

-Lotus

**Comment by wow-mania** [comment]
Item shows a chance to proc independent of the spell you use.
