### ISSUE TITLE
[Quest] Incoming Gumdrop

### ISSUE THREAD

**Issue by Theleiba** [wow-mania/Redemption#466]
The quest "Incoming Gumdrop" given by Talvash del Kissel in Ironforge and requiring the quest "Hallow's End Treats for Jesper!" given by Jesper in Stormwind should be completed when you target Talvash del Kissel and do the /train emote. This however doesn't seem to work.

**Comment by wow-mania** [comment]
Quest works fine. Change position and try again.
![image](https://cloud.githubusercontent.com/assets/12248683/19831488/ced50ec4-9e02-11e6-8164-552127910ffe.png)
