### ISSUE TITLE
[Quest] Threat from above

### ISSUE THREAD

**Issue by huqboss** [wow-mania/Redemption#468]
Now, after "adjustments" works much worse - cultist bombardiers spawn almost immediatelly, but invisible and untargetable, do dmg, can hear their voices, but can't attack, becoming visible after death of player or chillmaw. Still run to same spot evading attacks and despawn there, even during fight. 8 Time bombs instantly spawned also sux.

**Comment by wow-mania** [comment]
There has been absolutely no change in server as I tested multiple times and it works perfectly.
