### ISSUE TITLE
[Vendor] not selling Formula: Runed Adamantite Rod

### ISSUE THREAD

**Issue by hattrijck** [wow-mania/Redemption#469]
Rungor in Terokkar Forest should sell Formula: Runed Adamantite Rod which he doesn't.

http://www.wow-mania.com/armory/?item=25848#sold-by-npc

**Comment by wow-mania** [comment]
The item is sold correctly by both NPC. It carries only one item and it is refreshed every 12h. I will checked to be refreshed at every 6h.
