### ISSUE TITLE
[Quest] Gluttonous Lurkers

### ISSUE THREAD

**Issue by Kalasbyxan** [wow-mania/Redemption#474]
The quest (http://www.wow-mania.com/armory/?quest=12527) is completed by looting Zul'Drak Rats by clicking on them, throw five rats on a Lurking Basilisk (http://www.wow-mania.com/armory/?npc=28145) turning them into a Gorged Lurking Basilisk and looting it on click, giving you Basislisk Crystals (http://www.wow-mania.com/armory/?item=38382). 

**The rats aren't looted when clicked on, they disappear.** I added five rats and turned the Basilisk into Gorged and **it wasn't looted either**.

**Comment by Bozhkata** [comment]
Hi guys,so i was doing this quset and i was confused when i tryed to loot the rats but they just disappeared i tried everything and found out that you can loot them only when mounted,but that was not the main issue.When you throw 5 rats at the Lurking Basilisk it just dissapears and you can't loot it.
