### ISSUE TITLE
[Quest] Will of the Titans - 12705

### ISSUE THREAD

**Issue by pamshoney2003** [wow-mania/Redemption#48]
Quest to kill Frenzyheart Attackers. Player has Exalted with the Oracles and Hated by the Frenzyhearts. Players can not directly or indirectly (AOE spell) attach the Frenzyheart NPCs.  Also, the Frenzyheart and Oracle Factions are not fighting each other.

**Comment by Calebrimbor** [comment]
Closing the issue, this quest will be added to [Project](https://github.com/wow-mania/Redemption/projects/2).
