### ISSUE TITLE
purchase

### ISSUE THREAD

**Issue by mbdlf95** [wow-mania/Redemption#485]
Just bought the 5000 gold card and still there is nothing on my account. Maybe some result will be nice

**Comment by fvicaria** [comment]
Can you contact me on skype or in-game this not the right place for it.

**Comment by mbdlf95** [comment]
okey whats skype name could i add?

**Comment by fvicaria** [comment]
Wow-mania.com send me your email or transaction id please.

**Comment by fvicaria** [comment]
Wow-mania.com send me your email or transaction id please.

**Comment by mbdlf95** [comment]
m.baardolf95@gmail.com

**Comment by fvicaria** [comment]
I found it. Give me the name of your char and i will send it to you. Sorry for the trouble some hic-up of the server.

**Comment by mbdlf95** [comment]
bdlf is my character name. thank you! and no problem

2015-08-25 20:18 GMT+02:00 Janitor <notifications@github.com>:
