### ISSUE TITLE
Instant Shadow Bolt procs

### ISSUE THREAD

**Issue by proroka999** [wow-mania/Redemption#486]
Character Name: Andwin
Broken talent and glyph: Nightfall and Glyph Of Corruption
Together I am supposed to have a 8 percent chance of when damaging with Corruption or Drain Life to get an instant Shadow Bolt proc. It used to occur all the time. Now it happens every hour or so.

**Comment by huqboss** [comment]
works fine for my wlock (using only Nightfall), proc is accurate with chance for it
