### ISSUE TITLE
[Quest] Rifle The Bodies

### ISSUE THREAD

**Issue by rafirstgod** [wow-mania/Redemption#490]
Quest: Rifle The Bodies
Location: Northrend/ Dragonblight/ Moonrest Gardens
Task: Find the Moonrest Gardens Plans and return them to the Image of Archmage Modera at Stars' Rest. 
Solution: After the upheaval at the ruins, the ghosts of the Highborne rose up and decimated half of the mage hunters present. Go rifle their corpses for clues. 

Problem: I searched all the bodies around 2-3 times(40-50 bodies) and nothing no drop.

**Comment by IvanLlanas** [comment]
I just looted all the bodies, twice, and no plans were found.
