### ISSUE TITLE
[Quest]It Rolls Downhill

### ISSUE THREAD

**Issue by rafirstgod** [wow-mania/Redemption#493]
Quest: It Rolls Downhill
Quest Url: [Link](http://www.wowhead.com/quest=12673/it-rolls-downhill)
Location: Northrend/ Zul'Drak/Reliquary of Pain
Task: Overlord Drakuru in Voltarus wants you to use the Scepter of Suggestion on the Blight Geists and then order them to harvest 7 Blight Crystals. .
Solution:Tame the Blight Geists with the rod... now you have them as a pet with pet bar .... activate from the bar to collect the Blight Crystals.
Problem: Button doesn't work ... the Blight Geists don't move to collect .

**Comment by wow-mania** [comment]
Search before creating new issues #334
