### ISSUE TITLE
[Quest] Goblin invaders

### ISSUE THREAD

**Issue by Taurii** [wow-mania/Redemption#494]
The NPC doesn't give this quest. I did all the steps to unlock this quest. I did try in only 1 toon.

**Comment by Rushor** [comment]
you need to do first http://wotlk.openwow.com/quest=1061 in order to get the quest http://wotlk.openwow.com/quest=1062

**Comment by Taurii** [comment]
okay so it wasn't showing on tracker but yes that did the trick thanks a lot!
