### ISSUE TITLE
Conjured Mana Biscuit

### ISSUE THREAD

**Issue by Fiky995** [wow-mania/Redemption#499]
The mana biscuits created from Conjure refreshment rank 1 dont give health, but only mana.
Tooltip says health and mana

**Comment by Rushor** [comment]
```sql
UPDATE item_template SET spellcategory_1=0 WHERE entry IN (
34062,
34125,
34126,
34748,
34749,
34750,
34751,
34752,
34754,
34755,
34756,
34757,
34758,
34759,
34760,
34761,
34762,
34763,
34764,
34765,
34766,
34767,
34768,
34769,
34780,
39691,
42942,
42993,
42994,
42995,
42996,
42997,
42998,
42999,
43000,
43001,
43268,
43518,
43523,
43652,
44953,
45932);
```

**Comment by Mark-Colley** [comment]
This appears to be the same with most foods that give health and mana.
I use cooked Dalaran Stew or whatever its called for a health boost for stamina, I get the +40 stam buff, but whilst you are eating your health is not topped up.
I have to eat normal food after to increase health to topped up level.

**Comment by wow-mania** [comment]
It was pushed this morning. Thanks @Rushor
