### ISSUE TITLE
[Class Spell] Paladin's Consecration

### ISSUE THREAD

**Issue by Ashamedlol** [wow-mania/Redemption#5]
This spell is an aoe spell that puts an area that damages nearby enemies, however on this server it's scripted to ONLY hit visible enemies that enter the area and are around you, does not hit people who are invisible which is not proper.

**Comment by Lokkek** [comment]
Invisible (mage, warlock pet) or stealthed?  As a rogue from content, and live, I was and am able to open on a paladin in between consecration ticks.  In so much that consecrate is not an aura of effect like flare, but more like a placed effect which acts similar to blizzard, flamestrike, volley, hellfire etc

If I get lucky, and with some speed (enchant or sprint) I am able to move into melee range of the paladin in between ticks of consecrate damage and still maintain stealth, as I haven't taken any damage (ticks).  I also do not drop stealth if I resist any damage ticks.

**Comment by Calebrimbor** [comment]
Status BugTracker set as 'Pending'.

**Comment by Calebrimbor** [comment]
Status on BugTracker set as 'Fixed'.
