### ISSUE TITLE
That's Abominable! - vehicle does not appear

### ISSUE THREAD

**Issue by lcmclaughlin** [wow-mania/Redemption#500]
When summoning the abomination in this quest, the abomination appears as a pet (like a warlock might have, except with no ability bar) instead of a vehicle as I believe it's supposed to. This makes it impossible to complete the quest as you're supposed to use the vehicle's abilities to destroy a certain number of mobs by blowing them up.

**Comment by wow-mania** [comment]
Duplicate #29
