### ISSUE TITLE
Volatility

### ISSUE THREAD

**Issue by lcmclaughlin** [wow-mania/Redemption#501]
Doing this quest, it's possible to collect the helms, bones and armor, and to create the dummy and destroy a dragon, but credit is only given intermittently - I got credit for 1 out of 7 or 8 attempts. I haven't been able to figure out a pattern for when it works and when it doesn't.

**Comment by Mark-Colley** [comment]
I had the same issue with this quest. 
I managed one test successful and then the next 10-12 did not work, so I abandoned the quest.

Maddy

**Comment by fvicaria** [comment]
Should be fixed. The odd one still may fail if too far away.
