### ISSUE TITLE
I died 

### ISSUE THREAD

**Issue by EliteSAGamer** [wow-mania/Redemption#502]
I was doing a dungeon and we all got killed, the tank left and then someone ells left so i left aswell and i spawned at the place where people spawn where they die, but i was on a flying mount and i could not talk to the Spirit healer to revive myself at the place. Don't know if its a common bug or if im just lucky, (sorry i did not take any screenshots) -Opra

**Comment by wow-mania** [comment]
You have to fly back to your corpses.
