### ISSUE TITLE
data regards to the low proc chances

### ISSUE THREAD

**Issue by firedervil1986** [wow-mania/Redemption#508]
i did some intense testing in regards of thefailing procs that run arround 

1: Black Bruise (icc 25 fistweapon) procchance 0,2% procchance even thou it should be 2%

2:Needle-encrusted scorpion (forge of souls HC trinket) proc Chance 0,61% actually should be 10%

3 Hack and slash (combat roque ability)  0,7% Chance  actual Chance should be 5%

4:glyphe of sinister strike (roque) 6,5% should be 50%

5:heartpierce (icc 25 dagger) zero out of 1000 hits no proc

6:putrified lunaric dust (trinket for Emblems of frost) 7 procs from 290 direct heal spells (healing wave shaman) equals to a Chance of 2,4 (couldnt find anyinformation about the actual proc Chance but it seems to low.

for all procs i counted in the internal cooldown and waitedfor it to run out

I hope it will help to analyse or see the Problem in regards to the missing procs

**Comment by Agentbrut** [comment]
bump, Bloodsurge
