### ISSUE TITLE
Ogrila

### ISSUE THREAD

**Issue by neoserenity** [wow-mania/Redemption#510]
There seems to be some issues with a few of the quests in Ogrila. "Our Boy Wants To Be A Skyguard Ranger" and "An Apexis Relic" so far. The Apexis Relic stations for the "Simon" quest dont accept the apexis crytals, and neither do the fel crystal forges.

**Comment by neoserenity** [comment]
"Guardian of the Monument" seems to be bugged. Can use the monument to summon him, but when he dies he doesn't drop his head.

**Comment by Emcitementz** [comment]
Our Boy Wants To Be A Skyguard Ranger is working fine, forges accept the crystals as they should.

**Comment by wow-mania** [comment]
The other on has been logged separately.
