### ISSUE TITLE
[World] Griphone bug

### ISSUE THREAD

**Issue by rafirstgod** [wow-mania/Redemption#512]
Was in Nagrand near Camp Hate and i took a quest for scouting the camps  there ... all nice and good ... now every time i log out or get disconnected wile i'm flying some were with the griphone i get sent flying off the map or some were else ... for ex now i started flying from dalanar to mao'ki harbor and ended up off map in borean tundra and been there for 10 min waiting to see what happens next ... this is 3-4 th time that happens .  in the end ... i was taken to kalimdor ... died of fatigue near it ... released and ended up in westfall .

**Comment by wow-mania** [comment]
Cannot reproduce.
