### ISSUE TITLE
Random Dungeon Finder

### ISSUE THREAD

**Issue by Daethalion** [wow-mania/Redemption#518]
In the event that a dungeon party is filled using the RDF and a person does not accept before the timer runs down, members that accepted are not returned to the front of the queue as they should be.  Instead the healer and tank will be picked up by the next set of 3 dps that are queued, and the dps who were in line will get thrown back into the queue.

This basically means that one afk punishes the entire party, in the case of dps, it likely means the loss of a dungeon run for the day.

**Comment by dimman321** [comment]
Works like a charm for me, maybe this was one time only thingy?

**Comment by fvicaria** [comment]
Not an issue.
