### ISSUE TITLE
High Justice Grimstone

### ISSUE THREAD

**Issue by kinarth** [wow-mania/Redemption#52]
During the High Justice Grimstone fight in Black Rock Depths (the arena) he will spawn but become hostile if you get close to him. He opened the first door but after killing the enemies that spawned he appeared and attacked me (his spawn point was next to me). 
After this he kept attacking me, while untargetable, and never opened the 2nd door. Had to hearth out afterwards due to fight becoming unbeatable and having no escape.

**Comment by wow-mania** [comment]
Need to set REACT_PASSIVE to unit.

**Comment by fvicaria** [comment]
Fixed for. Release 10. Please confirm.
