### ISSUE TITLE
[Quest] The ring of exalted reputation with ashen verdicet 

### ISSUE THREAD

**Issue by eviatar10** [wow-mania/Redemption#520]
Hello, i earned exalted reputation with ashen verdicet and i know that should be somone at the icc that at him u complete the quest and get the finger (Ashen Band of Endless Might) , however, i enter icc and 2 people that got a blue question mark there, when i click them they dont give me any quest complete , i mean they are just talking to me but no one got any quest thing,i use wow mania launcher and all... i tried to reload and i opend a ticket but the gm told me to write my issue here, the character that i got the problem with is Uthar, have a good day.

**Comment by wow-mania** [comment]
Seems to be working fine for me.
![image](https://cloud.githubusercontent.com/assets/12248683/20456311/6edc0b6a-ae6c-11e6-853d-003ea6c1ecb6.png)
