### ISSUE TITLE
[Quest] Captain Tyralius

### ISSUE THREAD

**Issue by Readerlady** [wow-mania/Redemption#521]
It says to free the Captain from his prison but he is not in a prison. He is not targetable and none of the many prisons that I have opened contained him. The quest says the warden might have the key but he has never dropped a key for me.

**Comment by Emcitementz** [comment]
There's actually a problem with the fact that's Captain Tyralius is getting killed by the NPC's around him. That's gonna be fixed, there's no issue with the key itself, its drop rate was 100% and infact, it shouldn't even be that high, it should be around 40%. This is also going to be adapted.

**Comment by Readerlady** [comment]
This is still not working. I have an eternium key from the warden and I am standing in front of Captain Tyralius. He is standing on a little platform and is in a green/black swirly thing. I have no wheel to click on it or him. Maybe the key I need is not dropping? Is it a special key to save him and not a regular eternium key?
