### ISSUE TITLE
[Quest] A Mammoth Undertaking

### ISSUE THREAD

**Issue by iggapres** [wow-mania/Redemption#526]
In this Sholazar Basin quest, one has to attach a harness to a shattertusk mammoth to bring it back to the quest giver.
This quest is also a prerequisite for the killing of the brood mother, to obtain the achievement of Nessingwary in Sholozar.

At the time of writing, it is not possible to attach the harness. The casting bar appears, but nothing happens.
Entering in combat doesn't help.

**Comment by wow-mania** [comment]
Quest works. Just mount the mammoth without the harness.

**Comment by iggapres** [comment]
OK, thank you.
You just have to find the right ones (not speaking about the bulls). Not all shattertusk mammoths are mountable.

**Comment by Emcitementz** [comment]
I'll have a look, 

Just a quick note : When this is gonna be fixed, mounting the mammoth without using the harness will no longer work.
