### ISSUE TITLE
Flying taxi service.

### ISSUE THREAD

**Issue by dimman321** [wow-mania/Redemption#528]
100% of all attemptes to fly from dala to somewhere in tundra wow crashed, when i logged back in flying mount was all screwed up, flying in different direction, at some point even returning back to dalaran and then flying trough the terrain. Allso when you fly by one station at some point you dismount and mount back again. This prolongs the time it takes to reach your destination.

**Comment by fvicaria** [comment]
Not a server issue. Some corrupted file on the client. Try downloading the client again.
