### ISSUE TITLE
[Raid] Halion 25

### ISSUE THREAD

**Issue by elagen** [wow-mania/Redemption#530]
hi as we are doing Halion 25 normal - when we entered phase 3 the health regeneration that is suppose to happen to either the shadow or physical realm when the is no dps in the other realm is not happening so we can dps on 1 realm and the health is not regenerating

**Comment by Arawyn** [comment]
Confirmed. Comprehensive report states as follows:
In Phase 3 of Halion 25 man Normal, as the phase starts the disparity with DPS and health in the twilight realm and physical realm. The Health regeneration which should proc when the disparity between the 2 realms, does not proc. Meaning all players can go into the physical realm and DPS the boss without the worrying about twilight cutter or even having to split DPS. The Berserk also deals less damage than is supposed to and can be tanked with heconstant healing.
