### ISSUE TITLE
[Raid] Blackwing Lair

### ISSUE THREAD

**Issue by WastedMoment** [wow-mania/Redemption#532]
Myself (Sythilis), Shredder, Betty, and BM went into BWL. Nefarian is bugged. Starting out he is attackable in the first phase where you are only to kill the horde of adds that come in. But he immunes everything and throws shadowbolts. Once the add phase is done, Nefarian switches to dragon but in the middle of the transition he bugs out, and phases out completely, and so do the adds. Weeble was unable to respawn him, fix it or whatever. He raid rolled us some drops, but sadly we cant legit kill Nefarian for the true loot weekly, nor the Ach.

**Comment by wow-mania** [comment]
Fixed in dev. Need testers.

**Comment by WastedMoment** [comment]
How does one go about testing it, I would be interested
