### ISSUE TITLE
[Quest] Frostsaber provision

### ISSUE THREAD

**Issue by huqboss** [wow-mania/Redemption#535]
Reopen of issue #461 . It doesn't work as suppose, there is REPEATABLE quest "Frostsaber Provision" and "Winterfall Intrusion"instead of getting pet and do 20 DAILY quests from pet.

Previous just closed, looks like even without reading that there is OBSOLETE quest, which should be replaced with new one. Wasn't even confirmed after 1 month..

http://www.wowhead.com/quest=29034/they-grow-up-so-fast#see-also 
this is proper quest from patch 3.2 (same for horde, which actually works fine)

**Comment by wow-mania** [comment]
Add comment on the existing issue  would have the same effect. #461
