### ISSUE TITLE
[NPC] Galandria Nightbreeze

### ISSUE THREAD

**Issue by Readerlady** [wow-mania/Redemption#538]
Galandria Nightbreeze is standing on top of hill but all she does it whisper me "Up here on the hill, Katiya" When I go up the hill she does nothing. The item in my bad does nothing and there are three other people here who are saying the same in say chat. I researched and there was a previous ticket on this back in Jun that says it is fixed but I can't seem to get it to work.

**Comment by Kalasbyxan** [comment]
The npc (http://www.wow-mania.com/armory/?npc=19294) requires a die and respawn when this happens, or a server restart.
