### ISSUE TITLE
Quest, Last line of defense in Icecrown

### ISSUE THREAD

**Issue by djorjow** [wow-mania/Redemption#538]
Hello,

I'm currently trying to take a quest in the icecrown. It's called: The last line of defense. 
In which i need to kill 100 scourge and 3 drake with a cannon.
The problem is whenever i take this quest I start hovering in place, Being complete stuck and incapable of doing anything.

I tried everything i could.

Please help me

Regards,

Djor

**Comment by MrNorrell** [comment]
I have now seen this happen to mutliple players. This can be fixed by using .summon on them from anywhere. But as soon as they talk to the NPC or have the quest added they start to hover and jolt all over the place. This is a pretty bad issue for players and is complicated for GMs to help with.

**Comment by fvicaria** [comment]
Fixed.
