### ISSUE TITLE
[Quest] The Conquest Pit: Mad Furbolg

### ISSUE THREAD

**Issue by Ihatetotank** [wow-mania/Redemption#539]
The quest kill in the pit does not properly complete the quest. The preceding quest offers the same result

EDIT: Also the following quest as well. The Conquest Pit: Blood and Metal

**Comment by wow-mania** [comment]
http://www.wowhead.com/quest=12428/the-conquest-pit-mad-furbolg-fighting

**Comment by wow-mania** [comment]
![image](https://cloud.githubusercontent.com/assets/12248683/20639718/1a7a043a-b3c3-11e6-8072-863c4725088a.png)


All quests in the series worked fine for me.

**Comment by Ihatetotank** [comment]
That's really strange! Droggar sat there and watched it fail for us and
asked me to submit this Github. Were you in a group when you completed the
quest or were you solo?

**Comment by wow-mania** [comment]
I soloed. I will check if there is an issue in crediting a group. Thanks for the info.
