### ISSUE TITLE
[Quest] Taking Back Acherus

### ISSUE THREAD

**Issue by Nidhild** [wow-mania/Redemption#540]
For some odd reason I can't hand in the quest Taking Back Acherus.
http://www.wowhead.com/quest=13165/taking-back-acherus

Mograine doesnt have the questionmark over him, and relogging or abandon doesnt work either.

Using the laterst launcher and everything.

**Comment by Kalasbyxan** [comment]
Have recieved a few reports on this issue.

**Comment by wow-mania** [comment]
This quest simply requires The Light of Dawn completed properly. If you did not complete or did not use the Deathgate to go back after you won't see the question mark as you will be in the wrong phase.

**Comment by RyanOver9000** [comment]
This happened to me earlier today. (22/5/2017)  I completed "The Light of Dawn" and received the reward and the next quest "Taking Back Acherus".  I used my death gate ability and it took me to The new Acherus: The Ebon Hold zone (with the flight path master).  Highlord Darion Mograine does not have the quest turn in icon above his head.
