### ISSUE TITLE
[Quest] Divination: Gorefiend's Armor

### ISSUE THREAD

**Issue by Kalasbyxan** [wow-mania/Redemption#541]
The quest (http://www.wow-mania.com/armory/?quest=10634) is completed by killing Vhel'kur 8http://www.wow-mania.com/armory/?npc=21801) and looting Gorefiend's Armor (http://www.wow-mania.com/armory/?item=30797). 

I find Vhel'kur roaming the island but he is not visible to players.

**Comment by Emcitementz** [comment]
http://www.wowhead.com/item=30721/spectrecles

**Comment by Rushor** [comment]
remember that there are 2 kings of spectrecles. 

http://www.wowhead.com/item=30721/spectrecles#comments:id=2042405

**Comment by Emcitementz** [comment]
@Rushor 

Indeed, thanks for the info :)
