### ISSUE TITLE
[NPC] "Crowleg" Dan

### ISSUE THREAD

**Issue by Kalasbyxan** [wow-mania/Redemption#544]
The NPC (http://www.wow-mania.com/armory/?npc=24713) is an objective of the quest "Crowleg" Dan (http://www.wow-mania.com/armory/?quest=11479) where the player kills the NPC for quest credit.

Several reports of the NPC not being attackable rendering the quest uncompletable.

**Comment by Rushor** [comment]
because he is on a transport- creatures on transports often have these issues

**Comment by Marvin023** [comment]
this quest is still bug, npc stays neutral and can not attack him when you talk to him.
