### ISSUE TITLE
[Quest] The Tower of Althalaxx

### ISSUE THREAD

**Issue by whatapro** [wow-mania/Redemption#548]
The step in which you have to kill Athiricus Narassin at the tower of Althalaxx in Darkshore it's impossible to complete because inside the tower it's full of mobs (more than normal situation) and these mobs can also walk through the wall. If you aggro one of them you will aggro all of them.

Thank you

**Comment by Emcitementz** [comment]
This quest should be tricky to complete and needs to stay like it is now as showed here : http://www.wowhead.com/quest=1143/the-tower-of-althalaxx#comments:0
