### ISSUE TITLE
Quest Bug

### ISSUE THREAD

**Issue by zkakish** [wow-mania/Redemption#549]
I am on the quest Free Your Mind in Icecrown and i am supposed to use the rod on some NPCs but whenever i do nothing happens. ive read the text over and over again and im doing what im supposed to do. 
My name in game is Xantha. i need help completing the quest so i can continue the quest line,

Thanks

**Comment by wow-mania** [comment]
Ask a GM in-game for quest completion.

Issue should be fixed on the next update.

**Comment by zkakish** [comment]
Will the MP to EoF remain 5:1 forever?


________________________________
