### ISSUE TITLE
[Talent] Reflexive Shield

### ISSUE THREAD

**Issue by Mentorion** [wow-mania/Redemption#551]
#Hi, the talent Reflexive shield does nothing when investing points in it.

Class needed:    Priest
Talent tree:        Discipline
Talent:               Reflective Shield

Expected:          The shield should reflect, at 2 points invested in it, 45% of the damages absorbed.  
Actual result:     It does not reflect anything.

How-to-test:     Invest 2 points in the talent [Reflective Shield], use it on yourself then walk near an 
                         aggressive monster.  Observe the shield absorbing the damages without damaging the
                         monster.

*Edit*:  grammar

**Comment by Emcitementz** [comment]
I've just tested it now, it's working fine.
