### ISSUE TITLE
[Spell] Master Alchemy

### ISSUE THREAD

**Issue by Penskit** [wow-mania/Redemption#553]
Currently been a master alchemist (Transmute Master)  for over 3 months, and not one transmute has procced. A lot of time and effort goes into my profession, only to see the quest and work go to waste :( pls advise

**Comment by Emcitementz** [comment]
Which transmutation did you try ?

**Comment by wow-mania** [comment]
Please give an specific example that can be reproduced.

**Comment by Penskit** [comment]
I have tried to transmute eternals and gems to epic gems... always only 1 epic gem is transmuted from the mats

**Comment by hotdoggidy** [comment]
Ive had X-mute mastery for months. the procs are rare but they work for all transmutes. eternals, gems, saronite. Even TBC transmutes can proc up to 4 extra. Personally, ive found i get more procs when transmuting less mats. For instance having only 1 Eternal in my bag is more likely to yield extra procs than having a stack. i have procd Eye of zul x5 once and only once but that was enough to put my mind at ease.

**Comment by Penskit** [comment]
Lucky you hotdoggidy :)  I keep mats in bag to a minimum.. only what I need for each transmute, the rest are elsewhere on another toon for when needed.This does still not answer why my mastery does not work.

**Comment by Emcitementz** [comment]
> Ive had X-mute mastery for months. the procs are rare but they work for all transmutes. eternals, gems, saronite. Even TBC transmutes can proc up to 4 extra. Personally, ive found i get more procs when transmuting less mats. For instance having only 1 Eternal in my bag is more likely to yield extra procs than having a stack. i have procd Eye of zul x5 once and only once but that was enough to put my mind at ease.

The proc chance is 14% for all transmutations.
There's indeed a fact where you can be unlucky if you do that with a minimum of components.

**Comment by Penskit** [comment]
in game name is Penni. ty

**Comment by Penskit** [comment]
wohoo ... 1st transmute since Emcitementz last reply and get my 1st ever proc!! x3 no least :)
