### ISSUE TITLE
[Item] Greathelm of the Unyielding Bull xD

### ISSUE THREAD

**Issue by dimman321** [wow-mania/Redemption#555]
Hi! :S 
I think that greathelm of the unyielding bull doesnt look right xD
![rofl](https://cloud.githubusercontent.com/assets/13328157/9604571/ba01eb68-50b8-11e5-949f-3b8dfabf7c3f.jpg)
![wowscrnshot_090115_144816](https://cloud.githubusercontent.com/assets/13328157/9604577/c5e85944-50b8-11e5-937b-3621bf068689.jpg)

**Comment by fvicaria** [comment]
Fixed. Should be pushed tomorrow morning.
