### ISSUE TITLE
Amphitheater of Anguish quest chain start.

### ISSUE THREAD

**Issue by Tuckeroo** [wow-mania/Redemption#559]
No quest available for start of AoA quest chain despite being level 76. GM Tyreal gave me the start of the quest chain (Yggdras) in the end. However, the boss did not spawn when I received the quest in this manner.

**Comment by wow-mania** [comment]
The Champion's Call!
http://www.wowhead.com/quest=12974/the-champions-call
http://www.wowhead.com/npc=30137/shifty-vickers

Let me know in-game if you still have a problem with it.

**Comment by Tuckeroo** [comment]
haha Ok thanks. Sorry! :P
