### ISSUE TITLE
Quest Bug: Seal of Ascension

### ISSUE THREAD

**Issue by mercymania** [wow-mania/Redemption#563]
When trying to do the quest Seal of Ascension to create the key for UBRS players can succesfully take control of Emberstrife and use his breath on the unforged seal, unfortunately it doesn't do anything. Its suppose to upgrade the item into the forged seal but it doesn't work. This leaves players unable to complete the quest and acquire the key for UBRS.

**Comment by wow-mania** [comment]
Fixe. Will push on next update.
