### ISSUE TITLE
[Quest] The Flesh Giant Champion

### ISSUE THREAD

**Issue by Mark-Colley** [wow-mania/Redemption#564]
ID#13235
Hi this quest almost works.
You can kill Mobidus, but quest does not complete once he dies.
I am not sure if its because Olakin and the other npc's do too much damage or not.

Maddy

**Comment by wow-mania** [comment]
This is a general issue. You have to get a buddy to help you. You can't let the NPC do more than 50% of the damage or you don't get credit.
