### ISSUE TITLE
Broken Quest:  A Letter from the Admiral

### ISSUE THREAD

**Issue by travislaborde** [wow-mania/Redemption#566]
this is a quest in the Drenai area.  you get an item in the mail that you are supposed to click so that it can grant you the quest.  I have the item, and I've completed all quests in the surrounding area.  When I try to use the item to get the quest, it says that I am not eligible for the quest.

http://www.wowhead.com/item=24132/a-letter-from-the-admiral

I have found this same bug on other servers if that is any help.

**Comment by wow-mania** [comment]
Go get quest: Deliver Them From Evil... (9751) and complete it. Then go to the Messenger Hermesius and complete the quest Urgent Delivery (9672).
The other version (9672) is obtained by the letter. If you can't use the letter then you either have 9751 in your quest log or you already completed it and forgot ;)

**Comment by travislaborde** [comment]
I have completed Deliver Them From Evil on 8/31 at 17:10:15, and I have
completed Urgent Delivery on 8/31 at 17:10:15 too it seems.  This
information from my Carbonite addon which keeps a log of the quests I've
done.

I'm at a loss..
