### ISSUE TITLE
[Quest] Seeds of Chaos (13172)

### ISSUE THREAD

**Issue by ChemicalSerenity** [wow-mania/Redemption#59]
Killing the undead in the mine have no effect - the counter doesn't decrease. Quest is presently impossible to complete.

Repro steps:

- Obtain quest
- Go to mine
- Killin' in a coal mine, cut 'em down down down
- Eventually notice it has no effect
- Another day older and deeper in debt.

**Comment by fvicaria** [comment]
You need to ride the gryphon to do it.
