### ISSUE TITLE
Sorlof's Booty 11529

### ISSUE THREAD

**Issue by rbgspike** [wow-mania/Redemption#59]
After you kill Sorlof with the big gun no loot drops but it tells you it did. Tried twice with the same result

**Comment by Oriden** [comment]
He spawns a chest, tested this.

**Comment by genasi** [comment]
The goldpile that youre suppose to find can be hard to see, as Sorlof sometimes falls on top of it

**Comment by Kalasbyxan** [comment]
Run ashore as soon as you see the emote that Sorlof has dropped his booty and you will find it. It is hard to see.
