### ISSUE TITLE
[Instance] Trial of the Champion

### ISSUE THREAD

**Issue by Ashamedlol** [wow-mania/Redemption#6]
On this dungeon/instance, there are three stages: Wolf/horse fight -> PvP against three horde or alliance champions, then fight against priests and monks -> Paladin or Priest boss, then fight against deathknight who's on a mount and is fought 3 times after you kill the mount.

However the first two encounters drop no items although they should, and the second encounter's paladin or priest boss just walks into the crate and disappears. Deathknight (Black Knight) encounter is also buggy if he finds no target to damage or the group gets wiped, causing him to reset and become untargetable as it bugs the whole instance.

**Comment by Ashamedlol** [comment]
Also, the Mobs inside the instance attack you if you don't hide at the beginning, making them untargetable creatures that are killing you while not even being able to continue the instance.

**Comment by cajamangas** [comment]
still not fixed please make the black knight targetable

**Comment by wow-mania** [comment]
Both should be fixed on next update.
Please read this before logging bugs: 
ttps://github.com/wow-mania/Redemption/wiki/How-to-Properly-Report-an-Issue
