### ISSUE TITLE
Quest: Therylune's Escape.

### ISSUE THREAD

**Issue by Naigio** [wow-mania/Redemption#60]
A quest won't finish properly. "Therylune's Escape" in Darkshore around Master's Glaive.

I escorted her all the way out and she halted, the speech came up telling me she could make it the rest of the way but it never completed the objective. please send help.

I required the assistance of a GM to finish the quest.

Also I'm not sure 100% about this but I believe that it led to her never reappearing back at her spawn location, so nobody else could even acquire the quest while I was still "on it".

Edit: Additional information & Typo.

**Comment by wow-mania** [comment]
Fixed. It will be pushed next Wednesday at the latest.
