### ISSUE TITLE
Prospecting Ore

### ISSUE THREAD

**Issue by mentalhazord** [wow-mania/Redemption#600]
I have noticed that random prospects will yield no product. It has happened on multiple occasions. 

I will get a skill up and no gems or I will get nothing at all. 

I've searched on here for other issues for this same bug and says that their are 2 closed for the same problem and calls them duplicates and I can not find the original where it has been solved or is even an open work in progress.

**Comment by wow-mania** [comment]
Duplicate. Use search.

**Comment by mentalhazord** [comment]
I did use search, read my post. 

"I've searched on here for other issues for this same bug and says that their are 2 closed for the same problem and calls them duplicates and I can not find the original where it has been solved or is even an open work in progress."

So tell me where the ORIGINAL POST IS! That is why I made this one.
