### ISSUE TITLE
warrior charge-clipping/pathing issue

### ISSUE THREAD

**Issue by poohbear76** [wow-mania/Redemption#608]
in the hushbank of duskwood I used the warrior's charged and fell through the map to my death.  It almost happened a second time but I clipped through one side of a hill to the other.  The third time this happened I fell into the catacombs below tranquil garden cemetery.  Wile in the water the charge will respond with a no path available even though you have a clear shot to the target.

**Comment by wow-mania** [comment]
Known issue. Duplicate
