### ISSUE TITLE
Raise Dead Bug

### ISSUE THREAD

**Issue by Darthoridan** [wow-mania/Redemption#61]
I have experienced a bug with Raise Dead ability. Sometimes when i try to summon my Ghoul the Raise Dead spell gets grayed out and i cannot summon my Ghoul before i relogg. When this happens in the middle of an encounter or in PvP i am not able to Relogg to get my Raise Dead to work again.

A relogg does fix this issue however. But while in combat either in Raids or PvP you do not have the option nor the time to do so.

**Comment by wow-mania** [comment]
Fixed.
