### ISSUE TITLE
"Springing the Trap" bug

### ISSUE THREAD

**Issue by Poam** [wow-mania/Redemption#614]
The quest "Springing the Trap" (in Coldarra) gives a quest item "Raelorasz's Spark." The item, when used on the wooden fire signal at 25.3, 21.8, explodes and knocks over your character, but does not light the signal fire.

Below is a gif of the interaction with the quest item and the fire pit.

https://gyazo.com/99f22bea9b2da52cceaf49d7f15f772f

**Comment by wow-mania** [comment]
Duplicate #5
