### ISSUE TITLE
[QUEST] Dealing with Zeb'Sora

### ISSUE THREAD

**Issue by nickl384** [wow-mania/Redemption#621]
Elf Ears (Quest objective item) is not dropping whatsoever after ~25-30 kills.

**Comment by nickl384** [comment]
[Quest][Escort][Vorsha the Lasher][Ashenvale][Horde]

When in a party, accepting the quest after a party member starts it will not start the quest for you. 

Example: Player A starts escort quest. Player B accepts the escort quest when prompted with the dialogue box. Player B does not have quest in their log, and will not be credited for the quest, however Player A will have it, and will be credited.

**Comment by wow-mania** [comment]
Fixed for next update.

**Comment by wow-mania** [comment]
Please do not log multiple issues in one bug. Each issue should have it's on bug number.

**Comment by nickl384** [comment]
Alright sorry about that. I wasn't able to create a new post while this one was active, and I'm not sure why.
