### ISSUE TITLE
3 bugz

### ISSUE THREAD

**Issue by dinomtb** [wow-mania/Redemption#624]
Hi,

First, ty for your work.
Second, i did found bugz. Sry.
One is about looting. I'm trying to loot something, game decide that i'm too far from what i want to loot and then item get locked. Can't be looted anymore, even if i come closer.
Quest "Therylune's Escape", Drakshore, is bugged. Tryed 2 times and at the end of escort Q does not get complete.
Quest "Oh, it's real",Theramore Isle, part 6/7, i can't speak whit Major Mills.

Ty

**Comment by fvicaria** [comment]
Moved to individual bugs or duplicate.
