### ISSUE TITLE
Missing NPC (Arch Druid Fandrai Staghelm)

### ISSUE THREAD

**Issue by wernerbw** [wow-mania/Redemption#626]
NPC not in Darnassas on Quest completion - Crown of the Earth

**Comment by wow-mania** [comment]
He is there.
x = 10173
y = 2569.92
z = 1366.96

**Comment by wernerbw** [comment]
Well I'm stuck and can't find him...and can't move on til I do; also not allowed in chat for help.  Please help.  Is he always in same place?  Thanks.
