### ISSUE TITLE
Quest: Gerenzo's Orders.

### ISSUE THREAD

**Issue by Naigio** [wow-mania/Redemption#63]
In Stonetalon Mountain, inside the Windshear Mine, the quest given by the NPC "Piznik" won't start.

I accepted the quest & nothing happens.
I've waited more than 5 minutes and yet nothing happens.
No enemies spawn for me to protect him from and nor does the quest complete. 
I'd appreciate some help on this, or at least a fix would be nice.

**Comment by Oriden** [comment]
Fixed
