### ISSUE TITLE
Silence / interrupt effects not working on NPC's

### ISSUE THREAD

**Issue by Upperfoot** [wow-mania/Redemption#65]
@wow-mania 

Related issue: https://github.com/TrinityCore/TrinityCore/issues/1759
Commit to fix issue: https://github.com/TrinityCore/TrinityCore/pull/7658

Problem case:

Used warrior ability "Shield Bash" (which should lock them out of the spell school for 6 seconds) on Murloc Minor Tidecaller while casting the ability "Frostbolt", successfully interrupted with the above spell "Shield Bash" the NPC continues casting "Frostbolt" but should be locked out of that school and prevent them using "Frostbolt".

**Comment by Upperfoot** [comment]
@wow-mania Here is an official merge into the Trinitycore branch https://github.com/TrinityCore/TrinityCore/commit/f4c1a8fb2d6aff13f67dd2494dc18b481c548af9

**Comment by fvicaria** [comment]
Fixed on Release10.
