### ISSUE TITLE
[Item] Journal of Jandice Barov (gameobject #180794)

### ISSUE THREAD

**Issue by ChemicalSerenity** [wow-mania/Redemption#67]
Located in the basement of Scholomance next to (yes) Jandice Barov (), the book is supposed to teach people with the cloth tradeskill how to make Felcloth bags, and everyone else is supposed to see the following message:

*The journal of Jandice Barov is filled with ranting and raving about the undead. Towards the end of the book is what appears to be a tailoring pattern for the creation of a bag of some sort. Your understanding of tailoring is insufficient to decipher the pattern.*

When a non-cloth skilled person touches the book, nothing happens. Unsure of what happens with a cloth-skilled person.

Repro steps:

- Gain entrance to Scholomance
- Kill your way into the basement where Jandice Barov is
- Take her out
- Read her book
- Watch nothing happen

**Comment by fvicaria** [comment]
http://www.wowhead.com/object=180794/journal-of-jandice-barov#comments

Not working on 3.3.5.
