### ISSUE TITLE
Skullfish Soup does not give the right kind of buff

### ISSUE THREAD

**Issue by vincent1337** [wow-mania/Redemption#7]
Hello,
the item Skullfish Soup should give the "Enlightened" buff. Instead it gives "Well fed" which makes it not stack with Fish Feast which it should.
Lemontree

**Comment by wow-mania** [comment]
http://www.wowhead.com/item=33825/skullfish-soup

Regards,
JanitorWoW-Mania.comThe best WotLK server


Date: Sun, 21 Feb 2016 07:22:29 -0800

**Comment by wow-mania** [comment]
Fixed.
