### ISSUE TITLE
Dalaran client crash

### ISSUE THREAD

**Issue by NetDCon** [wow-mania/Redemption#70]
Whether flying in or porting in, about 29 out of 30 times my client crashes upon entry to Dalaran.  It's not a big fuss, but it is rather annoying when farming and having to stop in Dal, wait for crash, log back in and go back out.  From talking with fellow players I know this isn't something isolated to me, so I have included the crash output from Windows (Win10, AMD processor, Radeon 290X graphics)
[crash-001.txt](https://github.com/wow-mania/Redemption/files/299513/crash-001.txt)

**Comment by JuNNeZ** [comment]
Caused by memory lag, turn down view distance or use the 4gb patcher.

**Comment by wow-mania** [comment]
Also you can try changing your Texture Filtering settings. Reduce it to minimum.
