### ISSUE TITLE
[Quest] Generosity Abounds (13146)

### ISSUE THREAD

**Issue by ChemicalSerenity** [wow-mania/Redemption#71]
In this quest, you possess a Lithe Stalker and are told to use your Iron Chain spell (58203) to drag a bomb to a Lumbering Atrocity. If you click the spell without a bomb being targetted, the chain appears to attach to you - slowing you down, and unable to be detached so that one can attach to an actual bomb.

**Comment by fvicaria** [comment]
If you do that you will have to drop disguise and return to orb.
