### ISSUE TITLE
Still bugged; Quest: Gerenzo's Orders.

### ISSUE THREAD

**Issue by Naigio** [wow-mania/Redemption#72]
I put up a notice about a bugged quest here, "Gerenzo's Orders" in Stonetalon Mountains, given to the player by "Piznik" inside the Windshear Crag Mine a few days ago.

The issue then was it wouldn't start after you acquired the quest, which was fixed, but now there's a new issue.
The **issue now** is that either the last group of enemies don't appear and I'm unable to finish the quest, or the issue is that after the last group of enemies is killed, it simply won't complete the objective and you once again sit there without being able to complete the quest.

**Comment by Oriden** [comment]
Sorry for that, should be fixed now
