### ISSUE TITLE
[Quest] Mangletooth

### ISSUE THREAD

**Issue by Maxjestix** [wow-mania/Redemption#72]
NPC ID#37847
http://www.wowwiki.com/Mangletooth_%28pre-Cataclysm%29
After completing Blood Shards of Agamaggan, he would accept [Blood Shards] in exchange for buffs in the following quests:

[20] Agamaggan's Agility (repeatable)
[20] Agamaggan's Strength (repeatable)
[20] Razorhide (repeatable)
[20] Rising Spirit (repeatable)
[20] Spirit of the Wind (repeatable)
[20] Wisdom of Agamaggan (repeatable) 

However you don't get the Buffs upon completion.

**Comment by wow-mania** [comment]
May need to add script here.
Some auras:

48161          // Power Word: Fortitude        
48073          // Divine Spirit
20217          // Blessing of Kings
48469          // Mark of the wild
16609          // Spirit of Zandalar
15366          // Songflower Serenade
22888          // Rallying Cry of the Dragonslayer
57399          // Well Fed
17013          // Agamaggan's Agility
16612          // Agamaggan's Strength

**Comment by fvicaria** [comment]
Open the cage and complete quest.
