### ISSUE TITLE
Quest: Bodyguard for Hire & Quest: Gizelton Caravan

### ISSUE THREAD

**Issue by Naigio** [wow-mania/Redemption#74]
A quest, in Desolace given to the player by the NPC "Rigger Gizelton" and his Caravan called "Bodyguard for Hire" & "Gizelton Caravan" does not work as intended.

I accepted the quests and the NPC just stood there for ages, while the two kodo's carried on.
Eventually the NPC himself started to move but no enemies spawned and the objective was never completed when he walked past the camp, nor did he ever need assistance around Mannoroc Coven either.

The two kodo's and Goblin just went their merry way without ever needing help and the quest objectives never completed.
Please help!

**Comment by wow-mania** [comment]
Should be fixed for next Wednesday.
