### ISSUE TITLE
[Quest] The Purification of Quel'Delar

### ISSUE THREAD

**Issue by mariogotze** [wow-mania/Redemption#74]
There are many different IDs, because it's different for any race. 
ID#24598 
This one didn't work to a tauren. There is supposed to be a Warden of the Sunwell (ID#37523) next to Halduron Brightwing, who is supposed to port you. There is none there in front of the entrance, except Halduron.

**Comment by wow-mania** [comment]
I may add a hack to just complete this for now.

**Comment by fvicaria** [comment]
Fixed with a hack
