### ISSUE TITLE
Quest: If he Cannot be Turned

### ISSUE THREAD

**Issue by Taladric** [wow-mania/Redemption#76]
General Lightsbane has been killed a couple of times but I am not receiving credit for it.
![wowscrnshot_061016_154932](https://cloud.githubusercontent.com/assets/18010035/15980898/d6ea479e-2f23-11e6-8687-0e84c210864d.jpg)

**Comment by Taladric** [comment]
After the 7th time I received credit.  Not sure what was going on.

**Comment by loopty** [comment]
I too have experienced this problem, I have killed him several times and have not received any credit for the kill.
