### ISSUE TITLE
[Quest] The Battle For The Ebon Hold

### ISSUE THREAD

**Issue by Xxpala** [wow-mania/Redemption#78]
The quest "The battle for The Ebon Hold" requires a player to slay 10 Scourge and Patchwerk.
The despawn/respawn timers on Patchwerk are way too long which hinders the Deathknight to further progress.

http://www.wowhead.com/quest=13166/the-battle-for-the-ebon-hold

**Comment by Oriden** [comment]
Fixed

**Comment by Oriden** [comment]
Respawn time is 6 minutes, how long have you been waiting?

**Comment by Xxpala** [comment]
I was killing the adds around him for like 4 or 5 of their respawn cycles... after 20 minutes I just walked off and did something else. Must have been around 30 minutes.

**Comment by Calebrimbor** [comment]
Issue added to the BugTracker for testing. Thank you for your report. 
@ Testers: Please add all details such as links etc.

**Comment by Calebrimbor** [comment]
Tested it, the respawn time is set on 6 minutes, but killing him will tell you 36m remaining on the respawn time. I've timed it and it does respawn after 36m.

![wowscrnshot_091216_204846](https://cloud.githubusercontent.com/assets/20358867/18448267/b51349a8-792a-11e6-9b86-0abd82a3b717.jpg)

**Comment by wow-mania** [comment]
Lowered his Rank from 3 to 2. Tha should reduce the respawn time to 10min.

**Comment by Calebrimbor** [comment]
Status BugTracker set as 'Pending'.

**Comment by Calebrimbor** [comment]
Fix is confirmed. Status on BugTracker set as 'Fixed'.
