### ISSUE TITLE
Log on impossible

### ISSUE THREAD

**Issue by Hurrz** [wow-mania/Redemption#79]
I noticed this issue about 2 and a half weeks ago but was leaving for a holiday: When I enter my password (correctly) I get the standard error messg, along the lines "Unable to connect. please try again later. (...)".Tried connecting from a different computer but same issue. Same issue with another account. As far as I remember, I havent changed anything. Can you help me out here?

**Comment by wow-mania** [comment]
This is not a game issue. With 5 minutes looking on the website and forum you will find out the issue.
