### ISSUE TITLE
[Quest] Do Your Worst

### ISSUE THREAD

**Issue by wow-mania** [wow-mania/Redemption#8]
ID# 13305

This is on the horde side but I can safely assume it isn't working on the alliance side either. You are supposed to kill a bunch of mobs from the air ships flying around in IC. Unfortunately none of the mobs killed give you any credit for the completion of this quest. Mobs are as follows: Decomposed Ghoul ID# 31812, Frostskull Magus ID# 31813, and Bone Giant ID# 31815.

**Comment by mariogotze** [comment]
You are supposed to use Refurbished Demolisher as the description says, you can kill with the Demolisher Decomposed Ghouls and Frostskull Magus, but Bone Giant can't be one hitted with the Demolisher and he regens his HP after every hit. I did this by unmounting the Demolisher and killed the Giants by myself.

**Comment by fvicaria** [comment]
Fixed for Release 9.
