### ISSUE TITLE
[Quest] Going Bearback

### ISSUE THREAD

**Issue by Kalasbyxan** [wow-mania/Redemption#80]
The quest (http://www.wow-mania.com/armory/?quest=12851) starts with the player mounting Icefang. Then you trigger an automatic path for Icefang to move. All the player has to do is use the ability #1 Flaming Arrow (http://www.wow-mania.com/armory/?spell=54897) to set enemies ablaze.

Witnessed a player doing it twice with no credit of burning enemies and also did the run twice myself.

**Comment by Oriden** [comment]
Fixed on next update
