### ISSUE TITLE
[World] Half-buried Bottle (gameobject #2560)

### ISSUE THREAD

**Issue by ChemicalSerenity** [wow-mania/Redemption#81]
Picking up a half-buried bottle on the beaches of Stranglethorn should yield one of a few scrolls, a recipe, or the start of a quest (quest 26603 - Message in a Bottle). Instead, touching the bottle simply despawns the bottle with no effect (similar to problem with everfrost chip in northrend).

**Comment by fvicaria** [comment]
Works fine now. The quest you mentioned is for Cata only.
