### ISSUE TITLE
You know that unfinished instance in SW?

### ISSUE THREAD

**Issue by valenslunara** [wow-mania/Redemption#82]
Someone got stuck there. They were on the FP to SW and somehow ended up there. 
![wowscrnshot_052815_175947](https://cloud.githubusercontent.com/assets/11509141/7873079/8c4d8e0c-0563-11e5-8892-501f8cd87bc4.jpg)
They are currently stuck there and cannot hearth out. I just thought I would report it with a screenshot of what it looks like to someone on the outside.

**Comment by valenslunara** [comment]
Update! The person was able to hearth out if they precariously balanced right on the gate. Their name over their toon is missing and their tool tip info is still messed up, though.

**Comment by fvicaria** [comment]
Not a priority. I will talk to player to find out how he got there.
