### ISSUE TITLE
[Quest] Feeding Arngrim

### ISSUE THREAD

**Issue by Kalasbyxan** [wow-mania/Redemption#82]
The quest (http://www.wow-mania.com/armory/?quest=13046) is completed by using the item (http://www.wow-mania.com/armory/?item=42774) on a Jormungar, This summons an Arngrims Spirit that will eat the jormungar and give credit.

Using the item and summoning the giant gives no credit.

**Comment by wow-mania** [comment]
Fixed. Should be pushed tomorrow.
