### ISSUE TITLE
[Quest] Administering the Salve (#9447) *minor*

### ISSUE THREAD

**Issue by ChemicalSerenity** [wow-mania/Redemption#83]
After administering the salve, the afflicted orcs are supposed to don their armor, stand up and declare that they feel their strength return before fading out. The orcs don armor, give their lines and fade, but do not stand up. 

Yeah, it's minor, but it's visually perturbing to someone with latent OCD tendencies.

**Comment by fvicaria** [comment]
It's a SAI issue I fixed when it's in scripts to make them walk away and disappear but in SAI I can't.
