### ISSUE TITLE
Dungeon: Dire Maul (East Specifically)

### ISSUE THREAD

**Issue by Naigio** [wow-mania/Redemption#84]
Me and two friends wanted some adventure and took the journey to Diremaul.

We started with East, which quickly proved to be riddled with bugs.

Pusilin ran across the Sky, the little imp at the beginning.

Several mobs at the first gauntlet (Where you enter the instance, on the second floor. Above the little forest in the middle.) was jumping through the floor and not aggroing properly.

Hydrospawn proved to be quite the excellent rocket aiming for the moon when he shot up into the air when we aggroed him, NASA would be proud.

We didn't get to do the other two, due to issues with lag & such (This is was irrelevant to the dungeon), but I'd appreciate you folks taking a look at this, I mean sure, DM ain't the most popular dungeon, but it'd be nice if it was actually in working shape.

Perhaps take a quick peek at the other two as well, just to make sure.

**Comment by wow-mania** [comment]
Should be fixed by Wednesday.
