### ISSUE TITLE
(Quest) Last Line of Defense 

### ISSUE THREAD

**Issue by Bravopatriot** [wow-mania/Redemption#85]
Zone: Icecrown
Argent Crusade Faction Quest
Using WOW-Mania client and launcher
Using Windows 10
Toon Name: Bankerbit Lvl 80 Horde Warrior 

Description: previously when doing this quest the mobs would spawn but the turrets that are suppose to be on the wall would not. now no mobs are spawning and the walls completely disapear in the area. have abandoned quest multi times and restarted quest and same thing occurs. since this is a phased area event it is hard to get someone else to try to do it. Unable to move past this point and open the Faction "Ebon Blade" due to the starting quest for them being part of this chain.
![wowscrnshot_061616_184918](https://cloud.githubusercontent.com/assets/19984295/16136792/5345cf56-33f3-11e6-82a6-7902ebd5a752.jpg)
![wowscrnshot_061616_184934](https://cloud.githubusercontent.com/assets/19984295/16136791/5343f0f0-33f3-11e6-9f77-3e264585e7bc.jpg)

**Comment by Kalasbyxan** [comment]
Confirm empty phase when appearing. After completing quest, player automatically phased correctly and could hand in the quest.

**Comment by wow-mania** [comment]
Fixed for Wednesday.
