### ISSUE TITLE
(Instance, Heroic) Old Kindgom Bug

### ISSUE THREAD

**Issue by Bravopatriot** [wow-mania/Redemption#86]
Wow-Mania launcher and client
Windows 10
Horde, Bankbit Lvl 80 Warrior
Zone: Heroic Instance
Boss: Herald Volazj

Description of bug: When the boss cast "Insanity" and sends us to fight ourselves the adds are doing 4k damage per swing, with 5 mobs hitting you thats 20-25k dps per swing depending on armor. Unsure why after the boss was fixed so that you could no longer stun him or interrupt Insanity the adds are doing this much damage. Unable to complete dungeon after 3 tries. Not sure what the adds damage is set to scale but they are hitting harder than the elite trash mobs leading up to boss.

![wowscrnshot_061616_195221](https://cloud.githubusercontent.com/assets/19984295/16137770/4b30d8c0-33fc-11e6-9f79-dc69ccc2136a.jpg)
![wowscrnshot_061616_195228](https://cloud.githubusercontent.com/assets/19984295/16137771/4b34773c-33fc-11e6-9fe8-4422651c289a.jpg)

http://www.wowhead.com/npc=29311/herald-volazj

**Comment by wow-mania** [comment]
Cannot reproduce in latest release.
