### ISSUE TITLE
[Boss] Utgarde Pinnacle's "Skadi the Ruthless"

### ISSUE THREAD

**Issue by Kalasbyxan** [wow-mania/Redemption#87]
Utgarde Pinnacle (http://www.wow-mania.com/armory/?zone=1196) boss "Skadi the Ruthless" (http://www.wow-mania.com/armory/?npc=26693) is currently broken. No matter how many harpoons you shoot him with he does not fall from the sky as intended after being hit three times, rendering him unkillable. The waves of mobs spawning during the encounter is continuing.

With this boss broken players are unable to progress to the end of the instance due to the door being locked unitl Skadi is dead.

**Comment by wow-mania** [comment]
Should be fixed for next Wednesday (maybe earlier).
