### ISSUE TITLE
[Quest] Fresh Remounts

### ISSUE THREAD

**Issue by CasillasHorde** [wow-mania/Redemption#88]
The quest http://www.wow-mania.com/armory/?quest=12214 is completed by using The Onslaught Riding Crop http://www.wow-mania.com/armory/?item=37202 on a http://www.wow-mania.com/armory/?npc=27213 after killing it's rider. 

I can collect the Crop but cannot use it on any of the horses as they appear green and cannot be mounted.

**Comment by Nyeriah** [comment]
Is this still not working even after https://github.com/TrinityCore/TrinityCore/commit/2995e2a93551d17a6ebb79eb0694161e659d4fb3 ?
