### ISSUE TITLE
[Quest] Hah... You're not so big now!

### ISSUE THREAD

**Issue by Futuristics** [wow-mania/Redemption#89]
ID#11653
Borean Tundra: You must use the item " Crafty's ultra advanced proto-typical shortening blaster " on the enemies Magmoth Crushers and mates of Magmothregar, how ever the NPC's on the top of the hill tend to fall too far below the ground to even attack, and sometimes you have to shoot the same enemy multiple times, sometimes over 10 attempts to get the effect needed to kill the target and receive credit towards the objective. The quest is able to be completed  , however just very inconvenient.

**Comment by fvicaria** [comment]
Works fine you have to have the Magmoth Crushers below 50% to use the item.
THe falling below ground is another issue.

**Comment by Mayhem178** [comment]
The item does work on the Magmoth Crusher if they're below 50%.  However, it doesn't work on the  Mates of Magmothregar at all, regardless of their HP, and the item claims that it should.
