### ISSUE TITLE
[Quest Area] Argent Tournament

### ISSUE THREAD

**Issue by Ashamedlol** [wow-mania/Redemption#9]
In this area, the "mark of the valiant" or "mark of the champion" quests are bugged, why? Because the mobs are unattackable while you're on a mount, but if you dismount they immediately attack you and you can attack them so it becomes a disadvantage due to the fact that they can deal 3k-5k damage to you per 2 seconds with their mount while you have to fight them without one.

Also, not every combatant gives you mark of the champion, which is bugged as well.

**Comment by Assiah** [comment]
Having same issues: the only way to get the qeust accomplished is to get off your mount and kick their asses bare hands.

The whole area should be fixed. starting from the quests you get from your faction once the silver covenant chain is over.

**Comment by CaitlinGalanodel** [comment]
I've similar problem with the mark of the champion but Calvin doesn't speak to me even if I've the quest and I can't try to joust with them. In a similar way the black knight doesn't start. I need the object of the argent tournament, so...-_-

**Comment by Calebrimbor** [comment]
Issues are taken care of in other reports. CLosing this one
