### ISSUE TITLE
Return of the High Chief (Quest)

### ISSUE THREAD

**Issue by Taladric** [wow-mania/Redemption#91]
unable to aquire the piece of husk because it says "Item is already being used"
![wowscrnshot_061916_160234](https://cloud.githubusercontent.com/assets/18010035/16180567/af14c926-363d-11e6-9d48-34b827562075.jpg)

**Comment by Oriden** [comment]
Second time this is reported, adjusted a few things, tested on the developer server and it works fine. Should be working next update.
