### ISSUE TITLE
(NPC) Warrant Officer Tracy Proudwell

### ISSUE THREAD

**Issue by Naigio** [wow-mania/Redemption#92]
In Honor Hold, the NPC Tracy Proudwell (http://www.wow-mania.com/armory/?npc=18266) that gives the quest "Hellfire Fortifications" & proceeds to turn that into a repeatable quest.

After having done the quest & delivered it, the NPC persists on having the yellow quest sign above her head, and it shows on the minimap, although she offers no new quest, only the repeatable hellfire fortification. 
Would appreciate it if this was fixed :)

Needs tweaking and her yellow ! after the first hand in of the quest changing to a blue !

While not important, it's quite annoying.

**Comment by GMLucetta** [comment]
Confirmed. I've managed to reproduce. Issue is labeled as 'Confirmed' on the Bug Tracker. @Testers: Please add all details such as links etc.
