### ISSUE TITLE
NPC: Dreghood Brute, Ruins of Sha'naar, Hellfire Peninsula.

### ISSUE THREAD

**Issue by Naigio** [wow-mania/Redemption#93]
The NPC's in Ruins of Sha'naar aren't behaving properly.

After having killed their Illidari Taskmaster they don't run off like they should.
I made sure not to attack them at several occasions, only the taskmaster but they stayed to beat me up either way.

A fix would be appreciated :)

**Comment by Kalasbyxan** [comment]
Confirmed. 

Illidari Taskmaster (http://www.wow-mania.com/armory/?npc=17058) gets killed but Dreghood Brutes (http://www.wow-mania.com/armory/?npc=16938) stay hostile and attacks the player.
