### ISSUE TITLE
[Quest] A Special Surprise

### ISSUE THREAD

**Issue by kimsen33** [wow-mania/Redemption#96]
in this quest your suppose to kill a target inside a building but if you wait a little after she have said *put me out of my misery* she whil die to injuries and wont give you the kill and you have to wait for like 10min for the target to spawn again, i think you should take away so they cant die to injuries so people can read what the target says if they want to.

why i say target is because its a different target depending on your race

**Comment by fvicaria** [comment]
I reduced the respawn time to 4min and increased a bit her health.
