### ISSUE TITLE
[Quest] The Big Bone Worm

### ISSUE THREAD

**Issue by Naigio** [wow-mania/Redemption#97]
The clefthooves that I kill to use as lure to summon the big worm aint staying long enough for the worm to appear.

Basicly the bodies of the clefthooves disappear too quickly, so I can't use them to lure it out, leaving me unable to finish the quest.

**Comment by ThaydeGM** [comment]
tested http://www.wow-mania.com/armory/?quest=10930 today. The quest item Fumper http://www.wow-mania.com/armory/?item=31825 does not summon Enormous Worm in order for the player to receive the necessary quest item http://www.wow-mania.com/armory/?item=31826
