### ISSUE TITLE
[Quest] The Scarlet Apocalypse

### ISSUE THREAD

**Issue by kimsen33** [wow-mania/Redemption#97]
ID#12778
In this quest your suppose to fly down to death's breach and talk to arthas (lich king) but the problem is hes not standing where he should be, hes INSIDE of what he should stand ON but you can complete the quest by standing in front of the place (not where the ramp are, the other side) and jump onto 1 of the *feets* and then talk to him, but you should make so he stand on it or on the side of it :)

**Comment by fvicaria** [comment]
cannot reproduce.
