### ISSUE TITLE
[Quest] That's Asking A Lot - quest in Eastern Plaguelands isn't working properly. 

### ISSUE THREAD

**Issue by Nogrial** [wow-mania/Redemption#99]
That's Asking A Lot - quest in EP isn't working properly. I made all of the items it requested in quest. I am unable to turn it in to Smokey LaRue. Picked quest up at lvl 55 as a rogue, goblin.  ** update until after I hit 60, I don't know if any other factors took place**

Windows 7 / Using Client

**Comment by Oriden** [comment]
Works fine.
http://i.imgur.com/lNfgsvB.jpg
